def translateJepang(kata):
    kamusJepang = {
        
#jepang ke jepang
"neko": "neko",
"inu": "inu",
"zou": "zou",
"uma": "uma",
"saru": "saru",
"tora": "tora",
"cho": "cho",
"hebi": "hebi",
"tori": "tori",
"sakana": "sakana",
"ushi": "ushi",
"yagi": "yagi",
"usagi": "usagi",
"niwatori": "niwatori",
"ahiru": "ahiru",
"kangaru": "kangaru",
"kuma": "kuma",
"okami": "okami",
"raion": "raion",
"mushi": "mushi",
"ga": "ga",
"kaba": "kaba",
"kirin": "kirin",
"kaeru": "kaeru",
"kumo": "kumo",
"iruka": "iruka",
"kujira": "kujira",
"koumori": "koumori",
"nezumi": "nezumi",
"katatsumuri": "katatsumuri",
"tokage": "tokage",
"koala": "koala",
"tonbo": "tonbo",
"inko": "inko",
"hato": "hato",
"wani": "wani",
"kani": "kani",
"buta": "buta",
"paiton": "paiton",
"umihoshi": "umihoshi",
"remuru": "remuru",
"rakuda": "rakuda",
"hyou": "hyou",
"yamori": "yamori",
"yamakuzuri": "yamakuzuri",
"karasu": "karasu",
"fukurou": "fukurou",
"hiki": "hiki",
"banteng": "banteng",
"kame": "kame",
"kakatou": "kakatou",
"kame": "kame",
"chimpanji": "chimpanji",
"komodo doragon": "komodo doragon",
"burakku widou kumo": "burakku widou kumo",
"same": "same",
"ebi": "ebi",
"panda": "panda",
"kamome": "kamome",
"koubura": "koubura",
"ramu": "ramu",
"suzume": "suzume",
"ari": "ari",
"sutaanouzu mooru": "sutaanouzu mooru",
"robusutaa": "robusutaa",
"umigame": "umigame",
"chiita": "chiita",
"mOnaaku chou": "mOnaaku chou",
"washi": "washi",
"puma": "puma",
"huriru shaku": "huriru shaku",
"mokusei": "mokusei",
"shika": "shika",
"dokuhirokaeru": "dokuhirokaeru",
"pinku toodo taranchura": "pinku toodo taranchura",
"niwatori": "niwatori",
"umihoshi": "umihoshi",
"saihinocerosu": "saihinocerosu",
"yaseiusagi": "yaseiusagi",
"gacha": "gacha",
"paradaisu baado": "paradaisu baado",
"kingu chou": "kingu chou",
"akuteikku urufu": "akuteikku urufu",
"okapi": "okapi",
"bii itaa": "bii itaa",
"yasei buta": "yasei buta",
"koi": "koi",
"buruu tonbo": "buruu tonbo",
"ken hirameki": "ken hirameki",
"robusutaa": "robusutaa",
"reddo supaida": "reddo supaida",
"howaito umihoshi": "howaito umihoshi",
"hiyake no koara": "hiyake no koara",
"o-mume-sama": "o-mume-sama",
"suichu rui": "suichu rui",
"sasori": "sasori",
"kanuka": "kanuka",
"mizu nezumi": "mizu nezumi",
"suna gani": "suna gani",
"burakku umihoshi": "burakku umihoshi",
"hako kame": "hako kame",
"seisui wani": "seisui wani",
"yuki hato": "yuki hato",
"akai tonbo": "akai tonbo",
"hanmaa heddo shaku": "hanmaa heddo shaku",
"hitsuji": "hitsuji",
"kawauso": "kawauso",
"kanaria": "kanaria",
"kyoryu": "kyoryu",
"chairoi usagi": "chairoi usagi",
"kuroi ookami": "kuroi ookami",
"kamome": "kamome",
"hakucho": "hakucho",
"azarashi": "azarashi",
"tora neko": "tora neko",
"tokage": "tokage",
"afurika zou": "afurika zou",
"kogane no kumo": "kogane no kumo",
"beruga kujira": "beruga kujira",
"ranguru saru": "ranguru saru",
"akai kangaru": "akai kangaru",
"kassowari": "kassowari",
"haiiroi usagi": "haiiroi usagi",
"kiro tonbo": "kiro tonbo",
"chairoi hebi": "chairoi hebi",
"midori mushi": "midori mushi",
"gokiburi": "gokiburi",
"zebra": "zebra",
"paiton hebi": "paiton hebi",
"hachi": "hachi",
"orenji no chou": "orenji no chou",
"kuroi yasei buta": "kuroi yasei buta",
"aoi kumo": "aoi kumo",
"gurame": "gurame",
"haiiro no ookami": "haiiro no ookami",
"konjiki no kumo": "konjiki no kumo",
"shiroi gacha": "shiroi gacha",
"yuki fukurou": "yuki fukurou",
"perushan neko": "perushan neko",
"taranchura": "taranchura",
"shiroi nezumi": "shiroi nezumi",
"kingyo": "kingyo",
"shiroi usagi": "shiroi usagi",
"namazu": "namazu",
"chairoi kuma": "chairoi kuma",
"gureito honnodo": "gureito honnodo",
"kyodai kuroi kumo": "kyodai kuroi kumo",
"seisui kani": "seisui kani",
"osupurei": "osupurei",
"akai kamome": "akai kamome",
"kiiro no chou": "kiiro no chou",
"chairoi yasei buta": "chairoi yasei buta",
"sutinrei": "sutinrei",
"zebura uma": "zebura uma",
"ritoru fukurou": "ritoru fukurou",
"murasaki no chou": "murasaki no chou",
"shiroi yasei buta": "shiroi yasei buta",
"kyodai akai kumo": "kyodai akai kumo",
"midori kamome": "midori kamome",
"umi gani": "umi gani",
"maguro": "maguro",
"midori no kumo": "midori no kumo",
"kuroi neko": "kuroi neko",
"koi koi": "koi koi",
"kurokuroi usagi": "kurokuroi usagi",
"indo zou": "indo zou",
"kyodai kuroi ookami": "kyodai kuroi ookami",
"chairoi fukurou": "chairoi fukurou",
"kyodai konjiki no kumo": "kyodai konjiki no kumo",
"kuroi hakucho": "kuroi hakucho",
"midori hebi": "midori hebi",
"kyodai pinku toodo taranchura": "kyodai pinku toodo taranchura",
"kyodai hanmaa heddo shaku": "kyodai hanmaa heddo shaku",
"kyodai akai kamome": "kyodai akai kamome",
"kyodai aoi chou": "kyodai aoi chou",
"kyodai chairoi yasei buta": "kyodai chairoi yasei buta",
"kyodai namazu": "kyodai namazu",
"kyodai chairoi kuma": "kyodai chairoi kuma",
"kyodai midori kamome": "kyodai midori kamome",
"kyodai zebura uma": "kyodai zebura uma",
"kyodai kuroi neko": "kyodai kuroi neko",
"kyodai koi koi": "kyodai koi koi",
"kyodai indo zou": "kyodai indo zou",
"kyodai kurokuroi usagi": "kyodai kurokuroi usagi",
"kyodai kuroi ookami": "kyodai kuroi ookami",
"kyodai kyodai konjiki no kumo": "kyodai kyodai konjiki no kumo",
"kyodai kuroi hakucho": "kyodai kuroi hakucho",
"kyodai midori hebi": "kyodai midori hebi",
"chītā": "chītā",
"batarifurifisshu": "batarifurifisshu",
"gazeru": "gazeru",
"okutopasu": "okutopasu",
"pengin": "pengin",
"rainoserosu": "rainoserosu",
"jirafu": "jirafu",
"hejjihoggu": "hejjihoggu",
"igwana": "igwana",
"jagwā": "jagwā",
"kīui": "kīui",
"remā": "remā",
"mongūsu": "mongūsu",
"nyūto": "nyūto",
"orangutan": "orangutan",
"panda": "panda",
"kwokka": "kwokka",
"rakūn": "rakūn",
"surōsu": "surōsu",
"tapiru": "tapiru",
"anburera bādo": "anburera bādo",
"varuchā": "varuchā",
"wombatto": "wombatto",
"ekkusu-rei tetora": "ekkusu-rei tetora",
"yakku": "yakku",
"zēbu": "zēbu",
"arubatorosu": "arubatorosu",
"baison": "baison",
"kapibara": "kapibara",
"dorufin": "dorufin",
"erufantoshīru": "erufantoshīru",
"farukon": "farukon",
"gorira": "gorira",
"hanmingubādo": "hanmingubādo",
"inpara": "inpara",
"jerīfisshu": "jerīfisshu",
"koara": "koara",
"raionfisshu": "raionfisshu",
"mantisushirimp": "mantisushirimp",
"nāwaru": "nāwaru",
"oposamu": "oposamu",
"kueiru": "kueiru",
"rēndia": "rēndia",
"saramandā": "saramandā",
"tāshā": "tāshā",
"anburera bādo": "anburera bādo",
"vaipāfisshu": "vaipāfisshu",
"uippetto": "uippetto",
"ekkusu-rei tetora": "ekkusu-rei tetora",
"ieti": "ieti",
"zeburashāku": "zeburashāku",
"arupaka": "arupaka",
"barakūda": "barakūda",
"kamereon": "kamereon",
"dyūgongu": "dyūgongu",
"furamingo": "furamingo",
"natto": "natto",
"hanpbakkuhōru": "hanpbakkuhōru",
"jābanrainoserosu": "jābanrainoserosu",
"kingufishā": "kingufishā",
"rinkusu": "rinkusu",
"makō": "makō",
"nudoburanku": "nudoburanku",
"okapī": "okapī",
"puratipasu": "puratipasu",
"kwokka": "kwokka",
"rainoserosubītoru": "rainoserosubītoru",
"shīhōsu": "shīhōsu",
"tūkan": "tūkan",
"wakari": "wakari",
"varuchā": "varuchā",
"wōrasu": "wōrasu",
"ekkusu-rei tetora": "ekkusu-rei tetora",
"yakku": "yakku",
"zēbu": "zēbu",
"āmadirō": "āmadirō",
"binturongu": "binturongu",
"kaiman": "kaiman",
"dōru": "dōru",
"erando": "erando",
"fossa": "fossa",
"gurōwāmu": "gurōwāmu",
"hōsushukurabu": "hōsushukurabu",
"jaguarundi": "jaguarundi",
"kangarū": "kangarū",
"rebingu": "rebingu",
"māmosetto": "māmosetto",
"nematōdo": "nematōdo",
"orangutan": "orangutan",
"pōkupain": "pōkupain",
"kwokka": "kwokka",
"ratorusunēku": "ratorusunēku",
"shurimp": "shurimp",
"tapiru": "tapiru",
"āchin": "āchin",
"vōru": "vōru",
"wīzaru": "wīzaru",
"ekkusu-rei fissu": "ekkusu-rei fissu",
"yerōjyaketto": "yerōjyaketto",
"zēbu": "zēbu",
"avosetto": "avosetto",
"bongo": "bongo",
"chinchira": "chinchira",
"dōru": "dōru",
"īuwigu": "īuwigu",
"faiyafurai": "faiyafurai",
"gūsu": "gūsu",
"hejjihoggu": "hejjihoggu",
"inpara": "inpara",
"jagwā": "jagwā",
"kinkajū": "kinkajū",
"remā": "remā",
"makakku": "makakku",
"nutria": "nutria",
"osurotto": "osurotto",
"pangorin": "pangorin",
"kwokka": "kwokka",
"reddopanda": "reddopanda",
"shīdoragon": "shīdoragon",
"tāshā": "tāshā",
"wakari": "wakari",
"vaipāfisshu": "vaipāfisshu",
"wōvurīn": "wōvurīn",
"ekkusu-rei fissu": "ekkusu-rei fissu",
"yerōjyaketto": "yerōjyaketto",
"zēbu": "zēbu",
"ari": "ari",
"kōmori": "kōmori",
"wani": "wani",
"iruka": "iruka",
"zō": "zō",
"hayabusa": "hayabusa",
"harikein": "harikein",
"irawā": "irawā",
"jagwā": "jagwā",
"kuma": "kuma",
"ari": "ari",
"sāmandā": "sāmandā",
"taranchura": "taranchura",
"wēru": "wēru",
"zebu": "zebu",


        
# indo ke jepang

"kucing": "neko",
"anjing": "inu",
"sapi": "ushi",
"burung": "tori",
"kelinci": "usagi",
"babi": "buta",
"ikan": "sakana",
"kura-kura": "kame",
"ular": "hebi",
"gajah": "zou",
"harimau": "tora",
"kuda": "uma",
"kirin": "kirin",
"kepiting": "sarugani",
"rubah": "kitsune",
"anjing Akita": "akita inu",
"tengu": "tengu",
"tanuki": "tanuki",
"monyet": "saru",
"burung gereja": "suzume",
"kuda laut": "ushiwaka",
"paus": "kujira",
"ikan koi": "koi",
"lebah": "hachi",
"keong api": "hotaru",
"gurita": "ika",
"merak": "kujaku",
"berang-berang": "kawauso",
"beruang": "kuma",
"kelelawar": "komori",
"kupu-kupu": "konoha",
"kambing liar": "kamoshika",
"kanaria": "kanaria",
"koala": "koala",
"kelinci laut": "korin",
"rusa": "shika",
"burung camar": "shachou",
"singa": "shishi",
"hiu": "shark",
"jaguar": "jaguar",
"kupu-kupu": "joou",
"gurita": "tako",
"tengu": "tengu",
"tanuki": "tanuki",
"burung": "tori",
"kadal": "tokage",
"capung": "tombo",
"buaya": "nigai",
"boneka": "nuigurumi",
"hamster": "hamu",
"ayam muda": "hiyoko",
"gajah laut": "bou",
"burung phoenix": "houou",
"burung hantu": "fukurou",
"penguin": "pen",
"panda": "panda",
"kepiting": "pipi",
"kelabang": "hirameki",
"tapir": "baku",
"bajak laut": "mujaki",
"serangga": "mushi",
"kambing": "yagi",
"gecko": "yamori",
"kuda nil": "rakuda",
"singa": "raion",
"rubah": "regu",
"rusa kutub": "reindeer",
"gembala": "roba",
"hantu Jepang": "rokurokubi",
"buaya": "wani",
"elang": "washi",
"sapi": "ushi",
"burung robin": "ukitsumomiji",
"belut": "unagi",
"ulat daun": "enokimushi",
"udang": "ebi",

# inggris ke jepang

"cat" : "neko",
"dog": "inu",
"elephant": "zou",
"horse": "uma",
"monkey": "saru",
"tiger": "tora",
"butterfly": "cho",
"snake": "hebi",
"bird": "tori",
"fish": "sakana",
"cow": "ushi",
"goat": "yagi",
"rabbit": "usagi",
"chicken": "niwatori",
"duck": "ahiru",
"kangaroo": "kangaru",
"bear": "kuma",
"wolf": "okami",
"lion": "raion",
"beetle": "mushi",
"moth": "ga",
"hippopotamus": "kaba",
"giraffe": "kirin",
"frog": "kaeru",
"spider": "kumo",
"dolphin": "iruka",
"whale": "kujira",
"bat": "koumori",
"mouse": "nezumi",
"snail": "katatsumuri",
"lizard": "tokage",
"koala": "koala",
"dragonfly": "tonbo",
"parrot": "inko",
"pigeon": "hato",
"crocodile": "wani",
"crab": "kani",
"pig": "buta",
"python": "paiton",
"seahorse": "umihoshi",
"lemur": "remuru",
"camel": "rakuda",
"leopard": "hyou",
"pangolin": "yamori",
"porcupine": "yamakuzuri",
"crow": "karasu",
"owl": "fukurou",
"toad": "hiki",
"banteng": "banteng",
"turtle": "kame",
"cockatoo": "kakatou",
"turtle": "kame",
"chimpanzee": "chimpanji",
"komodo dragon": "komodo doragon",
"black widow spider": "burakku widou kumo",
"shark": "same",
"shrimp": "ebi",
"panda": "panda",
"seagull": "kamome",
"cobra": "koubura",
"ram": "ramu",
"sparrow": "suzume",
"ant": "ari",
"star-nosed mole": "sutaanouzu mooru",
"lobster": "robusutaa",
"sea turtle": "umigame",
"cheetah": "chiita",
"monarch butterfly": "mOnaaku chou",
"eagle": "washi",
"puma": "puma",
"whale shark": "huriru shaku",
"wood duck": "mokusei",
"deer": "shika",
"poison dart frog": "dokuhirokaeru",
"pink-toed tarantula": "pinku toodo taranchura",
"rooster": "niwatori",
"sea horse": "umihoshi",
"rhinoceros": "saihinocerosu",
"wild rabbit": "yaseiusagi",
"goose": "gacha",
"paradise bird": "paradaisu baado",
"king butterfly": "kingu chou",
"arctic wolf": "akuteikku urufu",
"okapi": "okapi",
"bee-eater bird": "bii itaa",
"wild boar": "yasei buta",
"koi fish": "koi",
"blue dragonfly": "buruu tonbo",
"swordfish": "ken hirameki",
"lobster": "robusutaa",
"red spider": "reddo supaida",
"white seahorse": "howaito umihoshi",
"sunbathing koala": "hiyake no koara",
"parakeet": "o-mume-sama",
"waterfowl": "suichu rui",
"scorpion": "sasori",
"stag": "kanuka",
"water rat": "mizu nezumi",
"sand crab": "suna gani",
"black seahorse": "burakku umihoshi",
"box turtle": "hako kame",
"freshwater crocodile": "seisui wani",
"snow dove": "yuki hato",
"red dragonfly": "akai tonbo",
"hammerhead shark": "hanmaa heddo shaku",
"sheep": "hitsuji",
"otter": "kawauso",
"canary": "kanaria",
"dinosaur": "kyoryu",
"brown rabbit": "chairoi usagi",
"black wolf": "kuroi ookami",
"seagull": "kamome",
"swan": "hakucho",
"seal": "azarashi",
"tabby cat": "tora neko",
"lizard": "tokage",
"African elephant": "afurika zou",
"golden spider": "kogane no kumo",
"beluga whale": "beruga kujira",
"langur monkey": "ranguru saru",
"red kangaroo": "akai kangaru",
"cassowary": "kassowari",
"grey rabbit": "haiiro no usagi",
"yellow dragonfly": "kiro tonbo",
"brown snake": "chairoi hebi",
"green beetle": "midori mushi",
"cockroach": "gokiburi",
"zebra": "zebra",
"python snake": "paiton hebi",
"bee": "hachi",
"orange butterfly": "orenji no chou",
"black wild boar": "kuroi yasei buta",
"blue spider": "aoi kumo",
"gourami fish": "gurame",
"grey wolf": "haiiro no ookami",
"golden orb spider": "konjiki no kumo",
"white goose": "shiroi gacha",
"snowy owl": "yuki fukurou",
"Persian cat": "perushan neko",
"tarantula": "taranchura",
"white mouse": "shiroi nezumi",
"goldfish": "kingyo",
"white rabbit": "shiroi usagi",
"catfish": "namazu",
"brown bear": "chairoi kuma",
"great horned owl": "gureito honnodo",
"giant black spider": "kyodai kuroi kumo",
"freshwater crab": "seisui kani",
"osprey": "osupurei",
"red seagull": "akai kamome",
"yellow butterfly": "kiiro no chou",
"brown wild pig": "chairoi yasei buta",
"stingray": "sutinrei",
"zebra horse": "zebura uma",
"little owl": "ritoru fukurou",
"purple butterfly": "murasaki no chou",
"white wild boar": "shiroi yasei buta",
"giant red spider": "kyodai akai kumo",
"green seagull": "midori kamome",
"sea crab": "umi gani",
"tuna fish": "maguro",
"green spider": "midori no kumo",
"black cat": "kuroi neko",
"koi carp": "koi koi",
"dark brown rabbit": "kurokuroi usagi",
"Indian elephant": "indo zou",
"giant black wolf": "kyodai kuroi ookami",
"brown owl": "chairoi fukurou",
"giant golden orb spider": "kyodai konjiki no kumo",
"black swan": "kuroi hakucho",
"green snake": "midori hebi",
"giant pink-toed tarantula": "kyodai pinku toodo taranchura",
"giant hammerhead shark": "kyodai hanmaa heddo shaku",
"giant red seagull": "kyodai akai kamome",
"giant blue butterfly": "kyodai aoi chou",
"giant brown wild pig": "kyodai chairoi yasei buta",
"giant catfish": "kyodai namazu",
"giant brown bear": "kyodai chairoi kuma",
"giant green seagull": "kyodai midori kamome",
"giant zebra horse": "kyodai zebura uma",
"giant black cat": "kyodai kuroi neko",
"giant koi carp": "kyodai koi koi",
"giant Indian elephant": "kyodai indo zou",
"giant dark brown rabbit": "kyodai kurokuroi usagi",
"giant black wolf": "kyodai kuroi ookami",
"giant giant golden orb spider": "kyodai kyodai konjiki no kumo",
"giant black swan": "kyodai kuroi hakucho",
"giant green snake": "kyodai midori hebi",
"cheetah": "chītā",
"butterflyfish": "batarifurifisshu",
"gazelle": "gazeru",
"octopus": "okutopasu",
"penguin": "pengin",
"rhinoceros": "rainoserosu",
"giraffe": "jirafu",
"hedgehog": "hejjihoggu",
"iguana": "igwana",
"jaguar": "jagwā",
"kiwi": "kīui",
"lemur": "remā",
"mongoose": "mongūsu",
"newt": "nyūto",
"orangutan": "orangutan",
"panda": "panda",
"quokka": "kwokka",
"raccoon": "rakūn",
"sloth": "surōsu",
"tapir": "tapiru",
"umbrellabird": "anburera bādo",
"vulture": "varuchā",
"wombat": "wombatto",
"x-raytetra": "ekkusu-rei tetora",
"yak": "yakku",
"zebu": "zēbu",
"albatross": "arubatorosu",
"bison": "baison",
"capybara": "kapibara",
"dolphin": "dorufin",
"elephantseal": "erufantoshīru",
"falcon": "farukon",
"gorilla": "gorira",
"hummingbird": "hanmingubādo",
"impala": "inpara",
"jellyfish": "jerīfisshu",
"koala": "koara",
"lionfish": "raionfisshu",
"mantisshrimp": "mantisushirimp",
"narwhal": "nāwaru",
"opossum": "oposamu",
"quail": "kueiru",
"reindeer": "rēndia",
"salamander": "saramandā",
"tarsier": "tāshā",
"umbrellabird": "anburera bādo",
"viperfish": "vaipāfisshu",
"whippet": "uippetto",
"xraytetra": "ekkusu-rei tetora",
"yeti": "ieti",
"zebrashark": "zeburashāku",
"alpaca": "arupaka",
"barracuda": "barakūda",
"chameleon": "kamereon",
"dugong": "dyūgongu",
"flamingo": "furamingo",
"gnat": "natto",
"humpbackwhale": "hanpbakkuhōru",
"javanrhinoceros": "jābanrainoserosu",
"kingfisher": "kingufishā",
"lynx": "rinkusu",
"macaw": "makō",
"nudibranch": "nudoburanku",
"okapi": "okapī",
"platypus": "puratipasu",
"quokka": "kwokka",
"rhinocerosbeetle": "rainoserosubītoru",
"seahorse": "shīhōsu",
"toucan": "tūkan",
"uakari": "wakari",
"vulture": "varuchā",
"walrus": "wōrasu",
"xraytetra": "ekkusu-rei tetora",
"yak": "yakku",
"zebu": "zēbu",
"armadillo": "āmadirō",
"binturong": "binturongu",
"caiman": "kaiman",
"dhole": "dōru",
"eland": "erando",
"fossa": "fossa",
"glowworm": "gurōwāmu",
"horseshoecrab": "hōsushukurabu",
"jaguarundi": "jaguarundi",
"kangaroo": "kangarū",
"lemming": "rebingu",
"marmoset": "māmosetto",
"nematode": "nematōdo",
"orangutan": "orangutan",
"porcupine": "pōkupain",
"quokka": "kwokka",
"rattlesnake": "ratorusunēku",
"shrimp": "shurimp",
"tapir": "tapiru",
"urchin": "āchin",
"vole": "vōru",
"weasel": "wīzaru",
"xrayfish": "ekkusu-rei fissu",
"yellowjacket": "yerōjyaketto",
"zebu": "zēbu",
"avocet": "avosetto",
"bongo": "bongo",
"chinchilla": "chinchira",
"dhole": "dōru",
"earwig": "īuwigu",
"firefly": "faiyafurai",
"goose": "gūsu",
"hedgehog": "hejjihoggu",
"impala": "inpara",
"jaguar": "jagwā",
"kinkajou": "kinkajū",
"lemur": "remā",
"macaque": "makakku",
"nutria": "nutria",
"ocelot": "osurotto",
"pangolin": "pangorin",
"quokka": "kwokka",
"redpanda": "reddopanda",
"seadragon": "shīdoragon",
"tarsier": "tāshā",
"uakari": "wakari",
"viperfish": "vaipāfisshu",
"wolverine": "wōvurīn",
"xrayfish": "ekkusu-rei fissu",
"yellowjacket": "yerōjyaketto",
"zebu": "zēbu",
"ant": "ari",
"bat": "kōmori",
"crocodile": "wani",
"dolphin": "iruka",
"elephant": "zō",
"falcon": "hayabusa",
"gazelle": "gazeru",
"hedgehog": "hejjihoggu",
"iguana": "iguana",
"jaguar": "jagwā",
"koala": "koara",
"lemur": "remā",
"mongoose": "mangūsu",
"newt": "imori",
"octopus": "tako",
"penguin": "pengin",
"rhinoceros": "sai",
"giraffe": "kirin",
"tiger": "tora",
"chimpanzee": "chimpanjī",
"komododragon": "komodo doragon",
"tarantula": "taranchura",
"whale": "kujira",
"zebra": "zeburā"


}

    return kamusJepang.get(kata.lower(), "KATA TIDAK DITEMUKAN DALAM KAMUS BAHASA JEPANG.")

def translateInggris(kata):
    kamusInggris = {
        
# inggris ke inggris

"cat": "cat",
"dog": "dog",
"elephant": "elephant",
"horse": "horse",
"monkey": "monkey",
"tiger": "tiger",
"butterfly": "butterfly",
"snake": "snake",
"bird": "bird",
"fish": "fish",
"cow": "cow",
"goat": "goat",
"rabbit": "rabbit",
"chicken": "chicken",
"duck": "duck",
"kangaroo": "kangaroo",
"bear": "bear",
"wolf": "wolf",
"lion": "lion",
"beetle": "beetle",
"moth": "moth",
"hippopotamus": "hippopotamus",
"giraffe": "giraffe",
"frog": "frog",
"spider": "spider",
"dolphin": "dolphin",
"whale": "whale",
"bat": "bat",
"mouse": "mouse",
"snail": "snail",
"lizard": "lizard",
"koala": "koala",
"dragonfly": "dragonfly",
"parrot": "parrot",
"pigeon": "pigeon",
"crocodile": "crocodile",
"crab": "crab",
"pig": "pig",
"python": "python",
"seahorse": "seahorse",
"lemur": "lemur",
"camel": "camel",
"leopard": "leopard",
"pangolin": "pangolin",
"porcupine": "porcupine",
"crow": "crow",
"owl": "owl",
"toad": "toad",
"banteng": "banteng",
"turtle": "turtle",
"cockatoo": "cockatoo",
"chimpanzee": "chimpanzee",
"komodo dragon": "komodo dragon",
"black widow spider": "black widow spider",
"shark": "shark",
"shrimp": "shrimp",
"panda": "panda",
"seagull": "seagull",
"cobra": "cobra",
"ram": "ram",
"sparrow": "sparrow",
"ant": "ant",
"star-nosed mole": "star-nosed mole",
"lobster": "lobster",
"sea turtle": "sea turtle",
"cheetah": "cheetah",
"monarch butterfly": "monarch butterfly",
"eagle": "eagle",
"puma": "puma",
"whale shark": "whale shark",
"wood duck": "wood duck",
"deer": "deer",
"poison dart frog": "poison dart frog",
"pink-toed tarantula": "pink-toed tarantula",
"rooster": "rooster",
"seahorse": "seahorse",
"rhinoceros": "rhinoceros",
"wild rabbit": "wild rabbit",
"goose": "goose",
"paradise bird": "paradise bird",
"king butterfly": "king butterfly",
"arctic wolf": "arctic wolf",
"okapi": "okapi",
"bee-eater bird": "bee-eater bird",
"wild boar": "wild boar",
"koi fish": "koi fish",
"blue dragonfly": "blue dragonfly",
"swordfish": "swordfish",
"lobster": "lobster",
"red spider": "red spider",
"white seahorse": "white seahorse",
"sunbathing koala": "sunbathing koala",
"parakeet": "parakeet",
"waterfowl": "waterfowl",
"scorpion": "scorpion",
"stag": "stag",
"water rat": "water rat",
"sand crab": "sand crab",
"black seahorse": "black seahorse",
"box turtle": "box turtle",
"freshwater crocodile": "freshwater crocodile",
"snow dove": "snow dove",
"red dragonfly": "red dragonfly",
"hammerhead shark": "hammerhead shark",
"sheep": "sheep",
"otter": "otter",
"canary": "canary",
"dinosaur": "dinosaur",
"brown rabbit": "brown rabbit",
"black wolf": "black wolf",
"seagull": "seagull",
"swan": "swan",
"seal": "seal",
"tabby cat": "tabby cat",
"lizard": "lizard",
"African elephant": "African elephant",
"golden spider": "golden spider",
"beluga whale": "beluga whale",
"langur monkey": "langur monkey",
"red kangaroo": "red kangaroo",
"cassowary": "cassowary",
"wild rabbit": "wild rabbit",
"yellow dragonfly": "yellow dragonfly",
"brown snake": "brown snake",
"green beetle": "green beetle",
"cockroach": "cockroach",
"zebra": "zebra",
"python snake": "python snake",
"bee": "bee",
"orange butterfly": "orange butterfly",
"black wild boar": "black wild boar",
"blue spider": "blue spider",
"gourami fish": "gourami fish",
"grey wolf": "grey wolf",
"golden orb spider": "golden orb spider",
"white goose": "white goose",
"snowy owl": "snowy owl",
"Persian cat": "Persian cat",
"tarantula": "tarantula",
"white mouse": "white mouse",
"goldfish": "goldfish",
"white rabbit": "white rabbit",
"catfish": "catfish",
"brown bear": "brown bear",
"great horned owl": "great horned owl",
"giant black spider": "giant black spider",
"freshwater crab": "freshwater crab",
"osprey": "osprey",
"red seagull": "red seagull",
"yellow butterfly": "yellow butterfly",
"brown wild pig": "brown wild pig",
"stingray": "stingray",
"zebra horse": "zebra horse",
"little owl": "little owl",
"purple butterfly": "purple butterfly",
"white wild boar": "white wild boar",
"giant red spider": "giant red spider",
"giant green seagull": "giant green seagull",
"sea crab": "sea crab",
"tuna fish": "tuna fish",
"green spider": "green spider",
"black cat": "black cat",
"koi carp": "koi carp",
"dark brown rabbit": "dark brown rabbit",
"Indian elephant": "Indian elephant",
"giant black wolf": "giant black wolf",
"brown owl": "brown owl",
"giant golden orb spider": "giant golden orb spider",
"black swan": "black swan",
"green snake": "green snake",
"giant pink-toed tarantula": "giant pink-toed tarantula",
"giant hammerhead shark": "giant hammerhead shark",
"giant red seagull": "giant red seagull",
"giant blue butterfly": "giant blue butterfly",
"giant brown wild pig": "giant brown wild pig",
"giant catfish": "giant catfish",
"giant brown bear": "giant brown bear",
"giant green seagull": "giant green seagull",
"giant zebra horse": "giant zebra horse",
"giant black cat": "giant black cat",
"giant koi carp": "giant koi carp",
"giant Indian elephant": "giant Indian elephant",
"giant dark brown rabbit": "giant dark brown rabbit",
"giant black wolf": "giant black wolf",
"giant giant golden orb spider": "giant giant golden orb spider",
"giant black swan": "giant black swan",
"giant green snake": "giant green snake",

"cheetah": "cheetah",
  "butterflyfish": "butterflyfish",
  "gazelle": "gazelle",
  "octopus": "octopus",
  "penguin": "penguin",
  "rhinoceros": "rhinoceros",
  "giraffe": "giraffe",
  "hedgehog": "hedgehog",
  "iguana": "iguana",
  "jaguar": "jaguar",
  "kiwi": "kiwi",
  "lemur": "lemur",
  "mongoose": "mongoose",
  "newt": "newt",
  "orangutan": "orangutan",
  "panda": "panda",
  "quokka": "quokka",
  "raccoon": "raccoon",
  "sloth": "sloth",
  "tapir": "tapir",
  "umbrellabird": "umbrellabird",
  "vulture": "vulture",
  "wombat": "wombat",
  "x-raytetra": "x-raytetra",
  "yak": "yak",
  "zebu": "zebu",
  "albatross": "albatross",
  "bison": "bison",
  "capybara": "capybara",
  "dolphin": "dolphin",
  "elephantseal": "elephant seal",
  "falcon": "falcon",
  "gorilla": "gorilla",
  "hummingbird": "hummingbird",
  "impala": "impala",
  "jellyfish": "jellyfish",
  "koala": "koala",
  "lionfish": "lionfish",
  "mantisshrimp": "mantis shrimp",
  "narwhal": "narwhal",
  "opossum": "opossum",
  "quail": "quail",
  "reindeer": "reindeer",
  "salamander": "salamander",
  "tarsier": "tarsier",
  "umbrellabird": "umbrellabird",
  "viperfish": "viperfish",
  "whippet": "whippet",
  "xraytetra": "x-ray tetra",
  "yeti": "yeti",
  "zebrashark": "zebra shark", 
  "alpaca": "alpaca",
  "barracuda": "barracuda",
  "chameleon": "chameleon",
  "dugong": "dugong",
  "flamingo": "flamingo",
  "gnat": "gnat",
  "humpbackwhale": "humpback whale",
  "impala": "impala",
  "javanrhinoceros": "Javan rhinoceros",
  "kingfisher": "kingfisher",
  "lynx": "lynx",
  "macaw": "macaw",
  "nudibranch": "nudibranch",
  "okapi": "okapi",
  "platypus": "platypus",
  "quokka": "quokka",
  "rhinocerosbeetle": "rhinoceros beetle",
  "seahorse": "seahorse",
  "toucan": "toucan",
  "uakari": "uakari",
  "vulture": "vulture",
  "walrus": "walrus",
  "xraytetra": "x-ray tetra",
  "yak": "yak",
  "zebu": "zebu",
  "armadillo": "armadillo",
  "binturong": "binturong",
  "caiman": "caiman",
  "dhole": "dhole",
  "eland": "eland",
  "fossa": "fossa",
  "glowworm": "glowworm",
  "horseshoecrab": "horseshoe crab",
  "impala": "impala",
  "jaguarundi": "jaguarundi",
  "kangaroo": "kangaroo",
  "lemming": "lemming",
  "marmoset": "marmoset",
  "nematode": "nematode",
  "orangutan": "orangutan",
  "porcupine": "porcupine",
  "quokka": "quokka",
  "rattlesnake": "rattlesnake",
  "shrimp": "shrimp",
  "tapir": "tapir",
  "urchin": "urchin",
  "vole": "vole",
  "weasel": "weasel",
  "xrayfish": "x-ray fish",
  "yellowjacket": "yellowjacket",
  "zebu": "zebu",
  "avocet": "avocet",
  "bongo": "bongo",
  "chinchilla": "chinchilla",
  "dhole": "dhole",
  "earwig": "earwig",
  "firefly": "firefly",
  "goose": "goose",
  "hedgehog": "hedgehog",
  "impala": "impala",
  "jaguar": "jaguar",
  "kinkajou": "kinkajou",
  "lemur": "lemur",
  "macaque": "macaque",
  "nutria": "nutria",
  "ocelot": "ocelot",
  "pangolin": "pangolin",
  "quokka": "quokka",
  "redpanda": "red panda",
  "seadragon": "seadragon",
  "tarsier": "tarsier",
  "uakari": "uakari",
  "viperfish": "viperfish",
  "wolverine": "wolverine",
  "xrayfish": "x-ray fish",
  "yellowjacket": "yellowjacket",
  "zebu": "zebu",
  "ant": "ant",
  "bat": "bat",
  "crocodile": "crocodile",
  "dolphin": "dolphin",
  "elephant": "elephant",
  "falcon": "falcon",
  "gazelle": "gazelle",
  "hedgehog": "hedgehog",
  "iguana": "iguana",
  "jaguar": "jaguar",
  "koala": "koala",
  "lemur": "lemur",
  "mongoose": "mongoose",
  "newt": "newt",
  "octopus": "octopus",
  "penguin": "penguin",
  "rhinoceros": "rhinoceros",
  "giraffe": "giraffe",
  "tiger": "tiger",
  "chimpanzee": "chimpanzee",
  "komodo dragon": "komodo dragon",
  "tarantula": "tarantula",
  "whale": "whale",
  "zebra": "zebra",
        
#indo ke inggris

"kucing" : "cat",
"anjing" : "dog",
"gajah" : "elephant",
"kuda" : "horse",
"monyet" : "monkey",
"harimau" : "tiger",
"kupu-kupu" : "butterfly",
"ular" : "snake",
"burung" : "bird",
"ikan" : "fish",
"sapi" : "cow",
"kambing" : "goat",
"kelinci" : "rabbit",
"ayam" : "chicken",
"bebek" : "duck",
"kanguru" : "kangaroo",
"beruang" : "bear",
"serigala" : "wolf",
"singa" : "lion",
"kumbang" : "beetle",
"kupu-kupu malam" : "moth",
"kuda nil" : "hippopotamus",
"jerapah" : "giraffe",
"katak" : "frog",
"laba-laba" : "spider",
"lumba-lumba" : "dolphin",
"paus" : "whale",
"kelelawar" : "bat",
"tikus" : "mouse",
"kelomang" : "snail",
"cicak" : "lizard",
"koala" : "koala",
"capung" : "dragonfly",
"beo" : "parrot",
"merpati" : "pigeon",
"ruak-ruak" : "crocodile",
"kepiting" : "crab",
"babi" : "pig",
"ular python" : "python",
"kuda laut" : "seahorse",
"monyet ekor panjang" : "lemur",
"unta" : "camel",
"macan tutul" : "leopard",
"trenggiling" : "pangolin",
"landak" : "porcupine",
"gagak" : "crow",
"burung hantu" : "owl",
"kodok" : "toad",
"banteng" : "banteng",
"kura-kura" : "turtle",
"kakatua" : "cockatoo",
"penyu" : "turtle",
"simpanse" : "chimpanzee",
"komodo" : "komodo dragon",
"laba-laba hitam" : "black widow spider",
"hiu" : "shark",
"udang" : "shrimp",
"panda" : "panda",
"burung camar" : "seagull",
"ular cobra" : "cobra",
"gembala jantan" : "ram",
"burung gereja" : "sparrow",
"semut" : "ant",
"harimau bintang" : "star-nosed mole",
"lobster" : "lobster",
"penyu laut" : "sea turtle",
"macan" : "cheetah",
"kupu-kupu monark" : "monarch butterfly",
"elang" : "eagle",
"puma" : "puma",
"hiu paus" : "whale shark",
"bebek hutan" : "wood duck",
"kijang" : "deer",
"katak beracun" : "poison dart frog",
"laba-laba merah jambu" : "pink-toed tarantula",
"ayam jantan" : "rooster",
"kuda laut laut" : "sea horse",
"badak" : "rhinoceros",
"kelinci liar" : "wild rabbit",
"angsa" : "goose",
"cendrawasih" : "paradise bird",
"kupu-kupu raja" : "king butterfly",
"serigala kutub" : "arctic wolf",
"jerapah okapi" : "okapi",
"burung pemakan lebah" : "bee-eater bird",
"celeng" : "wild boar",
"ikan koi" : "koi fish",
"capung biru" : "blue dragonfly",
"ikan paus" : "swordfish",
"camar" : "lobster",
"laba-laba merah" : "red spider",
"kuda laut gergaji" : "sawfish",
"kancil" : "mouse deer",
"burung hantu elang" : "eagle owl",
"beruang kutub" : "polar bear",
"lalat" : "fly",
"bintang laut" : "starfish",
"babi hutan" : "wild pig",
"serigala hutan" : "woodland wolf",
"kuda laut putih" : "white seahorse",
"koala berjemur" : "sunbathing koala",
"burung beo" : "parakeet",
"bebek air" : "waterfowl",
"kalajengking" : "scorpion",
"rusa" : "stag",
"tikus air" : "water rat",
"kepiting pasir" : "sand crab",
"kuda laut hitam" : "black seahorse",
"kura-kura darat" : "box turtle",
"buaya air tawar" : "freshwater crocodile",
"merpati salju" : "snow dove",
"capung merah" : "red dragonfly",
"ikan hiu" : "hammerhead shark",
"domba" : "sheep",
"berang-berang" : "otter",
"burung kenari" : "canary",
"dinosaurus" : "dinosaur",
"kelinci cokelat" : "brown rabbit",
"serigala hitam" : "black wolf",
"burung camar laut" : "seagull",
"kepala angsa" : "swan",
"anjing laut" : "seal",
"kucing belang" : "tabby cat",
"kadal" : "lizard",
"gajah Afrika" : "African elephant",
"laba-laba emas" : "golden spider",
"paus putih" : "beluga whale",
"monyet langur" : "langur monkey",
"kanguru merah" : "red kangaroo",
"burung kasuari" : "cassowary",
"kelinci abu-abu" : "grey rabbit",
"capung kuning" : "yellow dragonfly",
"kucing siam" : "Siamese cat",
"kerbau" : "buffalo",
"katak hijau" : "green frog",
"ular cokelat" : "brown snake",
"kumbang hijau" : "green beetle",
"kecoa" : "cockroach",
"zebra" : "zebra",
"ular piton" : "python snake",
"lebah" : "bee",
"kupu-kupu oranye" : "orange butterfly",
"babi hutan hitam" : "black wild boar",
"laba-laba biru" : "blue spider",
"ikan gurame" : "gourami fish",
"serigala kelabu" : "grey wolf",
"laba-laba jaring emas" : "golden orb spider",
"angsa putih" : "white goose",
"burung hantu salju" : "snowy owl",
"kucing persia" : "Persian cat",
"laba-laba besar" : "tarantula",
"tikus putih" : "white mouse",
"ikan mas" : "goldfish",
"kelinci putih" : "white rabbit",
"ikan lele" : "catfish",
"beruang cokelat" : "brown bear",
"burung hantu besar" : "great horned owl",
"laba-laba hitam besar" : "giant black spider",
"kepiting air tawar" : "freshwater crab",
"elang laut" : "osprey",
"burung camar merah" : "red seagull",
"kupu-kupu kuning" : "yellow butterfly",
"babi hutan cokelat" : "brown wild pig",
"ikan pari" : "stingray",
"kuda zebra" : "zebra horse",
"burung hantu kecil" : "little owl",
"kupu-kupu ungu" : "purple butterfly",
"babi hutan putih" : "white wild boar",
"laba-laba merah besar" : "giant red spider",
"burung camar hijau" : "green seagull",
"kepiting air laut" : "sea crab",
"ikan tuna" : "tuna fish",
"laba-laba hijau" : "green spider",
"kucing hitam" : "black cat",
"ikan mas koki" : "koi carp",
"kelinci cokelat tua" : "dark brown rabbit",
"gajah India" : "Indian elephant",
"serigala hitam besar" : "giant black wolf",
"burung hantu cokelat" : "brown owl",
"laba-laba jaring emas besar" : "giant golden orb spider",
"angsa hitam" : "black swan",
"ular hijau" : "green snake",
"laba-laba merah jambu besar" : "giant pink-toed tarantula",
"ikan hiu besar" : "giant hammerhead shark",
"burung camar merah besar" : "giant red seagull",
"kupu-kupu biru besar" : "giant blue butterfly",
"babi hutan cokelat besar" : "giant brown wild pig",
"ikan lele besar" : "giant catfish",
"beruang cokelat besar" : "giant brown bear",
"burung camar hijau besar" : "giant green seagull",
"kuda zebra besar" : "giant zebra horse",
"kucing hitam besar" : "giant black cat",
"ikan mas koki besar" : "giant koi carp",
"gajah India besar" : "giant Indian elephant",
"kelinci cokelat tua besar" : "giant dark brown rabbit",
"serigala hitam besar" : "giant black wolf",
"laba-laba jaring emas besar" : "giant giant golden orb spider",
"angsa hitam besar" : "giant black swan",
"ular hijau besar" : "giant green snake",

#Jepang ke inggris

"neko": "cat",
"inu": "dog",
"zou": "elephant",
"uma": "horse",
"saru": "monkey",
"tora": "tiger",
"cho": "butterfly",
"hebi": "snake",
"tori": "bird",
"sakana": "fish",
"ushi": "cow",
"yagi": "goat",
"usagi": "rabbit",
"niwatori": "chicken",
"ahiru": "duck",
"kangaru": "kangaroo",
"kuma": "bear",
"okami": "wolf",
"raion": "lion",
"mushi": "beetle",
"ga": "moth",
"kaba": "hippopotamus",
"kirin": "giraffe",
"kaeru": "frog",
"kumo": "spider",
"iruka": "dolphin",
"kujira": "whale",
"koumori": "bat",
"nezumi": "mouse",
"katatsumuri": "snail",
"tokage": "lizard",
"koala": "koala",
"tonbo": "dragonfly",
"inko": "parrot",
"hato": "pigeon",
"wani": "crocodile",
"kani": "crab",
"buta": "pig",
"paiton": "python",
"umihoshi": "seahorse",
"remuru": "lemur",
"rakuda": "camel",
"hyou": "leopard",
"yamori": "pangolin",
"yamakuzuri": "porcupine",
"karasu": "crow",
"fukurou": "owl",
"hiki": "toad",
"banteng": "banteng",
"kame": "turtle",
"kakatou": "cockatoo",
"kame": "turtle",
"chimpanji": "chimpanzee",
"komodo doragon": "komodo dragon",
"burakku widou kumo": "black widow spider",
"same": "shark",
"ebi": "shrimp",
"panda": "panda",
"kamome": "seagull",
"koubura": "cobra",
"ramu": "ram",
"suzume": "sparrow",
"ari": "ant",
"sutaanouzu mooru": "star-nosed mole",
"robusutaa": "lobster",
"umigame": "sea turtle",
"chiita": "cheetah",
"mOnaaku chou": "monarch butterfly",
"washi": "eagle",
"puma": "puma",
"huriru shaku": "whale shark",
"mokusei": "wood duck",
"shika": "deer",
"dokuhirokaeru": "poison dart frog",
"pinku toodo taranchura": "pink-toed tarantula",
"niwatori": "rooster",
"umihoshi": "seahorse",
"saihinocerosu": "rhinoceros",
"yaseiusagi": "wild rabbit",
"gacha": "goose",
"paradaisu baado": "paradise bird",
"kingu chou": "king butterfly",
"akuteikku urufu": "arctic wolf",
"okapi": "okapi",
"bii itaa": "bee-eater bird",
"yasei buta": "wild boar",
"koi": "koi fish",
"buruu tonbo": "blue dragonfly",
"ken hirameki": "swordfish",
"robusutaa": "lobster",
"reddo supaida": "red spider",
"howaito umihoshi": "white seahorse",
"hiyake no koara": "sunbathing koala",
"o-mume-sama": "parakeet",
"suichu rui": "waterfowl",
"sasori": "scorpion",
"kanuka": "stag",
"mizu nezumi": "water rat",
"suna gani": "sand crab",
"burakku umihoshi": "black seahorse",
"hako kame": "box turtle",
"seisui wani": "freshwater crocodile",
"yuki hato": "snow dove",
"akai tonbo": "red dragonfly",
"hanmaa heddo shaku": "hammerhead shark",
"hitsuji": "sheep",
"kawauso": "otter",
"kanaria": "canary",
"kyoryu": "dinosaur",
"chairoi usagi": "brown rabbit",
"kuroi ookami": "black wolf",
"kamome": "seagull",
"hakucho": "swan",
"azarashi": "seal",
"tora neko": "tabby cat",
"tokage": "lizard",
"afurika zou": "African elephant",
"kogane no kumo": "golden spider",
"beruga kujira": "beluga whale",
"ranguru saru": "langur monkey",
"akai kangaru": "red kangaroo",
"kassowari": "cassowary",
"haiiroi usagi": "grey rabbit",
"kiro tonbo": "yellow dragonfly",
"chairoi hebi": "brown snake",
"midori mushi": "green beetle",
"gokiburi": "cockroach",
"zebra": "zebra",
"paiton hebi": "python snake",
"hachi": "bee",
"orenji no chou": "orange butterfly",
"kuroi yasei buta": "black wild boar",
"aoi kumo": "blue spider",
"gurame": "gourami fish",
"haiiro no ookami": "grey wolf",
"konjiki no kumo": "golden orb spider",
"shiroi gacha": "white goose",
"yuki fukurou": "snowy owl",
"perushan neko": "Persian cat",
"taranchura": "tarantula",
"shiroi nezumi": "white mouse",
"kingyo": "goldfish",
"shiroi usagi": "white rabbit",
"namazu": "catfish",
"chairoi kuma": "brown bear",
"gureito honnodo": "great horned owl",
"kyodai kuroi kumo": "giant black spider",
"seisui kani": "freshwater crab",
"osupurei": "osprey",
"akai kamome": "red seagull",
"kiiro no chou": "yellow butterfly",
"chairoi yasei buta": "brown wild pig",
"sutinrei": "stingray",
"zebura uma": "zebra horse",
"ritoru fukurou": "little owl",
"murasaki no chou": "purple butterfly",
"shiroi yasei buta": "white wild boar",
"kyodai akai kumo": "giant red spider",
"midori kamome": "giant green seagull",
"umi gani": "sea crab",
"maguro": "tuna fish",
"midori no kumo": "green spider",
"kuroi neko": "black cat",
"koi koi": "koi carp",
"kurokuroi usagi": "dark brown rabbit",
"indo zou": "Indian elephant",
"kyodai kuroi ookami": "giant black wolf",
"chairoi fukurou": "brown owl",
"kyodai konjiki no kumo": "giant golden orb spider",
"kuroi hakucho": "black swan",
"midori hebi": "green snake",
"kyodai pinku toodo taranchura": "giant pink-toed tarantula",
"kyodai hanmaa heddo shaku": "giant hammerhead shark",
"kyodai akai kamome": "giant red seagull",
"kyodai aoi chou": "giant blue butterfly",
"kyodai chairoi yasei buta": "giant brown wild pig",
"kyodai namazu": "giant catfish",
"kyodai chairoi kuma": "giant brown bear",
"kyodai midori kamome": "giant green seagull",
"kyodai zebura uma": "giant zebra horse",
"kyodai kuroi neko": "giant black cat",
"kyodai koi koi": "giant koi carp",
"kyodai indo zou": "giant Indian elephant",
"kyodai kurokuroi usagi": "giant dark brown rabbit",
"kyodai kuroi ookami": "giant black wolf",
"kyodai kyodai konjiki no kumo": "giant giant golden orb spider",
"kyodai kuroi hakucho": "giant black swan",
"kyodai midori hebi": "giant green snake",
}

    return kamusInggris.get(kata.lower(), "KATA TIDAK DITEMUKAN DI KAMUS BAHASA INGGRIS.")

def translateIndo(kata):
    KamusIndonesia = {
        
#indo ke indo

"kucing": "kucing",
"anjing": "anjing",
"sapi": "sapi",
"burung": "burung",
"kelinci": "kelinci",
"babi": "babi",
"ikan": "ikan",
"kura-kura": "kura-kura",
"ular": "ular",
"gajah": "gajah",
"harimau": "harimau",
"kuda": "kuda",
"kirin": "kirin",
"kepiting": "kepiting",
"rubah": "rubah",
"anjing Akita": "anjing Akita",
"tengu": "tengu",
"tanuki": "tanuki",
"monyet": "monyet",
"burung gereja": "burung gereja",
"kuda laut": "kuda laut",
"paus": "paus",
"ikan koi": "ikan koi",
"lebah": "lebah",
"keong api": "keong api",
"gurita": "gurita",
"merak": "merak",
"berang-berang": "berang-berang",
"beruang": "beruang",
"kelelawar": "kelelawar",
"kupu-kupu": "kupu-kupu",
"kambing liar": "kambing liar",
"kanaria": "kanaria",
"koala": "koala",
"kelinci laut": "kelinci laut",
"rusa": "rusa",
"burung camar": "burung camar",
"singa": "singa",
"hiu": "hiu",
"jaguar": "jaguar",
"kupu-kupu": "kupu-kupu",
"gurita": "gurita",
"tengu": "tengu",
"tanuki": "tanuki",
"burung": "burung",
"kadal": "kadal",
"capung": "capung",
"buaya": "buaya",
"boneka": "boneka",
"hamster": "hamster",
"ayam muda": "ayam muda",
"gajah laut": "gajah laut",
"burung phoenix": "burung phoenix",
"burung hantu": "burung hantu",
"penguin": "penguin",
"panda": "panda",
"kepiting": "kepiting",
"kelabang": "kelabang",
"tapir": "tapir",
"bajak laut": "bajak laut",
"serangga": "serangga",
"kambing": "kambing",
"gecko": "gecko",
"kuda nil": "kuda nil",
"singa": "singa",
"rubah": "rubah",
"rusa kutub": "rusa kutub",
"gembala": "gembala",
"hantu Jepang": "hantu Jepang",
"buaya": "buaya",
"elang": "elang",
"sapi": "sapi",
"burung robin": "burung robin",
"belut": "belut",
"ulat daun": "ulat daun",
"udang": "udang",


        
# jepang ke indo

"neko": "kucing",
"inu": "anjing",
"ushi": "sapi",
"tori": "burung",
"usagi": "kelinci",
"buta": "babi",
"sakana": "ikan",
"kame": "kura-kura",
"hebi": "ular",
"zou": "gajah",
"tora": "harimau",
"uma": "kuda",
"kirin": "kirin",
"sarugani": "kepiting",
"kitsune": "rubah",
"akita inu": "anjing Akita",
"tengu": "tengu",
"tanuki": "tanuki",
"saru": "monyet",
"suzume": "burung gereja",
"ushiwaka": "kuda laut",
"kujira": "paus",
"koi": "ikan koi",
"hachi": "lebah",
"hotaru": "keong api",
"ika": "gurita",
"kujaku": "merak",
"kawauso": "berang-berang",
"kuma": "beruang",
"komori": "kelelawar",
"konoha": "kupu-kupu",
"kamoshika": "kambing liar",
"kanaria": "kanaria",
"koala": "koala",
"korin": "kelinci laut",
"shika": "rusa",
"shachou": "burung camar",
"shishi": "singa",
"shark": "hiu",
"jaguar": "jaguar",
"joou": "kupu-kupu",
"tako": "gurita",
"tengu": "tengu",
"tanuki": "tanuki",
"tori": "burung",
"tokage": "kadal",
"tombo": "capung",
"nigai": "buaya",
"nuigurumi": "boneka",
"hamu": "hamster",
"hiyoko": "ayam muda",
"bou": "gajah laut",
"houou": "burung phoenix",
"fukurou": "burung hantu",
"pen": "penguin",
"panda": "panda",
"pipi": "kepiting",
"hirameki": "kelabang",
"baku": "tapir",
"mujaki": "bajak laut",
"mushi": "serangga",
"yagi": "kambing",
"yamori": "gecko",
"rakuda": "kuda nil",
"raion": "singa",
"regu": "rubah",
"reindeer": "rusa kutub",
"roba": "gembala",
"rokurokubi": "hantu Jepang",
"wani": "buaya",
"washi": "elang",
"ushi": "sapi",
"ukitsumomiji": "burung robin",
"unagi": "belut",
"enokimushi": "ulat daun",
"ebi": "udang",
"chītā": "cheetah",
"batarifurifisshu": "ikan kupu-kupu",
"gazeru": "gazelle",
"okutopasu": "octopus",
"pengin": "penguin",
"rainoserosu": "badak",
"jirafu": "jerapah",
"hejjihoggu": "kelinci duri",
"igwana": "iguana",
"jagwā": "jaguar",
"kīui": "kiwi",
"remā": "lemur",
"mongūsu": "mongoose",
"nyūto": "salamander",
"orangutan": "orangutan",
"panda": "panda",
"kwokka": "quokka",
"rakūn": "raccoon",
"surōsu": "sloth",
"tapiru": "tapir",
"anburera bādo": "burung payung",
"varuchā": "vulture",
"wombatto": "wombat",
"ekkusu-rei tetora": "x-raytetra",
"yakku": "yak",
"zēbu": "zebu",
"arubatorosu": "albatross",
"baison": "bison",
"kapibara": "capybara",
"dorufin": "dolphin",
"erufantoshīru": "elephantseal",
"farukon": "falcon",
"gorira": "gorilla",
"hanmingubādo": "hummingbird",
"inpara": "impala",
"jerīfisshu": "giraffe",
"koara": "koala",
"raionfisshu": "lionfish",
"mantisushirimp": "mantisshrimp",
"nāwaru": "narwhal",
"oposamu": "opossum",
"kueiru": "quail",
"rēndia": "reindeer",
"saramandā": "salamander",
"tāshā": "tarsier",
"anburera bādo": "umbrellabird",
"vaipāfisshu": "viperfish",
"uippetto": "whippet",
"ekkusu-rei tetora": "xraytetra",
"ieti": "yeti",
"zeburashāku": "zebrashark",
"arupaka": "alpaca",
"barakūda": "barracuda",
"kamereon": "chameleon",
"dyūgongu": "dugong",
"furamingo": "flamingo",
"natto": "gnat",
"hanpbakkuhōru": "humpbackwhale",
"jābanrainoserosu": "javanrhinoceros",
"kingufishā": "kingfisher",
"rinkusu": "lynx",
"makō": "macaw",
"nudoburanku": "nudibranch",
"okapī": "okapi",
"puratipasu": "platypus",
"kwokka": "quokka",
"rainoserosubītoru": "rhinocerosbeetle",
"shīhōsu": "seahorse",
"tūkan": "toucan",
"wakari": "uakari",
"varuchā": "vulture",
"wōrasu": "walrus",
"ekkusu-rei tetora": "xraytetra",
"yakku": "yak",
"zēbu": "zebu",
"āmadirō": "armadillo",
"binturongu": "binturong",
"kaiman": "caiman",
"dōru": "dhole",
"erando": "eland",
"fossa": "fossa",
"gurōwāmu": "glowworm",
"hōsushukurabu": "horseshoecrab",
"jaguarundi": "jaguarundi",
"kangarū": "kangaroo",
"rebingu": "lemming",
"māmosetto": "marmoset",
"nematōdo": "nematode",
"orangutan": "orangutan",
"pōkupain": "porcupine",
"kwokka": "quokka",
"ratorusunēku": "rattlesnake",
"shurimp": "shrimp",
"tapiru": "tapir",
"āchin": "urchin",
"vōru": "vole",
"wīzaru": "weasel",
"ekkusu-rei fissu": "xrayfish",
"yerōjyaketto": "yellowjacket",
"zēbu": "zebu",
"ari": "ant",
"kōmori": "bat",
"wani": "crocodile",
"iruka": "dolphin",
"zō": "elephant",
"hayabusa": "falcon",
"harikein": "gazelle",
"irawā": "hedgehog",
"jagwā": "jaguar",
"kuma": "koala",
"ari": "lemur",
"sāmandā": "mongoose",
"taranchura": "tarantula",
"wēru": "whale",
"zebu": "zebra",

#inggris ke indo

"cat": "kucing",
"dog": "anjing",
"elephant": "gajah",
"horse": "kuda",
"monkey": "monyet",
"tiger": "harimau",
"butterfly": "kupu-kupu",
"snake": "ular",
"bird": "burung",
"fish": "ikan",
"cow": "sapi",
"goat": "kambing",
"rabbit": "kelinci",
"chicken": "ayam",
"duck": "bebek",
"kangaroo": "kanguru",
"bear": "beruang",
"wolf": "serigala",
"lion": "singa",
"beetle": "kumbang",
"moth": "kupu-kupu malam",
"hippopotamus": "kuda nil",
"giraffe": "jerapah",
"frog": "katak",
"spider": "laba-laba",
"dolphin": "lumba-lumba",
"whale": "paus",
"bat": "kelelawar",
"mouse": "tikus",
"snail": "kelomang",
"lizard": "cicak",
"koala": "koala",
"dragonfly": "capung",
"parrot": "beo",
"pigeon": "merpati",
"crocodile": "ruak-ruak",
"crab": "kepiting",
"pig": "babi",
"python": "ular python",
"seahorse": "kuda laut",
"lemur": "monyet ekor panjang",
"camel": "unta",
"leopard": "macan tutul",
"pangolin": "trenggiling",
"porcupine": "landak",
"crow": "gagak",
"owl": "burung hantu",
"toad": "kodok",
"banteng": "banteng",
"turtle": "kura-kura",
"cockatoo": "kakatua",
"turtle": "penyu",
"chimpanzee": "simpanse",
"komodo dragon": "komodo",
"black widow spider": "laba-laba hitam",
"shark": "hiu",
"shrimp": "udang",
"panda": "panda",
"seagull": "burung camar",
"cobra": "ular cobra",
"ram": "gembala jantan",
"sparrow": "burung gereja",
"ant": "semut",
"star-nosed mole": "harimau bintang",
"lobster": "lobster",
"sea turtle": "penyu laut",
"cheetah": "macan",
"monarch butterfly": "kupu-kupu monark",
"eagle": "elang",
"puma": "puma",
"whale shark": "hiu paus",
"wood duck": "bebek hutan",
"deer": "kijang",
"poison dart frog": "katak beracun",
"pink-toed tarantula": "laba-laba merah jambu",
"rooster": "ayam jantan",
"sea horse": "kuda laut laut",
"rhinoceros": "badak",
"wild rabbit": "kelinci liar",
"goose": "angsa",
"paradise bird": "cendrawasih",
"king butterfly": "kupu-kupu raja",
"arctic wolf": "serigala kutub",
"okapi": "jerapah okapi",
"bee-eater bird": "burung pemakan lebah",
"wild boar": "celeng",
"koi fish": "ikan koi",
"blue dragonfly": "capung biru",
"swordfish": "ikan paus",
"lobster": "camar",
"red spider": "laba-laba merah",
"sawfish": "kuda laut gergaji",
"mouse deer": "kancil",
"eagle owl": "burung hantu elang",
"polar bear": "beruang kutub",
"fly": "lalat",
"starfish": "bintang laut",
"wild pig": "babi hutan",
"woodland wolf": "serigala hutan",
"white seahorse": "kuda laut putih",
"sunbathing koala": "koala berjemur",
"parakeet": "burung beo",
"waterfowl": "bebek air",
"scorpion": "kalajengking",
"stag": "rusa",
"water rat": "tikus air",
"sand crab": "kepiting pasir",
"black seahorse": "kuda laut hitam",
"box turtle": "kura-kura darat",
"freshwater crocodile": "buaya air tawar",
"snow dove": "merpati salju",
"red dragonfly": "capung merah",
"hammerhead shark": "ikan hiu",
"sheep": "domba",
"otter": "berang-berang",
"canary": "burung kenari",
"dinosaur": "dinosaurus",
"brown rabbit": "kelinci cokelat",
"black wolf": "serigala hitam",
"seagull": "burung camar laut",
"swan": "kepala angsa",
"seal": "anjing laut",
"tabby cat": "kucing belang",
"lizard": "kadal",
"African elephant": "gajah Afrika",
"golden spider": "laba-laba emas",
"beluga whale": "paus putih",
"langur monkey": "monyet langur",
"red kangaroo": "kanguru merah",
"cassowary": "burung kasuari",
"grey rabbit": "kelinci abu-abu",
"yellow dragonfly": "capung kuning",
"Siamese cat": "kucing siam",
"buffalo": "kerbau",
"green frog": "katak hijau",
"brown snake": "ular cokelat",
"green beetle": "kumbang hijau",
"cockroach": "kecoa",
"zebra": "zebra",
"python snake": "ular piton",
"bee": "lebah",
"orange butterfly": "kupu-kupu oranye",
"black wild boar": "babi hutan hitam",
"blue spider": "laba-laba biru",
"gourami fish": "ikan gurame",
"grey wolf": "serigala kelabu",
"golden orb spider": "laba-laba jaring emas",
"white goose": "angsa putih",
"snowy owl": "burung hantu salju",
"Persian cat": "kucing persia",
"tarantula": "laba-laba besar",
"white mouse": "tikus putih",
"goldfish": "ikan mas",
"white rabbit": "kelinci putih",
"catfish": "ikan lele",
"brown bear": "beruang cokelat",
"great horned owl": "burung hantu besar",
"giant black spider": "laba-laba hitam besar",
"freshwater crab": "kepiting air tawar",
"osprey": "elang laut",
"red seagull": "burung camar merah",
"yellow butterfly": "kupu-kupu kuning",
"brown wild pig": "babi hutan cokelat",
"stingray": "ikan pari",
"zebra horse": "kuda zebra",
"little owl": "burung hantu kecil",
"purple butterfly": "kupu-kupu ungu",
"white wild boar": "babi hutan putih",
"giant red spider": "laba-laba merah besar",
"giant green seagull": "burung camar hijau besar",
"sea crab": "kepiting air laut",
"tuna fish": "ikan tuna",
"green spider": "laba-laba hijau",
"black cat": "kucing hitam",
"koi carp": "ikan mas koki",
"dark brown rabbit": "kelinci cokelat tua",
"Indian elephant": "gajah India",
"giant black wolf": "serigala hitam besar",
"brown owl": "burung hantu cokelat",
"giant golden orb spider": "laba-laba jaring emas besar",
"black swan": "angsa hitam",
"giant green snake": "ular hijau besar",
"cheetah": "cheetah",
"butterflyfish": "ikan kupu-kupu",
"gazelle": "gazelle",
"octopus": "gurita",
"penguin": "penguin",
"rhinoceros": "badak",
"giraffe": "jerapah",
"hedgehog": "landak",
"iguana": "iguana",
"jaguar": "jaguar",
"kiwi": "kiwi",
"lemur": "lemur",
"mongoose": "mongoose",
"newt": "salamander",
"orangutan": "orangutan",
"panda": "panda",
"quokka": "quokka",
"raccoon": "raccoon",
"sloth": "sloth",
"tapir": "tapir",
"umbrellabird": "burung payung",
"vulture": "burung nasar",
"wombat": "wombat",
"x-raytetra": "ikan x-ray",
"yak": "yak",
"zebu": "zebu",
"albatross": "albatros",
"bison": "bison",
"capybara": "capybara",
"dolphin": "lumba-lumba",
"elephantseal": "gajah laut",
"falcon": "falcon",
"gorilla": "gorila",
"hummingbird": "burung kolibri",
"impala": "impala",
"jellyfish": "ubur-ubur",
"koala": "koala",
"lionfish": "ikan singa",
"mantisshrimp": "udang raksasa",
"narwhal": "narwhal",
"opossum": "opossum",
"quail": "burung puyuh",
"reindeer": "rusa kutub",
"salamander": "salamander",
"tarsier": "tarsier",
"umbrellabird": "burung payung",
"viperfish": "ikan ular",
"whippet": "anjing whippet",
"xraytetra": "ikan x-ray",
"yeti": "yeti",
"zebrashark": "hiu zebra",
"alpaca": "alpaka",
"barracuda": "barracuda",
"chameleon": "bengkarung",
"dugong": "dugong",
"flamingo": "flamingo",
"gnat": "nyamuk kecil",
"humpbackwhale": "humpback whale",
"javanrhinoceros": "badak Jawa",
"kingfisher": "burung rajawali",
"lynx": "lynx",
"macaw": "burung macaw",
"nudibranch": "nudibranch",
"okapi": "okapi",
"platypus": "platipus",
"quokka": "quokka",
"rhinocerosbeetle": "kumbang badak",
"seahorse": "kuda laut",
"toucan": "toucan",
"uakari": "uakari",
"vulture": "burung nasar",
"walrus": "walrus",
"xraytetra": "ikan x-ray",
"yak": "yak",
"zebu": "zebu",
"armadillo": "armadillo",
"binturong": "binturong",
"caiman": "caiman",
"dhole": "anjing liar",
"eland": "eland",
"fossa": "fossa",
"glowworm": "cacing bercahaya",
"horseshoecrab": "keong kuda",
"jaguarundi": "jaguarundi",
"kangaroo": "kanguru",
"lemming": "lemming",
"marmoset": "marmoset",
"nematode": "nematoda",
"orangutan": "orangutan",
"porcupine": "porcupine",
"quokka": "quokka",
"rattlesnake": "ular berbisa",
"shrimp": "udang",
"tapir": "tapir",
"urchin": "bulu babi",
"vole": "vole",
"weasel": "musang",
"xrayfish": "ikan x-ray",
"yellowjacket": "tawon",
"zebu": "zebu",
"avocet": "avocet",
"bongo": "bongo",
"chinchilla": "chinchilla",
"dhole": "anjing liar",
"earwig": "cengkerik",
"firefly": "kunang-kunang",
"goose": "angsa",
"hedgehog": "landak",
"impala": "impala",
"jaguar": "jaguar",
"kinkajou": "kinkajou",
"lemur": "lemur",
"macaque": "monyet ekor panjang",
"nutria": "nutria",
"ocelot": "ocelot",
"pangolin": "pangolin",
"quokka": "quokka",
"redpanda": "red panda",
"seadragon": "naga laut",
"tarsier": "tarsier",
"uakari": "uakari",
"viperfish": "ikan ular",
"wolverine": "wolverine",
"xrayfish": "ikan x-ray",
"yellowjacket": "tawon",
"zebu": "zebu",
"ant": "semut",
"bat": "kelelawar",
"crocodile": "buaya",
"dolphin": "lumba-lumba",
"elephant": "gajah",
"falcon": "falcon",
"gazelle": "gazelle",
"hedgehog": "landak",
"iguana": "iguana",
"jaguar": "jaguar",
"koala": "koala",
"lemur": "lemur",
"mongoose": "mongoose",
"newt": "salamander",
"octopus": "gurita",
"penguin": "penguin",
"rhinoceros": "badak",
"giraffe": "jerapah",
"tiger": "harimau",
"chimpanzee": "chimpanzee",
"komododragon": "komodo dragon",
"tarantula": "tarantula",
"whale": "paus",
"zebra": "zebra"


    }

    return KamusIndonesia.get(kata, "KATA TIDAK DITEMUKAN DALAM KAMUS INDONESIA")


from flask import Flask, render_template, request, jsonify

app = Flask(__name__, static_url_path='/translate/static')

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/translate/templates', methods=['GET'])
def do_translate():
    translate = request.args.get('translate')
    pilihan = request.args.get('pilihan')

    if pilihan == "bahasa inggris":
        terjemahan = translateInggris(translate)
    elif pilihan == "bahasa jepang":
        terjemahan = translateJepang(translate)
    elif pilihan == "bahasa indonesia":
        terjemahan= translateIndo(translate)
    else:
        return jsonify({"error": "Pilihan tidak valid. Silakan pilih bahasa yang valid!"})

    return jsonify({"terjemahan": terjemahan})

if __name__ == '__main__':
    app.run(debug=True)