def translateJepang(kata):
    kamusJepang = {
    "selamat pagi": "ohayo",
    "selamat siang": "konnichiwa",
    "selamat malam": "konbanwa",
    "selamat makan": "ittadakimasu",
    "guru": "sensei",
    "teman": "tomodachi",
    "rumah": "ie",
    "mobil": "kuruma",
    "buku": "hon",
    "makanan": "tabemono",
    "minuman": "nomimono",
    "pagi": "asa",
    "siang": "hiru",
    "malam": "yoru",
    "sushi": "sushi",
    "kopi": "koohii",
    "air": "mizu",
    "sekolah": "gakkou",
    "kucing": "neko",
    "anjing": "inu",
    "bunga": "hana",
    "musik": "ongaku",
    "film": "eiga",
    "apakah": "ka",
    "suka": "suki",
    "tidak suka": "kirai",
    "angka": "suuji",
    "warna": "iro",
    "sore": "yūgata",
    "televisi": "terebi",
    "senang": "ureshii",
    "sedih": "kanashii",
    "malas": "namakemono",
    "cerita": "monogatari",
    "atas": "ue",
    "bawah": "shita",
    "panas": "atsui",
    "dingin": "samui",
    "hujan": "ame",
    "musim": "kisetsu",
    "apartemen": "apaatomento",
    "taman": "koen",
    "kota": "machinami",
    "kamar tidur": "shinshitsu",
    "kamar mandi": "ofuro",
    "pakaian": "fuku",
    "sepatu": "kutsu",
    "tas": "kaban",
    "uang": "okane",
    
  
"tiket": "chiketto",
    "telepon": "denwa",
    "komputer": "konpyuuta",
    "internet": "intanetto",
    
 
"restoran": "resutoran",
    "kucing": "neko",
    
    
"anjing": "inu",
    "burung": "tori",
    "ikan": "sakana",
    "buah": "kudamono",
    "sayur": "yasai",
    
   
"roti": "pan",
    "daging": "niku",
    "buah-buahan": "kajitsu",
    "sayuran": "yasai",
    "mangga": "mango",
    "keluarga": "kazoku",
    
  
"teman sekerja": "doukyuusei",
    "hobi": "shumi",
    "olahraga": "supootsu",
    "pemandangan": "keshiki",
    "museum": "bijutsukan",
    "kamera": "kamera",
    
 
"jalan": "michi",
    "tanda": "shirushi",
    "hujan deras": "osame",
    "kota": "tokai",
    "gunung": "yama",
    "pantai": "umibe",
    "pesawat": "hikouki",
    "kapal": "fune",
    "stasiun kereta": "eki",
    "taksi": "takushi",
    "hotel": "hoteru",
    "bandara": "kuukou",
    "aplikasi": "apuri",
    "foto": "shashin",
    "festival": "matsuri",
    "taman bermain": "yuuenchi",
    "liburan": "kyuujitsu",
    
   
"universitas": "daigaku",
    "pekerjaan": "shigoto",
    
  
"kesehatan": "kenkou",
    "dokter": "isha",
    
    
"apotek": "yakkyoku",
    "lapangan": "hiroba",
    
   
"sungai": "kawa",
    "danau": "mizuumi",
    "gunung berapi": "kazan",
    "gurun": "sabaku",
    "taman nasional": "kokuritsu kouen",
    "pulau": "shima",
    "kereta": "densha",
    "bis": "basu",
    
  
"sepeda": "jitensha",
    "motor": "baiku",
    "pesawat helikopter": "herikoputaa",
    "kapal selam": "sensuikan",
    "kantor": "kaisha",
    "karyawan": "shain",
    "bos": "shachou",
    "pohon": "ki",
    "bintang": "hoshi",
    "bulan": "tsuki",
    "matahari": "taiyou",
    "bumi": "chikyuu",
    "planet": "wakusei",
    "galaksi": "ginga",
    "teleskop": "teresukoopu",
    "robot": "robotto",
    "satelit": "eisei",
    "kometa": "hoshi-boshi",
    "energi": "enerugii",
    "listrik": "denki",
    "solar panel": "souraa paneru",
    "rambut": "kami",
    "mata": "me",
    "hidung": "hana",
    "mulut": "kuchi",
    
  
"telinga": "mimi",
    
 
"tangan": "te",
    
  
"kaki": "ashi",
    
   
"jari": "yubi",
    "tulang": "hone",
    "otak": "nou",
    "jantung": "shinzou",
    "paru-paru": "hai",
    "perut": "onaka",
    
    
"tulang belakang": "senaka",
 "pencuri": "touzoku",
    "polisi": "keisatsu",
    "penjara": "keimusho",
    "pahlawan": "eiyuu",
    
    
"monster": "kaibutsu",
    "mimpi": "yume",
    "kenangan": "kioku",
    "cinta": "ai",
    "kebahagiaan": "koufuku",
    "kesedihan": "kanashimi",
    "harapan": "kibou",
    
    
"keberhasilan": "seikou",
    
 
"kegagalan": "shippai",
    "senyuman": "egao",
    
   
"air mata": "namida",
    
    
"tawa": "warai",
    "berbicara": "hanasu",
    
  
"mendengarkan": "kiku",
    "menulis": "kaku",
    "melihat": "miru",
    
    
"merasa": "kanjiru",
    
   
"mengerti": "wakaru",
    "berjalan": "aruku",
    
    
"lari": "hashiru",
    
    

 
"berenang": "oyogu",
    "terbang": "tobu",
    "menari": "odoru",
    
   
"menggambar": "egaku",
    
   
"mendengar": "kiku",
    
   
"mengajar": "oshieru",
    "belajar": "manabu",
    
   
"tidur": "nemuru",
 "berbicara": "hanasu",
    "menyanyi": "utau",
    "memasak": "ryouri suru",
    "makan malam": "yuu shoku",
    "sarapan": "choushoku",
    "makan siang": "hiru gohan",
    "minum teh": "ocha o nomu",
    "membaca": "yomu",
    "menulis": "kaku",
    "bermain": "asobu",
    "berlibur": "kyuuka suru",
    "bermeditasi": "meisou suru",
    "bersepeda": "jitensha ni noru",
    "berenang": "oyogu",
    "bermain game": "geemu o suru",
    "memotret": "shashin o toru",
    
   
"berbelanja": "kaimono o suru",
    "berpikir": "kangaeru",
    "berdoa": "inoru",
    "menyapu": "soji o suru",
    "menyanyikan lagu": "uta o utau",
    "berlatih": "renshuu suru",
    "menggambar": "e o kaku",
    
  
"memotong": "kiru",
    "menjahit": "nuigurumi o shimeru",
    "menonton film": "eiga o miru",
    "mendengarkan musik": "ongaku o kiku",
    "mengemudi": "untensuru",
    "bermain musik": "ongaku o hiku",
    "berkebun": "niwa o sodateru",
    "mencuci": "arau",
    
   
"menyikat gigi": "hamigakimasu",
    "menyisir rambut": "kami o togu",
    "mandi": "abiru",
    
  
"menonton televisi": "terebi o miru",
    
  
"memasak": "ryouri suru",
    
 
"memotong": "kiru",
    "menyapu": "soji o suru",
    "menyiram tanaman": "ki o nomu",
    "memasang lampu": "denki o tsukeru",
    "membersihkan jendela": "mado o kirei ni suru",
    
   
"mengatur waktu": "jikan o seiri suru",
    "membaca buku": "hon o yomu",
    "menulis surat": "tegami o kaku",
    "berbicara di telepon": "denwa o suru",
    "memeriksa email": "meeru o kakunin suru",
    "mengirim pesan": "messeji o okuru",
    "menyimpan barang": "mono o shimau",
    "mengorganisir": "souzou suru",
    "memilih": "erabu",
    "menangis": "naaku",
    "tersenyum": "hohoemu",
    "bermain musik": "ongaku o hiku",
    "menggambar": "e o kaku",
    "bersepeda": "jitensha ni noru",
    "bermain game": "geemu o suru",
    "menari": "odoru",
    "bernyanyi": "utau",
    "menyanyikan lagu": "uta o utau",
    "bermain tenis": "tenisu o suru",
    "bermain golf": "gorufu o suru",
    "bermain sepak bola": "sakkaa o suru",
    "mendaki gunung": "yama o noboru",
    "mengunjungi museum": "bijutsukan o kengaku suru",
    "mengemudi mobil": "kuruma o unten suru",
    
 
"mengendarai sepeda motor": "baiku o unten suru",
    "memancing": "tsuri o suru",
    "mengembara": "tabi o suru",
    "mengikuti kelas": "jugyou ni kayou",
    "bermeditasi": "meisou suru",
    "berolahraga": "undou suru",
    "berfoto": "shashin o toru",
    "menghadiri pesta": "paatii ni iku",
    "berlibur": "kyuuka suru",
    "berjemur": "hi ni abiru",
    "menyusun puzzle": "pazuru o yaru",
    "mendengarkan musik": "ongaku o kiku",
    "membaca berita": "nyuusu o yomu",
    "menonton film": "eiga o miru",
    "bermain di taman": "koen de asobu",
    "bermain di pantai": "umibe de asobu",
    "berlayar": "seilaa o suru",
    "bermain catur": "shougi o suru",
    "bermain kartu": "kado o suru",
    "mengumpulkan koin": "kooin o atsumeru",
    "berdagang": "boueki suru",
    "berinvestasi": "toushi suru",
    "berdonasi": "kifu suru",
    "mengikuti kursus": "koushuu ni kayou",
    "berpartisipasi": "sanka suru",
    "berbicara bahasa Jepang": "nihongo de hanasu",
    "mendengarkan ceramah": "koorashia o kiku",
    "berdoa di kuil": "jinja de inoru",
    "bermain di taman bermain": "yuuenchi de asobu",
    
   
"berjemur di taman": "koen de hizamazuku",
    "berbicara dengan tetangga": "rinjin to hanasu",
    
 
"berbelanja di pasar": "ichiba de kaimono suru",
    
  
"menyelam di laut": "umibe de sukuramu",
    
  
"bermain dengan hewan peliharaan": "petto to asobu",
    "berkebun": "niwa o sodateru",
    
    

 
"melihat pemandangan": "keshiki o miru",
    
  
"mengamati bintang": "hoshi o kensatsu suru",
    "mencari harta karun": "takara o sagasu",
    "berkemah": "キャンプをする (kyanpu o suru)",
    
   
"menyelam": "ダイビングをする (daibingu o suru)",
    
   
"berfoto di tempat wisata": "kanko-jo de shashin o toru",
    "berpiknik di taman": "koen de pikunikku suru",
    "mengadakan pesta ulang tahun": "tanjobi no paatii o kaisai suru",
    
   
"membuat kerajinan tangan": "shuukougei o tsukuru",
    "menghadiri konser": "konseruto ni iku",
    
   
"berdiskusi": "ronbun o kiku",
    "berpikir kreatif": "sozouryoku o tsukau",
    "berbicara dalam rapat": "kaigi de hanasu",
    
   
"membuat rencana": "keikaku o suru",
    "mengelola waktu": "jikan o kanri suru",
    
   
"berlatih senam": "taiso o renshuu suru",
    
   
"mengikuti kelas seni bela diri": "budou no kurasu ni kayou",
    "menghadiri seminar": "semina ni iku",
    
   
"bermain teater": "gekijou de engeki o suru",
    "menyusun strategi": "sutoratejii o kumu",
    "mengikuti kursus keterampilan": "sukiru koushuu ni kayou",
    "membuat proyek DIY": "diy purojekuto o tsukuru",
    
   
"mengikuti kompetisi": "kontesuto ni sanka suru",
"mendaki tebing": "iya o noboru",
    
  
"mengikuti demonstrasi": "demosu ni sanka suru",
    
   
"berpartisipasi dalam festival": "matsuri ni sanka suru",
    
   
"bermain di hutan": "mori de asobu",
    
   
"menghadiri acara seni": "geijutsu sakuhin no kikaku ni sanka suru",
    
 
"bermain ski": "suki o suru",
    "mengikuti kelas yoga": "yoga no kurasu ni kayou",
    
   
"membuat vlog": "burogu bideo o tsukuru",
    "mendengarkan podcast": "podosuto o kiku",
    
   
"menyusun puzzle": "pazuru o toku",
    "mengikuti lomba lari": "rikujo ni sanka suru",
    
   
"mengikuti kursus bahasa asing": "gaikokugo no kurasu ni kayou",
    "berpartisipasi dalam permainan video": "bideo geemu ni sanka suru",
    "bermain board game": "boudo geemu o suru",
    
  
"membuat origami": "origami o tsukuru",
    "membuat perhiasan": "akusesari o tsukuru",
    "mendaki gunung bersalju": "yuki no aru yama o noboru",
    "berpartisipasi dalam flash mob": "furasshu mobu ni sanka suru",
    
    
"mengikuti kelas melukis": "e o kaku no kurasu ni kayou",
    
   

  
"berpartisipasi dalam acara amal": "ien katsudou ni sanka suru",
    "mengikuti kelas desain grafis": "gurafikku dezain no kurasu ni kayou",
    "menghadiri pameran seni": "geijutsu tenrankai ni mairu",
    "bermain alat musik": "gakki o hiku",
    
   
"membuat karya seni": "geijutsu sakuhin o tsukuru",
    "mendaki bukit": "oyama o noboru",
    "berpartisipasi dalam kelas memasak": "ryouri no kurasu ni sanka suru",
    
   
"membuat blog": "burogu o hajimeru",
    "mengikuti pelatihan kepemimpinan": "riidaashippu toriningu ni kayou",
    
 
"menghadiri konferensi": "kaigi ni sanka suru",
    
   
"berpartisipasi dalam pertunjukan teater": "gekijou no engeki ni sanka suru",
    "mengikuti kelas ketrampilan kerajinan": "kougei no kurasu ni kayou",
    
  
"mengikuti kelas menari": "nibu no kurasu ni kayou",
    
    

 
"mengikuti kelas memasak Jepang": "washoku no kurasu ni kayou",
    "membuat rencana perjalanan": "ryokou keikaku o suru",
    "mengikuti lomba renang": "suiei kontesuto ni sanka suru",
    
   
"bermain game papan": "boudo geemu o suru",
    
   
"bermain biola": "vaiorin o hiku",
    "bermain kartu": "kado o suru",
    
   
"mengikuti kelas menulis kreatif": "souzouryoku shuupurei no kurasu ni kayou",
    
   
"berpartisipasi dalam kelas fotografi": "shashin no kurasu ni sanka suru",
    "mengikuti kelas menulis": "shoosetsu no kurasu ni kayou",
    "mengikuti kursus keamanan online": "onrain anzen koushuu ni kayou",
    "mengikuti kelas manajemen waktu": "jikan kanri no kurasu ni kayou",
    "bermain permainan papan strategi": "sutoratejii boudo geemu o suru",
    
   
"mengikuti kursus seni lukis": "geijutsu gaikou no kurasu ni kayou",
    
   
"membuat rencana bisnis": "bijinesu puran o suru",
    "mendaki gunung bersama teman": "tomodachi to yama o noboru",
    "mengikuti kelas psikologi": "saikoroji no kurasu ni kayou",
    
 
"mengikuti kelas bahasa Jepang online": "onrain nihongo no kurasu ni kayou",
    "bermain game peran": "rooru geemu o suru",
    "berpartisipasi dalam kelas tata rias": "kezai no kurasu ni sanka suru",
    
 
"bermain permainan ponsel": "sumaho geemu o suru",
    
  
"mengikuti kelas desain mode": "fasshon dezain no kurasu ni kayou",
    
   
"bermain gitar": "gitaa o hiku",
    
   
"mengikuti kelas kecerdasan buatan": "jinkou chinou no kurasu ni kayou",
    "mengikuti kelas perencanaan keuangan": "kinnyuu keikaku no kurasu ni kayou",
    
   
"membuat playlist musik": "myujikku pureirisuto o tsukuru",
    
   
"mengikuti kelas bahasa asing": "gaikokugo no kurasu ni kayou",
    "mengikuti kelas ilmu komputer": "konpyuutaa kagaku no kurasu ni kayou",
    "membuat jurnal harian": "nikki o tsukuru",
    "mengikuti kelas teknik komunikasi": "komyunikeeshon kougaku no kurasu ni kayou",
    "mengikuti kelas seni teater": "engeki geijutsu no kurasu ni kayou",
    "mengikuti kelas biologi": "seibutsugaku no kurasu ni kayou",
    
   
"mengikuti kelas fisika": "butsuri kagaku no kurasu ni kayou",
    "mengikuti kelas kimia": "kagaku kagaku no kurasu ni kayou",
    
   
"bermain catur online": "onrain shougi o suru"

}

    return kamusJepang.get(kata.lower(), "KATA TIDAK DITEMUKAN DALAM KAMUS BAHASA JEPANG.")

def translateInggris(kata):
    kamusInggris = {
    "selamat malam":"good night",
    "rumah": "house",
    "mobil": "car",
    "pohon": "tree",
    "kucing": "cat",
    "anjing": "dog",
    "makanan": "food",
    "air": "water",
    "buku": "book",
    "sekolah": "school",
    "komputer": "computer",
    "harimau": "tiger",
    "burung": "bird",
    "kopi": "coffee",
    "meja": "table",
    "kursi": "chair",
    "jendela": "window",
    "pintu": "door",
    "televisi": "television",
    "telepon": "phone",
    "roti": "bread",
    "kamera": "camera",
    "jam": "clock",
    "lampu": "lamp",
    "pakaian": "clothes",
    "kunci": "key",
    "sendok": "spoon",
    "garpu": "fork",
    "pisau": "knife",
    "gelas": "glass",
    "piring": "plate",
    "matahari": "sun",
    "bulan": "moon",
    "bintang": "star",
    "gunung": "mountain",
    "laut": "sea",
    "langit": "sky",
    "tanah": "earth",
    "angin": "wind",
    "api": "fire",
    "salju": "snow",
    "hujan": "rain",
    "awan": "cloud",
    "rumput": "grass",
    "bunga": "flower",
    "buah": "fruit",
    "sayuran": "vegetable",
    "ikan": "fish",
    "udang": "shrimp",
    "ayam": "chicken",
    "sapi": "cow",
    "kuda": "horse",
    "kambing": "goat",
    "kelinci": "rabbit",
    "ular": "snake",
    "kupu-kupu": "butterfly",
    "lebah": "bee",
    "penyu": "turtle",
    "gajah": "elephant",
    "singa": "lion",
    "jerapah": "giraffe",
    "kanguru": "kangaroo",
    "monyet": "monkey",
    "serigala": "wolf",
    "tikus": "mouse",
    "katak": "frog",
    "ikan hiu": "shark",
    "kumbang": "beetle",
    "nyamuk": "mosquito",
    "lumba-lumba": "dolphin",
    "kura-kura": "turtle",
    "kadal": "lizard",
    "kelelawar": "bat",
    "merak": "peacock",
    "unta": "camel",
    "anjelir": "carnation",
    "anggrek": "orchid",
    "kaktus": "cactus",
    "ikan paus": "whale",
    "elang": "eagle",
    "angsa": "swan",
    "babi": "pig",
    "capung": "dragonfly",
    "kupu-kupu": "butterfly",
    "lalat": "fly",
    "kecoa": "cockroach",
    "nyala api": "flame",
    "petir": "lightning",
    "bulu": "feather",
    "sapi betina": "cow",
    "bebek": "duck",
    "buaya": "crocodile",
    "semut": "ant",
    "kelinci": "rabbit",
    "koala": "koala",
    "lele": "catfish",
    "macan tutul": "leopard",
    "merpati": "pigeon",
    "musang": "civet",
    "ular kobra": "cobra",
    "panda": "panda",
    "rajawali": "hawk",
    "merpati": "dove",
    "tupai": "squirrel",
    "beruang": "bear",
    "kodok": "toad",
    "capung": "damselfly",
    "katak": "toad",
    "kepiting": "crab",
    "kepala": "head",
    "kaki": "leg",
    "tangan": "hand",
    "mata": "eye",
    "hidung": "nose",
    "mulut": "mouth",
    "telinga": "ear",
    "dagu": "chin",
    "rambut": "hair",
    "jari": "finger",
    "kuku": "nail",
    "lutut": "knee",
    "perut": "stomach",
    "dada": "chest",
    "punggung": "back",
    "tulang": "bone",
    "darah": "blood",
    "jantung": "heart",
    "paru-paru": "lung",
    "hati": "liver",
    "ginjal": "kidney",
    "otak": "brain",
    "kulit": "skin",
    "otot": "muscle",
    "sendi": "joint",
    "tulang belakang": "spine",
    "pipi": "cheek",
    "lidah": "tongue",
    "leher": "neck",
    "telinga": "ear",
    "leher": "neck",
    "lidah": "tongue",
    "siku": "elbow",
    "pergelangan tangan": "wrist",
    "bahu": "shoulder",
    "pergelangan kaki": "ankle",
    "tumit": "heel",
    "siku": "elbow",
    "leher": "neck",
    "telinga": "ear",
    "dunia": "world",
    "bulan sabit": "crescent moon",
    "permen": "candy",
    "permen karet": "chewing gum",
    "kapal": "ship",
    "kapal selam": "submarine",
    "helikopter": "helicopter",
    "pesawat terbang": "airplane",
    "perahu": "boat",
    "sepeda": "bicycle",
    "kereta api": "train",
    "mobil listrik": "electric car",
    "stasiun kereta": "train station",
    "terminal bus": "bus terminal",
    "taksi": "taxi",
    "sepeda motor": "motorcycle",
    "jalan": "road",
    "jembatan": "bridge",
    "taman": "park",
    "taman bermain": "playground",
    "taman hiburan": "amusement park",
    "kolam renang": "swimming pool",
    "danau": "lake",
    "gunung berapi": "volcano",
    "pulau": "island",
    "gurun": "desert",
    "hutan": "forest",
    "sungai": "river",
    "air terjun": "waterfall",
    "pantai": "beach",
    "lautan": "ocean",
    "samudra": "sea",
    "peta": "map",
    "kompas": "compass",
    "televisi kabel": "cable television",
    "film": "movie",
    "teater": "theater",
    "museum": "museum",
    "pameran seni": "art exhibition",
    "zoo": "zoo",
    "gudang": "warehouse",
    "kantor": "office",
    "pabrik": "factory",
    "restoran": "restaurant",
    "kafetaria": "cafeteria",
    "pasar": "market",
    "pulpen": "pen",
    "pensil": "pencil",
    "kertas": "paper",
    "pensil warna": "colored pencil",
    "penggaris": "ruler",
    "penghapus": "eraser",
    "buku catatan": "notebook",
    "kalkulator": "calculator",
    "kompor": "stove",
    "kulkas": "refrigerator",
    "kompor gas": "gas stove",
    "piring makan": "dinner plate",
    "piring saji": "serving plate",
    "gelas air": "drinking glass",
    "piring mangkok": "bowl",
    "piring kue": "cake plate",
    "garasi": "garage",
    "halaman belakang": "backyard",
    "halaman depan": "front yard",
    "tangga": "stairs",
    "lantai": "floor",
    "dinding": "wall",
    "atap": "roof",
    "jendela": "window",
    "pintu": "door",
    "kunci pintu": "door lock",
    "tirai": "curtain",
    "lampu lantai": "floor lamp",
    "lukisan": "painting",
    "patung": "sculpture",
    "cetakan": "print",
    "konser": "concert",
    "pembicara": "speaker",
    "kursi lipat": "folding chair",
    "sandal": "sandals",
    "topi": "hat",
    "jaket": "jacket",
    "sepatu": "shoes",
    "tas": "bag",
    "jam tangan": "wristwatch",
    "kalung": "necklace",
    "gelang": "bracelet",
    "cincin": "ring",
    "kaos kaki": "socks",
    "koper": "suitcase",
    "payung": "umbrella",
    "sepeda motor": "motorbike",
    "sepeda listrik": "electric bike",
    "kereta gantung": "cable car",
    "roda gigi": "gear",
    "helm": "helmet",
    "kacamata": "glasses",
    "kamera digital": "digital camera",
    "pemutar musik": "music player",
    "laptop": "laptop",
    "tablet": "tablet",
    "penyimpanan awan": "cloud storage",
    "mouse komputer": "computer mouse",
    "keyboard": "keyboard",
    "speaker Bluetooth": "Bluetooth speaker",
    "pemutar DVD": "DVD player",
    "televisi pintar": "smart TV",
    "remote TV": "TV remote",
    "kotak suara": "loudspeaker",
    "printer": "printer",
    "scanner": "scanner",
    "flash drive": "flash drive",
    "mouse pad": "mouse pad",
    "pelindung layar": "screen protector",
    "penyedot debu": "dust collector",
    "pemutar video": "video player",
    "pemutar CD": "CD player",
    "sabun mandi": "soap",
    "sampo": "shampoo",
    "sikat gigi": "toothbrush",
    "pasta gigi": "toothpaste",
    "handuk": "towel",
    "sprei": "bedsheet",
    "bantal": "pillow",
    "selimut": "blanket",
    "gantungan baju": "hanger",
    "mesin cuci": "washing machine",
    "kursi malas": "armchair",
    "sofa": "sofa",
    "sabuk": "belt",
    "topi petualang": "adventurer hat",
    "kompor listrik": "electric stove",
    "panci": "pan",
    "sikat rambut": "hairbrush",
    "sikat cat": "paintbrush",
    "lemari pakaian": "wardrobe",
    "kasur": "mattress",
    "komputer tablet": "tablet computer",
    "kacamata hitam": "sunglasses",
    "kalkulator saku": "pocket calculator",
    "kotak pensil": "pencil case",
    "tas laptop": "laptop bag",
    "papan tulis": "whiteboard",
    "pensil mekanik": "mechanical pencil",
    "kertas lipat": "origami paper",
    "kain lap": "cloth rag",
    "alat potong": "cutting tool",
    "tang": "pliers",
    "palu": "hammer",
    "meteran": "tape measure",
    "baut": "screw",
    "sekrup": "nut",
    "pisau lipat": "pocket knife",
    "pemutar kaset": "cassette player",
    "radio": "radio",
    "mangkok sup": "soup bowl",
    "piring tatah": "charger plate",
    "botol air": "water bottle",
    "tisu": "tissue",
    "pembersih kaca": "glass cleaner",
    "lap kaca": "glass cloth",
    "telepon genggam": "mobile phone",
    "laptop gaming": "gaming laptop",
    "koper kabin": "carry-on luggage",
    "kasur angin": "air mattress",
    "kursi lipat portable": "portable chair",
    "kamera film": "film camera",
        "peniti": "pin",
    "kancing": "button",
    "jarum": "needle",
    "benang": "thread",
    "pemutar video": "video player",
    "pemanggang roti": "toaster",
    "sikat toilet": "toilet brush",
    "ember": "bucket",
    "sikat cuci piring": "dish brush",
    "korek api": "lighter",
    "korek telinga": "cotton swab",
    "kacamata renang": "swimming goggles",
    "topi renang": "swim cap",
    "pelampung": "lifebuoy",
    "baju renang": "swimsuit",
    "papan selancar": "surfboard",
    "kacamata selam": "diving mask",
    "perahu karet": "rubber boat",
    "tali tambang": "rope",
    "gitar": "guitar",
    "biola": "violin",
    "drum": "drums",
    "piano": "piano",
    "flute": "flute",
    "trompet": "trumpet",
    "saksofon": "saxophone",
    "klarinet": "clarinet",
    "bass": "bass guitar",
    "ukulele": "ukulele",
    "harpa": "harp",
    "trombon": "trombone",
    "biola": "cello",
    "senar gitar": "guitar string",
    "senapan angin": "air rifle",
    "busur panah": "bow and arrow",
    "sepeda gunung": "mountain bike",
    "sepeda BMX": "BMX bike",
    "sepeda lipat": "folding bike",
    "sepeda tandem": "tandem bike",
    "kuda poni": "pony",
    "kuda arab": "Arabian horse",
    "kuda jantan": "stallion",
    "jerami": "straw",
    "tiang listrik": "electric pole",
    "gudang penyimpanan": "storage warehouse",
    "pembibitan": "nursery",
    "pintu geser": "sliding door",
    "pemadam kebakaran": "fire extinguisher",
    "tabung gas": "gas cylinder",
    "layang-layang": "kite",
    "turbin angin": "wind turbine",
    "sumur": "well",
    "kincir air": "water wheel",
    "kolam ikan": "fish pond",
    "lapangan tenis": "tennis court",
    "lapangan golf": "golf course",
    "ring basket": "basketball hoop",
    "lapangan sepak bola": "soccer field",
    "gawang sepak bola": "soccer goal",
    "peluit": "whistle",
    "peta dunia": "world map",
    "pelampung udara": "hot air balloon",
    "sepeda motor trail": "trail bike",
    "helm trail": "off-road helmet",
    "kompor minyak": "oil stove",
    "tumpukan buku": "book stack",
    "meja rias": "dressing table",
    "cermin": "mirror",
    "kuas makeup": "makeup brush",
    "parfum": "perfume",
    "topi pesta": "party hat",
    "lilin ulang tahun": "birthday candle",
    "kertas kado": "gift wrapping paper",
    "boneka beruang": "teddy bear",
    "kursi goyang": "rocking chair",
    "piring kertas": "paper plate",
    "sendok plastik": "plastic spoon",
    "garpu plastik": "plastic fork",
    "pisau plastik": "plastic knife",
    "tong sampah": "trash bin",
    "deterjen": "detergent",
    "sapu tangan": "handkerchief",
    "payung pantai": "beach umbrella",
    "sepak bola pantai": "beach soccer ball",
    "pasir pantai": "beach sand",
    "pelampung renang": "swimming float",
    "kacamata surya": "sunglasses",
    "topi pantai": "beach hat",
    "handuk pantai": "beach towel",
    "gundukan pasir": "sandcastle",
    "kamera underwater": "underwater camera",
    "gelang karet": "rubber band",
    "pencil case": "tempat pensil",
    "tali rafia": "raffia string",
    "jurnal": "journal",
    "kartu pos": "postcard",
    "peta kota": "city map",
    "bendera": "flag",
    "kantong plastik": "plastic bag",
    "klip kertas": "paper clip",
    "kunci inggris": "wrench",
    "obeng": "screwdriver",
    "cat tembok": "wall paint",
    "gembok": "padlock",
    "sikat gigi elektrik": "electric toothbrush",
    "rautan pensil": "pencil sharpener",
    "baki cuci piring": "dish rack",
    "botol ketchup": "ketchup bottle",
    "tutup botol": "bottle cap",
    "ember air": "water bucket",
    "sendok sup": "soup spoon",
    "garpu kue": "cake fork",
    "piring plastik": "plastic plate",
    "piring porselen": "porcelain plate",
    "sendok garpu set": "cutlery set",
    "kompor gas portable": "portable gas stove",
    "oven": "oven",
    "kulkas mini": "mini fridge",
    "kipas angin": "fan",
    "ac portable": "portable air conditioner",
    "kursi lipat camping": "camping chair",
    "tenda": "tent",
    "sleeping bag": "sleeping bag",
    "pisau lipat camping": "camping knife",
    "kompor camping": "camping stove",
    "sendok kayu": "wooden spoon",
    "piring kayu": "wooden plate",
    "gitar akustik": "acoustic guitar",
    "harmonika": "harmonica",
    "trikoda": "tricycle",
    "sepeda listrik": "electric bicycle",
    "sepeda gantung": "hanging bicycle",
    "truk": "truck",
    "helikopter militer": "military helicopter",
    "kapal pesiar": "cruise ship",
    "kayak": "kayak",
    "paddleboard": "paddleboard",
    "perahu nelayan": "fishing boat",
    "submarine": "kapal selam",
    "jet ski": "jet ski",
    "perahu layar": "sailboat",
    "speedboat": "speedboat",
    "amfibi": "amphibian",
    "kompor camping": "camping stove",
    "tabung gas camping": "camping gas cylinder",
    "kantong tidur camping": "camping sleeping bag",
    "lampu camping": "camping lantern",
    "tenda camping": "camping tent",
    "kipas angin baterai": "battery-powered fan",
    "panci camping": "camping pot",
    "sendok lipat": "folding spoon",
    "garpu lipat": "folding fork",
    "pisau lipat": "folding knife",
    "seruling": "flute",
    "marakas": "maracas",
    "trompet": "trumpet",
    "gong": "gong",
    "biola": "violin",
    "seruling panjang": "pan flute",
    "trombon": "trombone",
    "piano elektrik": "electric piano",
    "djembe": "djembe",
    "tamborin": "tambourine",
    "kacamata virtual reality": "virtual reality glasses",
    "drone": "drone",
    "power bank": "power bank",
    "pemutar Blu-ray": "Blu-ray player",
    "earphone nirkabel": "wireless earphones",
    "kamera CCTV": "CCTV camera",
    "alarm pintu": "door alarm",
    "penyemprot air": "water spray",
    "lilin aromaterapi": "aromatherapy candle",
    "kacamata hitam polaroid": "polarized sunglasses",
    "gantungan kunci": "keychain",
    "petir buatan": "artificial lightning",
    "teleskop": "telescope",
    "metronome": "metronome",
    "plaster": "band-aid",
    "termos": "thermos",
    "tali tambang": "rope",
    "tangga lipat": "folding ladder",
    "jemuran": "clothesline",
    "kawat baju": "clothes hanger",
    "senter": "flashlight",
    "lampu camping": "camping lamp",
    "lampu sorot": "spotlight",
    "tirai shower": "shower curtain",
    "karpet": "rug",
    "kursi pantai": "beach chair",
    "tirai jendela": "window curtain",
    "meja makan lipat": "folding dining table",
    "kursi makan lipat": "folding dining chair",
    "payung taman": "garden umbrella",
    "alat pancing": "fishing gear",
    "kotak alat": "toolbox",
    "lemari pakaian kayu": "wooden wardrobe",
    "meja kerja": "work desk",
    "lampu meja": "table lamp",
    "meja makan": "dining table",
    "kursi tamu": "living room chair",
    "sofa tidur": "sofa bed",
    "pohon Natal": "Christmas tree",
    "kantong tidur": "sleeping bag",
    "karpet camping": "camping mat",
    "kursi lipat stadion": "stadium seat",
    "kipas angin gantung": "ceiling fan",
    "lemari es": "refrigerator",
    "mesin cuci piring": "dishwasher",
    "blender": "blender",
    "mesin kopi": "coffee machine",
    "toster": "toaster",
    "coffeemaker": "pembuat kopi",
    "kulkas es krim": "ice cream freezer",
    "penggorengan": "frying pan",
    "panci tekanan": "pressure cooker",
    "slow cooker": "slow cooker",
    "penggiling daging": "meat grinder",
    "penanak nasi": "rice cooker",
    "blender listrik": "electric blender",
    "juicer": "juicer",
    "teko air listrik": "electric kettle",
    "pencuci piring": "dishwasher",
    "pemanggang roti": "toaster",
    "kuali": "pot",
    "kantong kopi": "coffee bag",
    "kopi bubuk": "ground coffee",
    "air soda": "soda",
    "jus buah": "fruit juice",
    "minuman energi": "energy drink",
    "minuman ringan": "soft drink",
    "susu": "milk",
    "air mineral": "mineral water",
    "madu": "honey",
    "sirup maple": "maple syrup",
    "saus tomat": "ketchup",
    "mayones": "mayonnaise",
    "saus sambal": "hot sauce",
    "sambal": "chili sauce",
    "saus barbecue": "barbecue sauce",
    "bumbu masak": "spice",
    "garam": "salt",
    "gula": "sugar",
    "merica": "pepper",
    "kecap": "soy sauce",
    "susu kental manis": "condensed milk",
    "mentega": "butter",
    "minyak sayur": "vegetable oil",
    "minyak zaitun": "olive oil",
    "sereal": "cereal",
    "biskuit": "biscuit",
    "roti bakar": "toast",
    "donat": "doughnut",
    "kue": "cake",
    "es krim": "ice cream",
    "kue tart": "birthday cake",
    "kue kering": "cookies",
    "buah-buahan": "fruits",
    "sayuran": "vegetables",
    "daging sapi": "beef",
    "daging ayam": "chicken meat",
    "daging babi": "pork",
    "ikan salmon": "salmon",
    "udang": "shrimp",
    "sapi panggang": "roast beef",
    "nasi goreng": "fried rice",
    "mie goreng": "fried noodles",
    "ayam goreng": "fried chicken",
    "bakso": "meatball",
    
    

 
"sate": "satay",
    "rendang": "rendang",
    
   
"gado-gado": "gado-gado",
    
   
"nasi goreng": "fried rice",
    
   
"mie goreng": "fried noodles",
    "nasi padang": "Padang rice",
    
   
"soto": "soto",
    "martabak": "martabak",
    
   
"kue lapis": "layer cake",
    "ketoprak": "ketoprak",
    "kue basah": "traditional cakes",
    "es teh": "iced tea",
    
   
"es jeruk": "orange ice",
    "es kelapa muda": "young coconut ice",
    
   
"es krim": "ice cream",
    "es campur": "mixed ice",
    
   
"nasi uduk": "steamed rice",
    
   
"nasi kuning": "yellow rice",
    
   
"bubur ayam": "chicken porridge",
    "bubur ketan hitam": "black glutinous rice porridge",
    "rujak": "rujak",
    "kolak": "kolak",
    
   
"rujak cingur": "cingur salad",
    
   
"tahu goreng": "fried tofu",
    
   
"tempe goreng": "fried tempeh",
    "gado-gado": "gado-gado",
    
  
"sambal": "chili sauce",
    
  
"krupuk": "crackers",
    
   
"rendang": "rendang",
    
   

 
"nasi tumpeng": "tumpeng rice",
    
  
"kupat tahu": "kupat tahu",
    
   
"lontong sayur": "lontong sayur",
    "seblak": "seblak",
    "ketupat": "ketupat",
    
   
"siomay": "siomay",
    "lemper": "lemper",
    "cendol": "cendol",
    "es doger": "doger ice",
    "es puter": "puter ice",
    "klappertaart": "klappertaart",
    
   
"bandeng presto": "pressure-cooked milkfish",
    "papeda": "papeda",
    
   
"coto Makassar": "coto Makassar",
    "pempek": "pempek",
    "empek-empek": "empek-empek",
    "ketoprak": "ketoprak",
    
   
"otak-otak": "otak-otak",
    
   
"pisang goreng": "fried banana",
    
   
"sambal terasi": "shrimp paste chili sauce",
    
   
"ikan bakar": "grilled fish",
    
   
"ikan goreng": "fried fish",
    
   
"ikan pepes": "pepes fish",
    
   
"ikan panggang": "baked fish",
    
   
"ikan asam pedas": "sour and spicy fish",
    
   
"ikan acar kuning": "pickled yellow fish",
    "tahu isi": "filled tofu",
    "pisang kepok": "banana kepok",
    
   
"sop buntut": "oxtail soup",
    "sop iga": "ribs soup",
    
   
"rawon": "rawon",
    
   
"gado-gado": "gado-gado",
    
   
"rujak buah": "fruit salad",
    
   
"sambal matah": "raw shallot chili sauce",
    
   
"nasi goreng kambing": "fried goat meat rice",
    "ikan bakar Jimbaran": "Jimbaran grilled fish",
    
   
"sate lilit": "wrapped satay",
    "babi guling": "suckling pig",
    "sego sambel": "rice with chili sauce",
    
   
"serabi": "serabi",
    "sop kambing": "goat soup",
    "sop ikan Batam": "Batam fish soup",
    
   
"mie aceh": "Aceh noodles",
    
   
"rendang padang": "Padang rendang",
    
   
"nasi liwet": "liwet rice",
    
   
"kue cubit": "pinch cake",
    
   
"martabak telor": "egg martabak",
    "sup asparagus": "asparagus soup",
    
   
"soto betawi": "Betawi soto",
    
   
"nasi gudeg": "gudeg rice",
    "bubur kacang hijau": "green bean porridge",
    "kue putu": "putu cake",
    
   
"nasi jagung": "corn rice",
    "kolak ubi": "sweet potato kolak",
    "kue onde-onde": "onde-onde cake",
    
   
"tahu sumedang": "sumedang tofu",
    "sop buah": "fruit soup",
    "ketan durian": "durian glutinous rice",
    
   
"nasi tempong": "tempong rice",
    "kue mangkok": "cup cake",
    "sate maranggi": "maranggi satay",
    
   
"seblak Bandung": "Bandung seblak",
    "soto tangkar": "tangkar soto",
    "lumpia Semarang": "Semarang spring rolls",
    
  
"bika Ambon": "Ambon bika",
    
  
"klanting": "klanting",
    
   
"sate kikil": "kikil satay",
    "bakwan malang": "Malang bakwan",
    
   
"nasi ulam": "herb rice",
    
   
"klepon": "klepon",
    
   
"kue apem": "apem cake",
    "serabi notosuman": "notosuman serabi",
    
   
"kue lumpur": "mud cake",
    
   
"gemblong": "gemblong",
    "es cendol": "cendol ice",
    
   
"kue pancong": "pancong cake",
    "kupat tahu Magelang": "Magelang kupat tahu",
    "roti ganjel rel": "bread sandwich",
    "pempek kapal selam": "submarine pempek",
    "pempek lenjer": "lenjer pempek",
    
   
"pempek pistel": "pistel pempek",
    "pempek adaan": "adaan pempek",
    "pempek kulit": "skin pempek",
    
   
"pempek dos": "dos pempek",
    
   
"sambal goreng ati": "fried liver chili sauce",
    
    
"sayur asem": "sour vegetable soup",
    
   
"buntil": "buntil",
    
   
"cilok": "cilok",
    "gado-gado Betawi": "Betawi gado-gado",
    
   
"selat segara": "sea selat",
    "es kacang ijo": "mung bean ice",
    "lontong mie": "noodle",
    "rumah": "house",
    
  
"mobil": "car",
    
   
"pohon": "tree",
    "kucing": "cat",
    
    
"anjing": "dog",
    
 
"makanan": "food",
    "air": "water",
    
   
"buku": "book",
    
   
"sekolah": "school",
    
   
"komputer": "computer",
    "harimau": "tiger",
    "burung": "bird",
    "kopi": "coffee",
    "meja": "table",
    
    
"kursi": "chair",
    "jendela": "window",
    "pintu": "door",
    "televisi": "television",
    "telepon": "phone",
    "roti": "bread",
    "kamera": "camera",
    "jam": "clock",
    "lampu": "lamp",
    "pakaian": "clothes",
    "kunci": "key",
    "sendok": "spoon",
    "garpu": "fork",
    "pisau": "knife",
    
 
"gelas": "glass",
    "piring": "plate",
    "matahari": "sun",
    "bulan": "moon",
    "bintang": "star",
    
 
"gunung": "mountain",
    "laut": "sea",
    "langit": "sky",
    "tanah": "earth",
    "angin": "wind",
    "api": "fire",
    "salju": "snow",
    "hujan": "rain",
    "awan": "cloud",
    "rumput": "grass",
    "bunga": "flower",
    "buah": "fruit",
    
 
"sayuran": "vegetable",
    "ikan": "fish",
    "udang": "shrimp",
    "ayam": "chicken",
    "sapi": "cow",
    "kuda": "horse",
    "kambing": "goat",
    "kelinci": "rabbit",
    "ular": "snake",
    "kupu-kupu": "butterfly",
    "lebah": "bee",
    "penyu": "turtle",
    "gajah": "elephant",
    "singa": "lion",
    "jerapah": "giraffe",
    "kanguru": "kangaroo",
    "monyet": "monkey",
    "serigala": "wolf",
    "tikus": "mouse",
    "katak": "frog",
    "ikan hiu": "shark",
    "kumbang": "beetle",
    "nyamuk": "mosquito",
    "lumba-lumba": "dolphin",
    "kura-kura": "turtle",
    "kadal": "lizard",
    "kelelawar": "bat",
    "merak": "peacock",
    "unta": "camel",
    "anjelir": "carnation",
    "anggrek": "orchid",
    "kaktus": "cactus",
    "ikan paus": "whale",
    "elang": "eagle",
    "angsa": "swan",
    "babi": "pig",
    "capung": "dragonfly",
    "kupu-kupu": "butterfly",
    "lalat": "fly",
    "kecoa": "cockroach",
    "nyala api": "flame",
    "petir": "lightning",
    "bulu": "feather",
    "sapi betina": "cow",
    "bebek": "duck",
    "buaya": "crocodile",
    "semut": "ant",
    "kelinci": "rabbit",
    "koala": "koala",
    "lele": "catfish",
    "macan tutul": "leopard",
    "merpati": "pigeon",
    "musang": "civet",
    "ular kobra": "cobra",
    
 
"panda": "panda",
    "rajawali": "hawk",
    "merpati": "dove",
    
    
"tupai": "squirrel",
    "beruang": "bear",
    "kodok": "toad",
    "capung": "damselfly",
    "katak": "toad",
    
 
"kepiting": "crab",
    "kepala": "head",
    "kaki": "leg",
    
   
"tangan": "hand",
    
  
"mata": "eye",
    
 
"hidung": "nose",
    "mulut": "mouth",
    
   
"telinga": "ear",
    "dagu": "chin",
    
   
"rambut": "hair",
    "jari": "finger",
    "kuku": "nail",
    "lutut": "knee",
    "perut": "stomach",
    
 
"dada": "chest",
    
    
"punggung": "back",
    
    
"tulang": "bone",
    "darah": "blood",
    "jantung": "heart",
    "paru-paru": "lung",
    
   
"hati": "liver",
    
    
"ginjal": "kidney",
    
  
"otak": "brain",
    
  
"kulit": "skin",
    
  
"otot": "muscle",
    
    
"sendi": "joint",
    
 
"tulang belakang": "spine",
    
   
"pipi": "cheek",
    
  
"lidah": "tongue",
    
    
"leher": "neck",
    "telinga": "ear",
    
   
"leher": "neck",
    "lidah": "tongue",
    
   
"siku": "elbow",
    
   
"pergelangan tangan": "wrist",
    "bahu": "shoulder",
    
   
"pergelangan kaki": "ankle",
    "tumit": "heel",
    
   
"siku": "elbow",
    
   
"leher": "neck",
    "telinga": "ear",
    "dunia": "world",
    
   
"bulan sabit": "crescent moon",
    "permen": "candy",
    "permen karet": "chewing gum",
    
    
"kapal": "ship",
    
   
"kapal selam": "submarine",
    
   
"helikopter": "helicopter",
    
    

 
"pesawat terbang": "airplane",
    
   
"perahu": "boat",
    
    
"sepeda": "bicycle",
    
    
"kereta api": "train",
    "mobil listrik": "electric car",
    
    

 
"stasiun kereta": "train station",
    
 
"terminal bus": "bus terminal",
    
   
"taksi": "taxi",
    
  
"sepeda motor": "motorcycle",
    "jalan": "road",
    "jembatan": "bridge",
    "trotoar": "sidewalk",
    "lampu lalu lintas": "traffic light",
    "tanda stop": "stop sign",
    "bus stop": "bus stop",
    
   
"pompa bensin": "gas station",
    "toko": "shop",
    "mall": "mall",
    
   
"pasar": "market",
    
   
"restoran": "restaurant",
    "kantor pos": "post office",
    "hotel": "hotel",
    
   
"bank": "bank",
    
   
"rumah sakit": "hospital",
    "sekolah": "school",
    
   
"universitas": "university",
    
   
"masjid": "mosque",
    "gereja": "church",
    "temple": "temple",
    
   
"pabrik": "factory",
    "kantor": "office",
    "gedung apartemen": "apartment building",
    
   
"stasiun radio": "radio station",
    "kantor berita": "newsroom",
    "studio televisi": "TV studio",
    "bioskop": "cinema",
    "taman": "park",
    "taman bermain": "playground",
    "kolam renang": "swimming pool",
    "lapangan tenis": "tennis court",
    "gym": "gym",
    "lapangan sepak bola": "soccer field",
    "bandara": "airport",
    "kandang": "barn",
    "sawah": "rice field",
    "gunung": "mountain",
    "pantai": "beach",
    "gurun": "desert",
    "hutan": "forest",
    "danau": "lake",
    "sungai": "river",
    "air terjun": "waterfall",
    "pulau": "island",
    "bukit": "hill",
    
   
"lumpur": "mud",
    
   
"batu": "rock",
    
   
"pasir": "sand",
    
   
"hujan salju": "snowfall",
    
   
"badai": "storm",
    "pelangi": "rainbow",
    "awan": "cloud",
    "petir": "lightning",
    "guntur": "thunder",
    "pelangi": "rainbow",
    
   
"berawan": "cloudy",
    "hujan ringan": "drizzle",
    
   
"hujan deras": "heavy rain",
    "badai salju": "snowstorm",
    "angin kencang": "strong wind",
    "gelombang laut": "sea waves",
    "gunung berapi": "volcano",
    "tanah longsor": "landslide",
    "gempa bumi": "earthquake",
    
   
"tsunami": "tsunami",
    
   
"tornado": "tornado",
    "puting beliung": "waterspout",
    
   
"cuaca": "weather",
    "musim semi": "spring",
    
   
"musim panas": "summer",
    
   
"musim gugur": "autumn",
    "musim dingin": "winter",
    "siang hari": "daytime",
    
   
"malam hari": "nighttime",
    "fajar": "dawn",
    "senja": "dusk",
    "terbit": "sunrise",
    "terbenam": "sunset",
    "bulan purnama": "full moon",
    "bulan sabit": "crescent moon",
    
   
"bulan": "moon",
    
   
"bintang": "star",
    "planet": "planet",
    "galaksi": "galaxy",
    
   
"tata surya": "solar system",
    
   
"lubang hitam": "black hole",
    "angkasa luar": "outer space",
    "astronot": "astronaut",
    "roket": "rocket",
    
   
"satelit": "satellite",
    
   
"teleskop": "telescope",
    
   
"meteor": "meteor",
    
   
"kometa": "comet",
    
   
"pesawat luar angkasa": "spaceship",
    "hari": "day",
    "minggu": "week",
    
   
"bulan": "month",
    "tahun": "year",
    "jam": "hour",
    
   
"menit": "minute",
    
   
"detik": "second",
    "pagi": "morning",
    "siang": "afternoon",
    "sore": "evening",
    "malam": "night",
    
   
"minggu depan": "next week",
    
   
"bulan depan": "next month",
    "tahun depan": "next year",
    "minggu lalu": "last week",
    
   
"bulan lalu": "last month",
    "tahun lalu": "last year",
    "kemarin": "yesterday",
    
   
"hari ini": "today",
    
   
"besok": "tomorrow",
    
   
"sekarang": "now",
    "kemudian": "later",
    "baru saja": "just now",
    
   
"cepat": "fast",
    "lambat": "slow",
    
   
"besar": "big",
    
   
"kecil": "small",
    "tinggi": "tall",
    "pendek": "short",
    
   
"tebal": "thick",
    "tipis": "thin",
    "berat": "heavy",
    
   
"ringan": "light",
    "panjang": "long",
    "pendek": "short",
    "lebar": "wide",
    
   
"sempit": "narrow",
    "panas": "hot",
    "dingin": "cold",
    
   
"hangat": "warm",
    "dingin": "cool",
    "kering": "dry",
    "basah": "wet",
    
   
"bersih": "clean",
    
   
"kotor": "dirty",
    
   
"sehat": "healthy",
    "sakit": "sick",
    "baik": "good",
    
   
"buruk": "bad",
    
   
"cantik": "beautiful",
    "jelek": "ugly",
    "ganteng": "handsome",
    "cantik": "pretty",
    "ramah": "friendly",
    "jahat": "mean",
    "bahagia": "happy",
    
   
"sedih": "sad",
    "marah": "angry",
    "ketawa": "laugh",
    
   
"menangis": "cry",
    "tidur": "sleep",
    "bangun": "wake up",
    
   
"makan": "eat",
    
   
"minum": "drink",
    
   
"jalan": "walk",
    "lari": "run",
    
   
"berenang": "swim",
    
   
"terbang": "fly",
    "duduk": "sit",
    
   
"berdiri": "stand",
    "jongkok": "squat",
    "melompat": "jump",
    "bermain": "play",
    "bekerja": "work",
    "kopi": "coffee",
    "meja": "table",
    "kursi": "chair",
    "jendela": "window",
    "pintu": "door",
    "televisi": "television",
    "telepon": "phone",
    "roti": "bread",
    "kamera": "camera",
    "jam": "clock",
    "lampu": "lamp",
    "pakaian": "clothes",
    "kunci": "key",
    "sendok": "spoon",
    "garpu": "fork",
    "pisau": "knife",
    "gelas": "glass",
    "piring": "plate",
    "matahari": "sun",
    "bulan": "moon",
    "bintang": "star",
    "gunung": "mountain",
    "laut": "sea",
    "langit": "sky",
    "tanah": "earth",
    "angin": "wind",
    "api": "fire",
    "salju": "snow",
    "hujan": "rain",
    "awan": "cloud",
    "rumput": "grass",
    "bunga": "flower",
    "buah": "fruit",
    "sayuran": "vegetable",
    "ikan": "fish",
    "udang": "shrimp",
    "ayam": "chicken",
    "sapi": "cow",
    "kuda": "horse",
    "kambing": "goat",
    "kelinci": "rabbit",
    "ular": "snake",
    "kupu-kupu": "butterfly",
    "lebah": "bee",
    "penyu": "turtle",
    "gajah": "elephant",
    "singa": "lion",
    "jerapah": "giraffe",
    "kanguru": "kangaroo",
    "monyet": "monkey",
    "serigala": "wolf",
    "tikus": "mouse",
    "katak": "frog",
    "ikan hiu": "shark",
    "kumbang": "beetle",
    "nyamuk": "mosquito",
    "lumba-lumba": "dolphin",
    "kura-kura": "turtle",
    "kadal": "lizard",
    "kelelawar": "bat",
    "merak": "peacock",
    "unta": "camel",
    "anjelir": "carnation",
    "anggrek": "orchid",
    "kaktus": "cactus",
    "ikan paus": "whale",
    "elang": "eagle",
    "angsa": "swan",
    "babi": "pig",
    "capung": "dragonfly",
    "kupu-kupu": "butterfly",
    "lalat": "fly",
    "kecoa": "cockroach",
    "nyala api": "flame",
    "petir": "lightning",
    "bulu": "feather",
    "sapi betina": "cow",
    "bebek": "duck",
    "buaya": "crocodile",
    "semut": "ant",
    "kelinci": "rabbit",
    "koala": "koala",
    "lele": "catfish",
    "macan tutul": "leopard",
    "merpati": "pigeon",
    "musang": "civet",
    "ular kobra": "cobra",
    "panda": "panda",
    "rajawali": "hawk",
    "merpati": "dove",
    "tupai": "squirrel",
    "beruang": "bear",
    "kodok": "toad",
    "capung": "damselfly",
    "katak": "toad",
    "kepiting": "crab",
    "kepala": "head",
    "kaki": "leg",
    "tangan": "hand",
    "mata": "eye",
    "hidung": "nose",
    "mulut": "mouth",
    "telinga": "ear",
    "dagu": "chin",
    "rambut": "hair",
    "jari": "finger",
    "kuku": "nail",
    "lutut": "knee",
    "perut": "stomach",
    "dada": "chest",
    "punggung": "back",
    "tulang": "bone",
    "darah": "blood",
    "jantung": "heart",
    "paru-paru": "lung",
    "hati": "liver",
    "ginjal": "kidney",
    "otak": "brain",
    "kulit": "skin",
    "otot": "muscle",
    "sendi": "joint",
    "tulang belakang": "spine",
    "pipi": "cheek",
    "lidah": "tongue",
    "leher": "neck",
    "telinga": "ear",
    "leher": "neck",
    "lidah": "tongue",
    "siku": "elbow",
    "pergelangan tangan": "wrist",
    "bahu": "shoulder",
    "pergelangan kaki": "ankle",
    "tumit": "heel",
    "siku": "elbow",
    "leher": "neck",
    "telinga": "ear",
    "dunia": "world",
    "bulan sabit": "crescent moon",
    "permen": "candy",
    "permen karet": "chewing gum",
    "kapal": "ship",
    "kapal selam": "submarine",
    "helikopter": "helicopter",
    "pesawat terbang": "airplane",
    "perahu": "boat",
    "sepeda": "bicycle",
    "kereta api": "train",
    "mobil listrik": "electric car",
    "stasiun kereta": "train station",
    "terminal bus": "bus terminal",
    "taksi": "taxi",
    "sepeda motor": "motorcycle",
    "jalan": "road",
    "jembatan": "bridge",
    "taman": "park",
    "taman bermain": "playground",
    "taman hiburan": "amusement park",
    "kolam renang": "swimming pool",
    "danau": "lake",
    "gunung berapi": "volcano",
    "pulau": "island",
    "gurun": "desert",
    "hutan": "forest",
    "sungai": "river",
    "air terjun": "waterfall",
    "pantai": "beach",
    "lautan": "ocean",
    "samudra": "sea",
    "selat": "strait",
    "teluk": "bay",
    "rawa": "swamp",
    "pegunungan": "mountain range",
    "bukit": "hill",
    "lembah": "valley",
    "padang rumput": "meadow",
    "dataran tinggi": "highland",
    "padang pasir": "sand dune",
    "pelangi": "rainbow",
    "awan": "cloud",
    "pelangi": "rainbow",
    "badai": "storm",
    "petir": "lightning",
    "hujan es": "hail",
    "peluru": "bullet",
    "senjata": "weapon",
    "pedang": "sword",
    "perisai": "shield",
    "tombak": "spear",
    "panah": "arrow",
    "pistol": "pistol",
    "meriam": "cannon",
    "tank": "tank",
    "helikopter tempur": "attack helicopter",
    "kapal perang": "warship",
    "pesawat tempur": "fighter jet",
    "bom": "bomb",
    "granat": "grenade",
    "roket": "rocket",
    "pakaian militer": "military uniform",
    "topi tentara": "army hat",
    "sepatu bot": "combat boots",
    "rompi peluru": "bulletproof vest",
    "bendera": "flag",
    "seragam sekolah": "school uniform",
    "topi": "hat",
    "kacamata": "glasses",
    "dasik": "necktie",
    "syal": "scarf",
    "sarung tangan": "gloves",
    "topi baseball": "baseball cap",
    "topi koboi": "cowboy hat",
    "topi santa": "santa hat",
    "kostum halloween": "halloween costume",
    "jubah": "robe",
    "gaun": "dress",
    "rok": "skirt",
    "kemeja": "shirt",
    "kemeja lengan panjang": "long-sleeved shirt",
    "kaos": "t-shirt",
    "sweater": "sweater",
    "jaket": "jacket",
    "mantel": "coat",
    "celana": "pants",
    "jeans": "jeans",
    "rok": "skirt",
    "celana pendek": "shorts",
    "kaos kaki": "socks",
    "sepatu": "shoes",
    "sepatu bot": "boots",
    "sepatu olahraga": "sneakers",
    "sandal": "sandals",
    "sepatu hak tinggi": "high heels",
    "sepatu kets": "canvas shoes",
    "tas": "bag",
    "tas ransel": "backpack",
    "koper": "suitcase",
    "tas tangan": "handbag",
    "dompet": "wallet",
    "topi": "hat",
    "ikat pinggang": "belt",
    "jam tangan": "watch",
    "anting-anting": "earrings",
    "gelang": "bracelet",
    "kalung": "necklace",
    "cincin": "ring",
    "televisi": "television",
    "remote control": "remote control",
    "kamera": "camera",
    "ponsel": "mobile phone",
    "laptop": "laptop",
    "komputer": "computer",
    "mouse": "mouse",
    "keyboard": "keyboard",
    "monitor": "monitor",
    "printer": "printer",
    "speaker": "speaker",
    "earphone": "earphones",
    "baterai": "battery",
    "charger": "charger",
    "lampu meja": "desk lamp",
    "lampu lantai": "floor lamp",
    "bohlam": "light bulb",
    "lilin": "candle",
    "lampu tidur": "bedside lamp",
    "senter": "flashlight",
    "kulkas": "refrigerator",
    "kompor": "stove",
    "oven": "oven",
    "microwave": "microwave",
    "mesin cuci": "washing machine",
    "pompa air": "water pump",
    "kipas angin": "fan",
    "AC": "air conditioner",
    "pemanas ruangan": "heater",
    "kipas sirip": "fin",
    "pompa bensin": "gas pump",
    "pompa oli": "oil pump",
    "kursi roda": "wheelchair",
    "tongkat": "cane",
    "kruk": "crutch",
    "rambut": "hair",
    "wajah": "face",
    "mata": "eye",
    "hidung": "nose",
    "mulut": "mouth",
    "telinga": "ear",
    "gigi": "tooth",
    "lidah": "tongue",
    "rambut": "hair",
    "kepala": "head",
    "tubuh": "body",
    "tangan": "hand",
    "jari": "finger",
    "kuku": "nail",
    "lengan": "arm",
    "siku": "elbow",
    "bahu": "shoulder",
    "dada": "chest",
    "perut": "stomach",
    "punggung": "back",
    "pinggul": "hip",
    "kaki": "leg",
    "lutut": "knee",
    "betis": "calf",
    "paha": "thigh",
    "kaki": "foot",
    "tumit": "heel",
    "jari kaki": "toe",
    "kuku kaki": "toenail",
    "telinga": "ear",
    "hidung": "nose",
    "mulut": "mouth",
    "bibir": "lip",
    "lidah": "tongue",
    "gusi": "gum",
    "tenggorokan": "throat",
    "amandel": "tonsil",
    "laring": "larynx",
    "trakea": "trachea",
    "paru-paru": "lung",
    "jantung": "heart",
    "hati": "liver",
    "ginjal": "kidney",
    "usus": "intestine",
    "lambung": "stomach",
    "kandung empedu": "gallbladder",
    "kandung kemih": "bladder",
    "tulang": "bone",
    "tulang belakang": "spine",
    "tulang rusuk": "rib",
    "tulang panggul": "pelvic bone",
    "tulang paha": "thigh bone",
    "tulang kering": "shinbone",
    "tulang betis": "calf bone",
    "tulang kaki": "foot bone",
    "tulang lengan": "arm bone",
    "tulang ulna": "ulna",
    "tulang radius": "radius",
    "tulang tangan": "hand bone",
    "tulang jari": "finger bone",
    "tulang tengkorak": "skull bone",
    "otak": "brain",
    "tulang sumsum": "spinal cord",
    "saraf": "nerve",
    "mata": "eye",
    "alis": "eyebrow",
    "kelopak mata": "eyelid",
    "bulu mata": "eyelash",
    "pupil": "pupil",
    "iris": "iris",
    "lensa mata": "lens",
    "kornea": "cornea",
    "retina": "retina",
    "sklera": "sclera",
    "konjungtiva": "conjunctiva",
    "air mata": "tear",
    "telinga": "ear",
    "telinga luar": "outer ear",
    "telinga tengah": "middle ear",
    "telinga dalam": "inner ear",
    "daun telinga": "earlobe",
    "saluran telinga": "ear canal",
    "gendang telinga": "eardrum",
    "tulang pendengaran": "auditory ossicle",
    "koklea": "cochlea",
    "tuba eustachius": "eustachian tube",
    "hidung": "nose",
    "septum hidung": "nasal septum",
    "lubang hidung": "nostril",
    "rongga hidung": "nasal cavity",
    "polip hidung": "nasal polyp",
    "mukosa hidung": "nasal mucosa",
    "gusi": "gum",
    "gigi": "tooth",
    "lubang gigi": "tooth cavity",
    "email gigi": "tooth enamel",
    "pulpa gigi": "tooth pulp",
    "akar gigi": "tooth root",
    "gusi": "gum",
    "lidah": "tongue",
    "papila lidah": "taste bud",
    "lidah tengah": "midline of the tongue",
    "lidah samping": "side of the tongue",
    "lapisan lidah": "tongue coating",
    "rambut lidah": "lingual hair",
    "bibir": "lip",
    "bibir atas": "upper lip",
    "bibir bawah": "lower lip",
    "rongga mulut": "oral cavity",
    "palatum": "palate",
    "gusi": "gum",
    "amandel": "tonsil",
    "tenggorokan": "throat",
    "epiglotis": "epiglottis",
    "langit-langit lunak": "soft palate",
    "langit-langit keras": "hard palate",
    "uvula": "uvula",
    "usus": "intestine",
    "usus kecil": "small intestine",
    "usus besar": "large intestine",
    "anus": "anus",
    "rektum": "rectum",
    "biliaris": "bile duct",
    "hati": "liver",
    "empedu": "bile",
    "kandung empedu": "gallbladder",
    "limpa": "spleen",
    "pankreas": "pancreas",
    "ginjal": "kidney",
    "ureter": "ureter",
    "kandung kemih": "bladder",
    "uretra": "urethra",
    "tulang": "bone",
    "tulang belakang": "spine",
    "tulang rusuk": "rib",
    "tulang panggul": "pelvic bone",
    "tulang paha": "thigh bone",
    "tulang kering": "shinbone",
    "tulang betis": "calf bone",
    "tulang kaki": "foot bone",
    "tulang lengan": "arm bone",
    "tulang ulna": "ulna",
    "tulang radius": "radius",
    "tulang tangan": "hand bone",
    "tulang jari": "finger bone",
    "tulang tengkorak": "skull bone",
    "otot": "muscle",
    "otot lurik": "skeletal muscle",
    "otot polos": "smooth muscle",
    "otot jantung": "cardiac muscle",
    "sendi": "joint",
    "tulang rawan": "cartilage",
    "tulang belulang": "ligament",
    "otot": "muscle",
    "otot lurik": "skeletal muscle",
    "otot polos": "smooth muscle",
    "otot jantung": "cardiac muscle",
    "sendi": "joint",
    "tulang rawan": "cartilage",
    "tulang belulang": "ligament",
    "tendon": "tendon",
    "sumsum tulang": "bone marrow",
    "darah": "blood",
    "pembuluh darah": "blood vessel",
    "arteri": "artery",
    "vena": "vein",
    "kapiler": "capillary",
    "jantung": "heart",
    "peredaran darah": "circulatory system",
    "sel darah merah": "red blood cell",
    "sel darah putih": "white blood cell",
    "trombosit": "platelet",
    "plasma darah": "blood plasma",
    "sistem limfatik": "lymphatic system",
    "kelenjar getah bening": "lymph node",
    "limfa": "lymph",
    "sistem pernapasan": "respiratory system",
    "hidung": "nose",
    "paru-paru": "lung",
    "bronkus": "bronchus",
    "alveolus": "alveolus",
    "diafragma": "diaphragm",
    "sistem pencernaan": "digestive system",
    "mulut": "mouth",
    "esofagus": "esophagus",
    "lambung": "stomach",
    "usus kecil": "small intestine",
    "usus besar": "large intestine",
    "anus": "anus",
    "hati": "liver",
    "kandung empedu": "gallbladder",
    "pankreas": "pancreas",
    "sistem ekskresi": "excretory system",
    "ginjal": "kidney",
    "ureter": "ureter",
    "kandung kemih": "bladder",
    "uretra": "urethra",
    "sistem saraf": "nervous system",
    "otak": "brain",
    "sumsum tulang belakang": "spinal cord",
    "saraf": "nerve",
    "neuron": "neuron",
    "sistem endokrin": "endocrine system",
    "kelenjar pineal": "pineal gland",
    "hipotalamus": "hypothalamus",
    "kelenjar pituitari": "pituitary gland",
    "kelenjar tiroid": "thyroid gland",
    "kelenjar paratiroid": "parathyroid gland",
    "kelenjar adrenal": "adrenal gland",
    "pankreas": "pancreas",
    "kelenjar timus": "thymus gland",
    "kelenjar seks": "reproductive system",
    "ovarium": "ovary",
    "testis": "testis",
    "rahim": "uterus",
    "vagina": "vagina",
    "penis": "penis",
    "sistem reproduksi": "reproductive system",
    "ovarium": "ovary",
    "saluran telur": "fallopian tube",
    "rahim": "uterus",
    "vagina": "vagina",
    "testis": "testis",
    "saluran sperma": "vas deferens",
    "kandung kemih": "bladder",
    "uretra": "urethra",
    "sistem rangka": "skeletal system",
    "tulang": "bone",
    "tulang belakang": "spine",
    "tulang rusuk": "rib",
    "tulang panggul": "pelvic bone",
    "tulang paha": "thigh bone",
    "tulang kering": "shinbone",
    "tulang betis": "calf bone",
    "tulang kaki": "foot bone",
    "tulang lengan": "arm bone",
    "tulang ulna": "ulna",
    "tulang radius": "radius",
    "tulang tangan": "hand bone",
    "tulang jari": "finger bone",
    "tulang tengkorak": "skull bone",
    "sistem endoskeleton": "endoskeleton",
    "sistem eksoskeleton": "exoskeleton",
    "sistem otot": "muscular system",
    "otot lurik": "skeletal muscle",
    "otot polos": "smooth muscle",
    "otot jantung": "cardiac muscle",
    "sistem integumen": "integumentary system",
    "kulit": "skin",
    "rambut": "hair",
    "kuku": "nail",
    "sistem limfatik": "lymphatic system",
    "kelenjar getah bening": "lymph node",
    "limfa": "lymph",
    "amandel": "tonsil",
    "sistem artikulasi": "articulatory system",
    "tulang rawan": "cartilage",
    "sendi": "joint",
    "otot": "muscle",
    "sistem peredaran darah": "circulatory system",
    "darah": "blood",
    "pembuluh darah": "blood vessel",
    "arteri": "artery",
    "vena": "vein",
    "kapiler": "capillary",
    "jantung": "heart",
    "sistem pernapasan": "respiratory system",
    "hidung": "nose",
    "paru-paru": "lung",
    "bronkus": "bronchus",
    "alveolus": "alveolus",
    "diafragma": "diaphragm",
    "sistem pencernaan": "digestive system",
    "mulut": "mouth",
    "esofagus": "esophagus",
    "lambung": "stomach",
    "usus kecil": "small intestine",
    "usus besar": "large intestine",
    "anus": "anus",
    "hati": "liver",
    "kandung empedu": "gallbladder",
    "pankreas": "pancreas",
    "sistem ekskresi": "excretory system",
    "ginjal": "kidney",
    "ureter": "ureter",
    "kandung kemih": "bladder",
    "uretra": "urethra",
    "sistem saraf": "nervous system",
    "otak": "brain",
    "sumsum tulang belakang": "spinal cord",
    "saraf": "nerve",
    "neuron": "neuron",
    "tubuh manusia": "human body",
    "sistem imun": "immune system",
    "antibodi": "antibody",
    "sistem kekebalan tubuh": "immune system",
    "limfosit": "lymphocyte",
    "sel T": "T cell",
    "sel B": "B cell",
    "histamin": "histamine",
    "alergi": "allergy",
    "sistem endokrin": "endocrine system",
    "kelenjar keringat": "sweat gland",
    "kelenjar sebaceous": "sebaceous gland",
    "hormon": "hormone",
    "insulin": "insulin",
    "adrenalin": "adrenaline",
    "melatonin": "melatonin",
    "serta": "and",
    "juga": "also",
    "dan": "and",
    "atau": "or",
    "sebagai": "as",
    "oleh": "by",
    "pada": "on",
    "dengan": "with",
    "untuk": "for",
    "dari": "from",
    "ke": "to",
    "di": "in",
    "lebih": "more",
    "kurang": "less",
    "berbagai": "various",
    "berfungsi": "function",
    "proses": "process",
    "memiliki": "have",
    "terdiri dari": "consist of",
    "bagian": "part",
    "organ": "organ",
    "jaringan": "tissue",
    "sel": "cell",
    "DNA": "DNA",
    "RNA": "RNA",
    "gen": "gene",
    "rekayasa genetika": "genetic engineering",
    "kloning": "cloning",
    "genom": "genome",
    "prokariota": "prokaryote",
    "eukariota": "eukaryote",
    "evolusi": "evolution",
    "adaptasi": "adaptation",
    "seleksi alam": "natural selection",
    "organisme": "organism",
    "spesies": "species",
    "ekosistem": "ecosystem",
    "biodiversitas": "biodiversity",
    "populasi": "population",
    "komunitas": "community",
    "ekologi": "ecology",
    "lingkungan": "environment",
    "siklus": "cycle",
    "bernapas": "breathe",
    "makan": "eat",
    "minum": "drink",
    "bergerak": "move",
    "berpikir": "think",
    "merasa": "feel",
    "melihat": "see",
    "mendengar": "hear",
    "sentuhan": "touch",
    "ciuman": "smell",
    "rasa": "taste",
    "kesadaran": "consciousness",
    "insting": "instinct",
    "memori": "memory",
    "emosi": "emotion",
    "intelektual": "intellectual",
    "kognitif": "cognitive",
    "persepsi": "perception",
    "motorik": "motor",
    "sensorik": "sensory",
    "refleks": "reflex",
    "tidur": "sleep",
    "bangun": "wake up",
    "istirahat": "rest",
    "tidur nyenyak": "deep sleep",
    "tidur ringan": "light sleep",
    "ritme sirkadian": "circadian rhythm",
    "insomnia": "insomnia",
    "mimpi": "dream",
    "alat reproduksi": "reproductive organs",
    "ejakulasi": "ejaculation",
    "orgasme": "orgasm",
    "kehamilan": "pregnancy",
    "menstruasi": "menstruation",
    "menopause": "menopause",
    "fertilisasi": "fertilization",
    "pembuahan": "conception",
    "pemuliaan": "breeding",
    "proses persalinan": "childbirth process",
    "caesarean": "cesarean",
    "pemberian makanan": "feeding",
    "ASI": "breast milk",
    "air susu ibu": "breast milk",
    "popok": "diaper",
    "mainan bayi": "baby toys",
    "perkembangan motorik": "motor development",
    "perkembangan bahasa": "language development",
    "pengetahuan": "knowledge",
    "pemahaman": "understanding",
    "intuisi": "intuition",
    "kreativitas": "creativity",
    "inovasi": "innovation",
    "kecerdasan": "intelligence",
    "komunikasi": "communication",
    "kompetensi sosial": "social competence",
    "emosional": "emotional",
    "empati": "empathy",
    "motivasi": "motivation",
    "stres": "stress",
    "koping": "coping",
    "kebahagiaan": "happiness",
    "depresi": "depression",
    "kecemasan": "anxiety",
    "gangguan tidur": "sleep disorder",
    "kecanduan": "addiction",
    "psikologi": "psychology",
    "psikiatri": "psychiatry",
    "terapi": "therapy",
    "konseling": "counseling",
    "meditasi": "meditation",
    "refleksi": "reflection",
    "introspeksi": "introspection",
    "relaksasi": "relaxation",
    "visualisasi": "visualization",
    "tahap perkembangan": "developmental stage",
    "anak-anak": "children",
    "remaja": "adolescents",
    "dewasa": "adults",
    "lansia": "elderly",
    "kehidupan awal": "early life",
    "pertumbuhan": "growth",
    "perkembangan": "development",
    "penuaan": "aging",
    "perubahan fisik": "physical changes",
    "perubahan mental": "mental changes",
    "penyakit": "disease",
    "penyakit menular": "infectious disease",
    "penyakit tidak menular": "non-communicable disease",
    "penyakit genetik": "genetic disease",
    "penyakit jantung": "heart disease",
    "penyakit kanker": "cancer",
    "diabetes": "diabetes",
    "stroke": "stroke",
    "hipertensi": "hypertension",
    "asma": "asthma",
    "infeksi": "infection",
    "virus": "virus",
    "bakteri": "bacteria",
    "parasit": "parasite",
    "penyakit menular seksual": "sexually transmitted infection (STI)",
    "HIV": "HIV",
    "AIDS": "AIDS",
    "flu": "flu",
    "batuk": "cough",
    "pilek": "cold",
    "alergi": "allergy",
    "autoimun": "autoimmune",
    "kecelakaan": "accident",
    "cedera": "injury",
    "operasi": "surgery",
    "pengobatan": "treatment",
    "obat": "medication",
    "efek samping": "side effects",
    "alergi obat": "drug allergy",
    "obat bebas": "over-the-counter (OTC) drugs",
    "reseptor": "receptor",
    "enzim": "enzyme",
    "vitamin": "vitamin",
    "mineral": "mineral",
    "suplemen": "supplement",
    "pemulihan": "recovery",
    "kesehatan mental": "mental health",
    "terapi bicara": "speech therapy",
    "terapi fisik": "physical therapy",
    "rehabilitasi": "rehabilitation",
    "pemulihan pasca-trauma": "trauma recovery",
    "perawatan paliatif": "palliative care",
    "perawatan jangka panjang": "long-term care",
    "perawatan primer": "primary care",
    "perawatan sekunder": "secondary care",
    "perawatan tersier": "tertiary care",
    "asuransi kesehatan": "health insurance",
    "prestasi": "achievement",
    "keberhasilan": "success",
    "kesalahan": "mistake",
    "tanggung jawab": "responsibility",
    "etika": "ethics",
    "moral": "morality",
    "prinsip": "principle",
    "nilai": "value",
    "kehormatan": "honor",
    "keadilan": "justice",
    "kebebasan": "freedom",
    "demokrasi": "democracy",
    "hak asasi manusia": "human rights",
    "keberagaman": "diversity",
    "inklusi": "inclusion",
    "diskriminasi": "discrimination",
    "pelecehan": "abuse",
    "kekerasan": "violence",
    "peperangan": "war",
    "damai": "peace",
    "harmoni": "harmony",
    "solidaritas": "solidarity",
    "empowerment": "empowerment",
    "kepemimpinan": "leadership",
    "kolaborasi": "collaboration",
    "kompetisi": "competition",
    "kerjasama": "cooperation",
    "pemilihan umum": "election",
    "politik": "politics",
    "pemerintahan": "government",
    "hukum": "law",
    "demokrasi": "democracy",
    "ekonomi": "economy",
    "globalisasi": "globalization",
    "teknologi": "technology",
    "inovasi": "innovation",
    "revolusi industri": "industrial revolution",
    "sains": "science",
    "teknologi informasi": "information technology",
    "kecerdasan buatan": "artificial intelligence",
    "robotika": "robotics",
    "bioteknologi": "biotechnology",
    "energi terbarukan": "renewable energy",
    "pemanasan global": "global warming",
    "lingkungan hidup": "environment",
    "pelestarian alam": "conservation",
    "pencemaran": "pollution",
    "limbah": "waste",
    "daur ulang": "recycling",
    "energi nuklir": "nuclear energy",
    "transportasi": "transportation",
    "mobil listrik": "electric car",
    "penerbangan": "aviation",
    "kereta api": "train",
    "bisnis": "business",
    "kewirausahaan": "entrepreneurship",
    "perusahaan": "corporation",
    "industri": "industry",
    "pemasaran": "marketing",
    "branding": "branding",
    "konsumen": "consumer",
    "produksi": "production",
    "manufaktur": "manufacturing",
    "teori ekonomi": "economic theory",
    "pasar": "market",
    "harga": "price",
    "permintaan": "demand",
    "penawaran": "supply",
    "persaingan": "competition",
    "monopoli": "monopoly",
    "keuangan": "finance",
    "investasi": "investment",
    "bank": "bank",
    "bunga bank": "interest rate",
    "inflasi": "inflation",
    "deflasi": "deflation",
    "saham": "stock",
    "obligasi": "bond",
    "dividen": "dividend",
    "keuangan pribadi": "personal finance",
    "pinjaman": "loan",
    "kredit": "credit",
    "hipotek": "mortgage",
    "asuransi": "insurance",
    "pajak": "tax",
    "penyusutan": "depreciation",
    "akuntansi": "accounting",
    "bisnis internasional": "international business",
    "perekonomian global": "global economy",
    "negosiasi": "negotiation",
    "kontrak": "contract",
    "hukum bisnis": "business law",
    "etika bisnis": "business ethics",
    "tanggung jawab sosial perusahaan": "corporate social responsibility (CSR)",
    "bisnis online": "online business",
    "e-commerce": "e-commerce",
    "start-up": "start-up",
    "teknologi informasi dan komunikasi": "information and communication technology (ICT)",
    "teknologi hijau": "green technology",
    "perubahan iklim": "climate change",
    "pengembangan berkelanjutan": "sustainable development",
    "sumber daya alam": "natural resources",
    "energi": "energy",
    "sumber daya manusia": "human resources",
    "kepegawaian": "human resource management",
    "perekrutan": "recruitment",
    "pelatihan": "training",
    "pengembangan organisasi": "organizational development",
    "manajemen kinerja": "performance management",
    "motivasi karyawan": "employee motivation",
    "kepuasan kerja": "job satisfaction",
    "komunikasi organisasi": "organizational communication",
    "budaya perusahaan": "corporate culture",
    "diversitas dan inklusi": "diversity and inclusion",
    "keamanan kerja": "workplace safety",
    "pengembangan karir": "career development",
    "keseimbangan kerja dan kehidupan": "work-life balance",
    "pemberdayaan karyawan": "employee empowerment",
    "outsourcing": "outsourcing",
    "gaji dan tunjangan": "salary and benefits",
    "manajemen proyek": "project management",
    "tim manajemen": "management team",
    "perencanaan strategis": "strategic planning",
    "analisis SWOT": "SWOT analysis",
    "pemasaran digital": "digital marketing",
    "pelanggan": "customer",
    "brand awareness": "brand awareness",
    "strategi pemasaran": "marketing strategy",
    "inovasi produk": "product innovation",
    "harga penetrasi": "penetration pricing",
    "analisis pasar": "market analysis",
    "riset pasar": "market research",
    "siklus hidup produk": "product life cycle",
    "promosi penjualan": "sales promotion",
    "pemasaran langsung": "direct marketing",
    "manajemen rantai pasokan": "supply chain management",
    "logistik": "logistics",
    "distribusi": "distribution",
    "manajemen operasi": "operations management",
    "produksi lean": "lean production",
    "six sigma": "Six Sigma",
    "teknologi manufaktur": "manufacturing technology",
    "pemeliharaan peralatan": "equipment maintenance",
    "kualitas produk": "product quality",
    "sistem informasi manufaktur": "manufacturing information system",
    "keberlanjutan": "sustainability",
    "etika lingkungan": "environmental ethics",
    "pengelolaan limbah": "waste management",
    "efisiensi energi": "energy efficiency",
    "konservasi air": "water conservation",
    "ramah lingkungan": "eco-friendly",
    "akreditasi": "accreditation",
    "kurikulum": "curriculum",
    "pembelajaran jarak jauh": "distance learning",
    "pendidikan inklusif": "inclusive education",
    "penelitian pendidikan": "educational research",
    "kebijakan pendidikan": "education policy",
    "pembiayaan pendidikan": "education funding",
    "sistem pendidikan": "education system",
    "pendidikan tinggi": "higher education",
    "beasiswa": "scholarship",
    "pendidikan vokasional": "vocational education",
    "pemilihan sekolah": "school choice",
    "evaluasi pendidikan": "educational evaluation",
    "guru": "teacher",
    "kepala sekolah": "school principal",
    "penasihat akademik": "academic advisor",
    "perilaku belajar": "learning behavior",
    "kecerdasan multiple": "multiple intelligences",
    "pendidikan kesejahteraan anak": "child welfare education",
    "pendidikan seni": "art education",
    "pendidikan bahasa": "language education",
    "pendidikan sains": "science education",
    "pendidikan matematika": "mathematics education",
    "olahraga dan pendidikan fisik": "sports and physical education",
    "teknologi pendidikan": "educational technology",
    "kecerdasan buatan dalam pendidikan": "artificial intelligence in education",
    "media pembelajaran": "learning media",
    "gaya mengajar": "teaching style",
    "pembelajaran kolaboratif": "collaborative learning",
    "pembelajaran mandiri": "self-directed learning",
    "penilaian pembelajaran": "learning assessment",
    "e-learning": "e-learning",
    "moralitas": "morality",
    "etika bisnis": "business ethics",
    "etika profesi": "professional ethics",
    "etika penelitian": "research ethics",
    "etika teknologi informasi": "information technology ethics",
    "karakter": "character",
    "integritas": "integrity",
    "kejujuran": "honesty",
    "tanggung jawab sosial": "social responsibility",
    "norma sosial": "social norms",
    "hukum dan etika": "law and ethics",
    "bioetika": "bioethics",
    "etika lingkungan": "environmental ethics",
    "kebebasan berpendapat": "freedom of speech",
    "hak asasi manusia": "human rights",
    "keadilan sosial": "social justice",
    "multikulturalisme": "multiculturalism",
    "pluralisme": "pluralism",
    "toleransi": "tolerance",
    "pengembangan masyarakat": "community development",
    "partisipasi masyarakat": "community participation",
    "kebijakan publik": "public policy",
    "pemerintahan daerah": "local government",
    "pengelolaan risiko": "risk management",
    "kebijakan lingkungan": "environmental policy",
    "perubahan iklim": "climate change",
    "pengelolaan bencana": "disaster management",
    "keamanan nasional": "national security",
    "hubungan internasional": "international relations",
    "organisasi internasional": "international organizations",
    "perjanjian perdagangan": "trade agreements",
    "konflik internasional": "international conflicts",
    "negosiasi damai": "peace negotiations",
    "bantuan luar negeri": "foreign aid",
    "globalisasi ekonomi": "economic globalization",
    "pemberdayaan perempuan": "women's empowerment",
    "pemberdayaan masyarakat": "community empowerment",
    "perubahan sosial": "social change",
    "revolusi digital": "digital revolution",
    "peran media sosial": "role of social media",
    "keamanan siber": "cybersecurity",
    "kecerdasan buatan": "artificial intelligence",
    "robotika": "robotics",
    "otomatisasi": "automation",
    "teknologi biomedis": "biomedical technology",
    "genomika": "genomics",
    "terapi gen": "gene therapy",
    "rekayasa genetika": "genetic engineering",
    "nanoteknologi": "nanotechnology",
    "kecerdasan buatan dalam kesehatan": "artificial intelligence in healthcare",
    "teknologi hijau": "green technology",
    "energi terbarukan": "renewable energy",
    "energi panas bumi": "geothermal energy",
    "energi surya": "solar energy",
    "energi angin": "wind energy",
    "bahan bakar bio": "biofuel",
    "teknologi baterai": "battery technology",
    "teknologi informasi dan komunikasi": "information and communication technology",
    "Internet of Things (IoT)": "Internet of Things (IoT)",
    "big data": "big data",
    "blockchain": "blockchain",
    "teknologi 5G": "5G technology",
    "teknologi virtual reality": "virtual reality technology",
    "teknologi augmented reality": "augmented reality technology",
    "teknologi otomotif": "automotive technology",
    "mobil listrik": "electric cars",
    "mobil otonom": "autonomous vehicles",
    "penerbangan": "aviation",
    "pesawat terbang listrik": "electric aircraft",
    "pesawat terbang otonom": "autonomous aircraft",
    "kereta api cepat": "high-speed train",
    "teknologi pangan": "food technology",
    "pangan organik": "organic food",
    "pangan transgenik": "genetically modified food",
    "keamanan pangan": "food safety",
    "blockchain dalam rantai pasokan makanan": "blockchain in food supply chain",
    "teknologi pertanian": "agricultural technology",
    "pertanian vertikal": "vertical farming",
    "pemantauan tanaman dengan dron": "crop monitoring with drones",
    "teknologi keamanan": "security technology",
    "pengenalan wajah": "facial recognition",
    "pencitraan sidik jari": "fingerprint imaging",
    "teknologi kecerdasan buatan dalam keamanan": "artificial intelligence in security",
    "kecerdasan buatan dalam deteksi kecurangan": "artificial intelligence in fraud detection",
    "kecerdasan buatan dalam kesehatan mental": "artificial intelligence in mental health",
    "robotika medis": "medical robotics",
    "robot bedah": "surgical robot",
    "perawatan kesehatan jarak jauh": "telehealth",
    "aplikasi kesehatan": "health apps",
    "teknologi wearable": "wearable technology",
    "Internet of Medical Things (IoMT)": "Internet of Medical Things (IoMT)",
    "teknologi radiologi": "radiology technology",
    "tomografi komputer (CT)": "computerized tomography (CT)",
    "magnetic resonance imaging (MRI)": "magnetic resonance imaging (MRI)",
    "teknologi pencitraan medis": "medical imaging technology",
    "radioterapi": "radiation therapy",
    "teknologi informasi kesehatan": "health information technology",
    "sistem rekam medis elektronik (EHR)": "electronic health record (EHR) system",
    "keamanan data kesehatan": "health data security",
    "teknologi rehabilitasi": "rehabilitation technology",
    "prostetik": "prosthetics",
    "ekoskeleton": "exoskeleton",
    "teknologi pendidikan": "educational technology",
    "pembelajaran online": "online learning",
    "platform e-learning": "e-learning platforms",
    "teknologi augmented reality dalam pendidikan": "augmented reality technology in education",
    "virtual reality dalam pendidikan": "virtual reality technology in education",
    "pembelajaran adaptif": "adaptive learning",
    "teknologi blockchain dalam pendidikan": "blockchain technology in education",
    "penilaian otomatis": "automated assessment",
    "teknologi kecerdasan buatan dalam pengajaran": "artificial intelligence in teaching",
    "teknologi keamanan siber": "cybersecurity technology",
    "enkripsi": "encryption",
    "firewall": "firewall",
    "antivirus": "antivirus",
    "keamanan jaringan": "network security",
    "teknologi kecerdasan buatan dalam keuangan": "artificial intelligence in finance",
    "analisis risiko keuangan": "financial risk analysis",
    "pengelolaan portofolio": "portfolio management",
    "robot keuangan": "robo-advisors",
    "chatbot keuangan": "financial chatbots",
    "teknologi blockchain dalam keuangan": "blockchain technology in finance",
    "smart contracts": "smart contracts",
    "keamanan transaksi keuangan online": "online financial transaction security",
    "teknologi kecerdasan buatan dalam bisnis": "artificial intelligence in business",
    "analisis data bisnis": "business data analysis",
    "pemrosesan bahasa alami": "natural language processing",
    "pengoptimalan rantai pasokan": "supply chain optimization",
    "analisis sentimen": "sentiment analysis",
    "teknologi kecerdasan buatan dalam pemasaran": "artificial intelligence in marketing",
    "analisis perilaku konsumen": "consumer behavior analysis",
    "personalisasi pemasaran": "personalized marketing",
    "chatbot pemasaran": "marketing chatbots",
    "teknologi kecerdasan buatan dalam manufaktur": "artificial intelligence in manufacturing",
    "pengendalian otomatis": "automatic control",
    "robot industri": "industrial robots",
    "pemeliharaan prediktif": "predictive maintenance",
    "teknologi kecerdasan buatan dalam logistik": "artificial intelligence in logistics",
    "optimasi rute": "route optimization",
    "manajemen inventaris": "inventory management",
    "teknologi kecerdasan buatan dalam sumber daya manusia": "artificial intelligence in human resources",
    "seleksi karyawan otomatis": "automatic employee selection",
    "manajemen kinerja otomatis": "automatic performance management",
    "teknologi kecerdasan buatan dalam hukum": "artificial intelligence in law",
    "analisis hukum": "legal analysis",
    "penelitian hukum": "legal research",
    "pemrosesan bahasa alami dalam hukum": "natural language processing in law",
    "teknologi kecerdasan buatan dalam pelayanan pelanggan": "artificial intelligence in customer service",
    "chatbot layanan pelanggan": "customer service chatbots",
    "pemantauan media sosial": "social media monitoring",
    "analisis data pelanggan": "customer data analysis",
    "teknologi kecerdasan buatan dalam pariwisata": "artificial intelligence in tourism",
    "sistem pemesanan otomatis": "automatic booking system",
    "panduan wisata virtual": "virtual tour guides",
    "rekomendasi destinasi berdasarkan preferensi": "destination recommendations based on preferences",
    "teknologi kecerdasan buatan dalam transportasi": "artificial intelligence in transportation",
    "manajemen lalu lintas": "traffic management",
    "optimasi rute transportasi umum": "public transportation route optimization",
    "teknologi kecerdasan buatan dalam otomotif": "artificial intelligence in automotive",
    "kendaraan otonom": "autonomous vehicles",
    "pemantauan kondisi kendaraan": "vehicle health monitoring",
    "teknologi kecerdasan buatan dalam pertanian": "artificial intelligence in agriculture",
    "penggunaan pupuk dan pestisida yang efisien": "efficient use of fertilizers and pesticides",
    "pemantauan pertumbuhan tanaman": "crop growth monitoring",
    "teknologi kecerdasan buatan dalam energi": "artificial intelligence in energy",
    "prediksi kebutuhan energi": "energy demand prediction",
    "manajemen jaringan listrik pintar": "smart grid management",
    "teknologi kecerdasan buatan dalam lingkungan": "artificial intelligence in environmental",
    "pemantauan polusi udara dan air": "air and water pollution monitoring",
    "pengelolaan limbah yang efisien": "efficient waste management",
    "teknologi kecerdasan buatan dalam penelitian dan pengembangan": "artificial intelligence in research and development",
    "pengujian obat secara virtual": "virtual drug testing",
    "pemodelan struktur molekuler": "molecular structure modeling",
    "teknologi kecerdasan buatan dalam seni dan hiburan": "artificial intelligence in arts and entertainment",
    "penciptaan musik otomatis": "automatic music composition",
    "efek khusus pada film": "special effects in movies",
    "teknologi kecerdasan buatan dalam olahraga": "artificial intelligence in sports",
    "analisis kinerja atlet": "athlete performance analysis",
    "peramalan hasil pertandingan": "sports match outcome prediction",
    "teknologi kecerdasan buatan dalam perbankan": "artificial intelligence in banking",
    "deteksi kecurangan keuangan": "financial fraud detection",
    "analisis kredit otomatis": "automatic credit analysis",
    "teknologi kecerdasan buatan dalam asuransi": "artificial intelligence in insurance",
    "penentuan premi otomatis": "automatic premium determination",
    "klaim asuransi otomatis": "automatic insurance claims",
    "teknologi kecerdasan buatan dalam e-commerce": "artificial intelligence in e-commerce",
    "sistem rekomendasi produk": "product recommendation systems",
    "deteksi penipuan transaksi online": "online transaction fraud detection",
    "teknologi kecerdasan buatan dalam manajemen sumber daya manusia": "artificial intelligence in human resource management",
    "seleksi karyawan otomatis": "automatic employee selection",
    "manajemen kinerja otomatis": "automatic performance management",
    "teknologi kecerdasan buatan dalam pendidikan": "artificial intelligence in education",
    "pembelajaran adaptif": "adaptive learning",
    "pemantauan kemajuan siswa": "student progress monitoring",
    "teknologi kecerdasan buatan dalam hukum": "artificial intelligence in law",
    "analisis hukum": "legal analysis",
    "penelitian hukum": "legal research",
    "pemrosesan bahasa alami dalam hukum": "natural language processing in law",
    "teknologi kecerdasan buatan dalam kesehatan": "artificial intelligence in healthcare",
    "diagnosa penyakit otomatis": "automatic disease diagnosis",
    "pemantauan pasien secara real-time": "real-time patient monitoring",
    "teknologi kecerdasan buatan dalam pelayanan pelanggan": "artificial intelligence in customer service",
    "chatbot layanan pelanggan": "customer service chatbots",
    "analisis sentimen pelanggan": "customer sentiment analysis",
    "pemantauan media sosial": "social media monitoring",
    "analisis data pelanggan": "customer data analysis",
    "teknologi kecerdasan buatan dalam pariwisata": "artificial intelligence in tourism",
    "sistem pemesanan otomatis": "automatic booking system",
    "panduan wisata virtual": "virtual tour guides",
    "rekomendasi destinasi berdasarkan preferensi": "destination recommendations based on preferences",
    "teknologi kecerdasan buatan dalam transportasi": "artificial intelligence in transportation",
    "manajemen lalu lintas": "traffic management",
    "optimasi rute transportasi umum": "public transportation route optimization",
    "teknologi kecerdasan buatan dalam otomotif": "artificial intelligence in automotive",
    "kendaraan otonom": "autonomous vehicles",
    "pemantauan kondisi kendaraan": "vehicle health monitoring",
    "teknologi kecerdasan buatan dalam pertanian": "artificial intelligence in agriculture",
    "penggunaan pupuk dan pestisida yang efisien": "efficient use of fertilizers and pesticides",
    "pemantauan pertumbuhan tanaman": "crop growth monitoring",
    "teknologi kecerdasan buatan dalam energi": "artificial intelligence in energy",
    "prediksi kebutuhan energi": "energy demand prediction",
    "manajemen jaringan listrik pintar": "smart grid management",
    "teknologi kecerdasan buatan dalam lingkungan": "artificial intelligence in environmental",
    "pemantauan polusi udara dan air": "air and water pollution monitoring",
    "pengelolaan limbah yang efisien": "efficient waste management",
    "teknologi kecerdasan buatan dalam penelitian dan pengembangan": "artificial intelligence in research and development",
    "pengujian obat secara virtual": "virtual drug testing",
    "pemodelan struktur molekuler": "molecular structure modeling",
    "teknologi kecerdasan buatan dalam seni dan hiburan": "artificial intelligence in arts and entertainment",
    "penciptaan musik otomatis": "automatic music composition",
    "efek khusus pada film": "special effects in movies",
    "teknologi kecerdasan buatan dalam olahraga": "artificial intelligence in sports",
    "analisis kinerja atlet": "athlete performance analysis",
    "peramalan hasil pertandingan": "sports match outcome prediction",
    "teknologi kecerdasan buatan dalam perbankan": "artificial intelligence in banking",
    "deteksi kecurangan keuangan": "financial fraud detection",
    "analisis kredit otomatis": "automatic credit analysis",
    "teknologi kecerdasan buatan dalam asuransi": "artificial intelligence in insurance",
    "penentuan premi otomatis": "automatic premium determination",
    "klaim asuransi otomatis": "automatic insurance claims",
    "teknologi kecerdasan buatan dalam e-commerce": "artificial intelligence in e-commerce",
    "sistem rekomendasi produk": "product recommendation systems",
    "deteksi penipuan transaksi online": "online transaction fraud detection",
    "teknologi kecerdasan buatan dalam manajemen sumber daya manusia": "artificial intelligence in human resource management",
    "seleksi karyawan otomatis": "automatic employee selection",
    "manajemen kinerja otomatis": "automatic performance management",
    "teknologi kecerdasan buatan dalam pendidikan": "artificial intelligence in education",
    "pembelajaran adaptif": "adaptive learning",
    "pemantauan kemajuan siswa": "student progress monitoring",
    "teknologi kecerdasan buatan dalam hukum": "artificial intelligence in law",
    "analisis hukum": "legal analysis",
    "penelitian hukum": "legal research",
    "pemrosesan bahasa alami dalam hukum": "natural language processing in law",
    "teknologi kecerdasan buatan dalam kesehatan": "artificial intelligence in healthcare",
    "diagnosa penyakit otomatis": "automatic disease diagnosis",
    "pemantauan pasien secara real-time": "real-time patient monitoring",
    "teknologi kecerdasan buatan dalam pelayanan pelanggan": "artificial intelligence in customer service",
    "chatbot layanan pelanggan": "customer service chatbots",
    "analisis sentimen pelanggan": "customer sentiment analysis",
    "pemantauan media sosial": "social media monitoring",
    "analisis data pelanggan": "customer data analysis",
    "teknologi kecerdasan buatan dalam pariwisata": "artificial intelligence in tourism",
    "sistem pemesanan otomatis": "automatic booking system",
    "panduan wisata virtual": "virtual tour guides",
    "rekomendasi destinasi berdasarkan preferensi": "destination recommendations based on preferences",
    "teknologi kecerdasan buatan dalam transportasi": "artificial intelligence in transportation",
    "manajemen lalu lintas": "traffic management",
    "optimasi rute transportasi umum": "public transportation route optimization",
    "teknologi kecerdasan buatan dalam otomotif": "artificial intelligence in automotive",
    "kendaraan otonom": "autonomous vehicles",
    "pemantauan kondisi kendaraan": "vehicle health monitoring",
    "teknologi kecerdasan buatan dalam pertanian": "artificial intelligence in agriculture",
    "penggunaan pupuk dan pestisida yang efisien": "efficient use of fertilizers and pesticides",
    "pemantauan pertumbuhan tanaman": "crop growth monitoring",
    "teknologi kecerdasan buatan dalam energi": "artificial intelligence in energy",
    "prediksi kebutuhan energi": "energy demand prediction",
    "manajemen jaringan listrik pintar": "smart grid management",
    "teknologi kecerdasan buatan dalam lingkungan": "artificial intelligence in environmental",
    "pemantauan polusi udara dan air": "air and water pollution monitoring",
    "pengelolaan limbah yang efisien": "efficient waste management",
    "teknologi kecerdasan buatan dalam penelitian dan pengembangan": "artificial intelligence in research and development",
    "pengujian obat secara virtual": "virtual drug testing",
    "pemodelan struktur molekuler": "molecular structure modeling",
    "teknologi kecerdasan buatan dalam seni dan hiburan": "artificial intelligence in arts and entertainment",
    "penciptaan musik otomatis": "automatic music composition",
    "efek khusus pada film": "special effects in movies",
    "teknologi kecerdasan buatan dalam olahraga": "artificial intelligence in sports",
    "analisis kinerja atlet": "athlete performance analysis",
    "peramalan hasil pertandingan": "sports match outcome prediction",
    "teknologi kecerdasan buatan dalam perbankan": "artificial intelligence in banking",
    "deteksi kecurangan keuangan": "financial fraud detection",
    "analisis kredit otomatis": "automatic credit analysis",
    "teknologi kecerdasan buatan dalam asuransi": "artificial intelligence in insurance",
    "penentuan premi otomatis": "automatic premium determination",
    "klaim asuransi otomatis": "automatic insurance claims",
    "teknologi kecerdasan buatan dalam e-commerce": "artificial intelligence in e-commerce",
    "sistem rekomendasi produk": "product recommendation systems",
    "deteksi penipuan transaksi online": "online transaction fraud detection",
    "teknologi kecerdasan buatan dalam manajemen sumber daya manusia": "artificial intelligence in human resource management",
    "seleksi karyawan otomatis": "automatic employee selection",
    "manajemen kinerja otomatis": "automatic performance management",
    "teknologi kecerdasan buatan dalam pendidikan": "artificial intelligence in education",
    "pembelajaran adaptif": "adaptive learning",
    "pemantauan kemajuan siswa": "student progress monitoring",
    "teknologi kecerdasan buatan dalam hukum": "artificial intelligence in law",
    "analisis hukum": "legal analysis",
    "penelitian hukum": "legal research",
    "pemrosesan bahasa alami dalam hukum": "natural language processing in law",
    "teknologi kecerdasan buatan dalam kesehatan": "artificial intelligence in healthcare",
    "diagnosa penyakit otomatis": "automatic disease diagnosis"
    
}

    return kamusInggris.get(kata.lower(), "KATA TIDAK DITEMUKAN DALAM KAMUS BAHASA INGGRIS.")
    


from flask import Flask, render_template, request, jsonify

app = Flask(__name__)

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/translate', methods=['POST'])
def do_translate():
    translate = request.form['translate']
    pilihan = request.form['pilihan']

    if pilihan == "bahasa inggris":
        terjemahan = translateInggris(translate)
    elif pilihan == "bahasa jepang":
        terjemahan = translateJepang(translate)
    else:
        return jsonify({"error": "Pilihan tidak valid. Silakan pilih 'bahasa Inggris' atau 'bahasa Jepang'."})

    return jsonify({"terjemahan": terjemahan})

if __name__ == '__main__':
    app.run(debug=True)