def translateInggris(kata):
    kamusInggris = {
        
# inggris ke inggris

"cat": "cat",
"dog": "dog",
"elephant": "elephant",
"horse": "horse",
"monkey": "monkey",
"tiger": "tiger",
"butterfly": "butterfly",
"snake": "snake",
"bird": "bird",
"fish": "fish",
"cow": "cow",
"goat": "goat",
"rabbit": "rabbit",
"chicken": "chicken",
"duck": "duck",
"kangaroo": "kangaroo",
"bear": "bear",
"wolf": "wolf",
"lion": "lion",
"beetle": "beetle",
"moth": "moth",
"hippopotamus": "hippopotamus",
"giraffe": "giraffe",
"frog": "frog",
"spider": "spider",
"dolphin": "dolphin",
"whale": "whale",
"bat": "bat",
"mouse": "mouse",
"snail": "snail",
"lizard": "lizard",
"koala": "koala",
"dragonfly": "dragonfly",
"parrot": "parrot",
"pigeon": "pigeon",
"crocodile": "crocodile",
"crab": "crab",
"pig": "pig",
"python": "python",
"seahorse": "seahorse",
"lemur": "lemur",
"camel": "camel",
"leopard": "leopard",
"pangolin": "pangolin",
"porcupine": "porcupine",
"crow": "crow",
"owl": "owl",
"toad": "toad",
"banteng": "banteng",
"turtle": "turtle",
"cockatoo": "cockatoo",
"chimpanzee": "chimpanzee",
"komodo dragon": "komodo dragon",
"black widow spider": "black widow spider",
"shark": "shark",
"shrimp": "shrimp",
"panda": "panda",
"seagull": "seagull",
"cobra": "cobra",
"ram": "ram",
"sparrow": "sparrow",
"ant": "ant",
"star-nosed mole": "star-nosed mole",
"lobster": "lobster",
"sea turtle": "sea turtle",
"cheetah": "cheetah",
"monarch butterfly": "monarch butterfly",
"eagle": "eagle",
"puma": "puma",
"whale shark": "whale shark",
"wood duck": "wood duck",
"deer": "deer",
"poison dart frog": "poison dart frog",
"pink-toed tarantula": "pink-toed tarantula",
"rooster": "rooster",
"seahorse": "seahorse",
"rhinoceros": "rhinoceros",
"wild rabbit": "wild rabbit",
"goose": "goose",
"paradise bird": "paradise bird",
"king butterfly": "king butterfly",
"arctic wolf": "arctic wolf",
"okapi": "okapi",
"bee-eater bird": "bee-eater bird",
"wild boar": "wild boar",
"koi fish": "koi fish",
"blue dragonfly": "blue dragonfly",
"swordfish": "swordfish",
"lobster": "lobster",
"red spider": "red spider",
"white seahorse": "white seahorse",
"sunbathing koala": "sunbathing koala",
"parakeet": "parakeet",
"waterfowl": "waterfowl",
"scorpion": "scorpion",
"stag": "stag",
"water rat": "water rat",
"sand crab": "sand crab",
"black seahorse": "black seahorse",
"box turtle": "box turtle",
"freshwater crocodile": "freshwater crocodile",
"snow dove": "snow dove",
"red dragonfly": "red dragonfly",
"hammerhead shark": "hammerhead shark",
"sheep": "sheep",
"otter": "otter",
"canary": "canary",
"dinosaur": "dinosaur",
"brown rabbit": "brown rabbit",
"black wolf": "black wolf",
"seagull": "seagull",
"swan": "swan",
"seal": "seal",
"tabby cat": "tabby cat",
"lizard": "lizard",
"African elephant": "African elephant",
"golden spider": "golden spider",
"beluga whale": "beluga whale",
"langur monkey": "langur monkey",
"red kangaroo": "red kangaroo",
"cassowary": "cassowary",
"wild rabbit": "wild rabbit",
"yellow dragonfly": "yellow dragonfly",
"brown snake": "brown snake",
"green beetle": "green beetle",
"cockroach": "cockroach",
"zebra": "zebra",
"python snake": "python snake",
"bee": "bee",
"orange butterfly": "orange butterfly",
"black wild boar": "black wild boar",
"blue spider": "blue spider",
"gourami fish": "gourami fish",
"grey wolf": "grey wolf",
"golden orb spider": "golden orb spider",
"white goose": "white goose",
"snowy owl": "snowy owl",
"Persian cat": "Persian cat",
"tarantula": "tarantula",
"white mouse": "white mouse",
"goldfish": "goldfish",
"white rabbit": "white rabbit",
"catfish": "catfish",
"brown bear": "brown bear",
"great horned owl": "great horned owl",
"giant black spider": "giant black spider",
"freshwater crab": "freshwater crab",
"osprey": "osprey",
"red seagull": "red seagull",
"yellow butterfly": "yellow butterfly",
"brown wild pig": "brown wild pig",
"stingray": "stingray",
"zebra horse": "zebra horse",
"little owl": "little owl",
"purple butterfly": "purple butterfly",
"white wild boar": "white wild boar",
"giant red spider": "giant red spider",
"giant green seagull": "giant green seagull",
"sea crab": "sea crab",
"tuna fish": "tuna fish",
"green spider": "green spider",
"black cat": "black cat",
"koi carp": "koi carp",
"dark brown rabbit": "dark brown rabbit",
"Indian elephant": "Indian elephant",
"giant black wolf": "giant black wolf",
"brown owl": "brown owl",
"giant golden orb spider": "giant golden orb spider",
"black swan": "black swan",
"green snake": "green snake",
"giant pink-toed tarantula": "giant pink-toed tarantula",
"giant hammerhead shark": "giant hammerhead shark",
"giant red seagull": "giant red seagull",
"giant blue butterfly": "giant blue butterfly",
"giant brown wild pig": "giant brown wild pig",
"giant catfish": "giant catfish",
"giant brown bear": "giant brown bear",
"giant green seagull": "giant green seagull",
"giant zebra horse": "giant zebra horse",
"giant black cat": "giant black cat",
"giant koi carp": "giant koi carp",
"giant Indian elephant": "giant Indian elephant",
"giant dark brown rabbit": "giant dark brown rabbit",
"giant black wolf": "giant black wolf",
"giant giant golden orb spider": "giant giant golden orb spider",
"giant black swan": "giant black swan",
"giant green snake": "giant green snake",

"cheetah": "cheetah",
  "butterflyfish": "butterflyfish",
  "gazelle": "gazelle",
  "octopus": "octopus",
  "penguin": "penguin",
  "rhinoceros": "rhinoceros",
  "giraffe": "giraffe",
  "hedgehog": "hedgehog",
  "iguana": "iguana",
  "jaguar": "jaguar",
  "kiwi": "kiwi",
  "lemur": "lemur",
  "mongoose": "mongoose",
  "newt": "newt",
  "orangutan": "orangutan",
  "panda": "panda",
  "quokka": "quokka",
  "raccoon": "raccoon",
  "sloth": "sloth",
  "tapir": "tapir",
  "umbrellabird": "umbrellabird",
  "vulture": "vulture",
  "wombat": "wombat",
  "x-raytetra": "x-raytetra",
  "yak": "yak",
  "zebu": "zebu",
  "albatross": "albatross",
  "bison": "bison",
  "capybara": "capybara",
  "dolphin": "dolphin",
  "elephantseal": "elephant seal",
  "falcon": "falcon",
  "gorilla": "gorilla",
  "hummingbird": "hummingbird",
  "impala": "impala",
  "jellyfish": "jellyfish",
  "koala": "koala",
  "lionfish": "lionfish",
  "mantisshrimp": "mantis shrimp",
  "narwhal": "narwhal",
  "opossum": "opossum",
  "quail": "quail",
  "reindeer": "reindeer",
  "salamander": "salamander",
  "tarsier": "tarsier",
  "umbrellabird": "umbrellabird",
  "viperfish": "viperfish",
  "whippet": "whippet",
  "xraytetra": "x-ray tetra",
  "yeti": "yeti",
  "zebrashark": "zebra shark", 
  "alpaca": "alpaca",
  "barracuda": "barracuda",
  "chameleon": "chameleon",
  "dugong": "dugong",
  "flamingo": "flamingo",
  "gnat": "gnat",
  "humpbackwhale": "humpback whale",
  "impala": "impala",
  "javanrhinoceros": "Javan rhinoceros",
  "kingfisher": "kingfisher",
  "lynx": "lynx",
  "macaw": "macaw",
  "nudibranch": "nudibranch",
  "okapi": "okapi",
  "platypus": "platypus",
  "quokka": "quokka",
  "rhinocerosbeetle": "rhinoceros beetle",
  "seahorse": "seahorse",
  "toucan": "toucan",
  "uakari": "uakari",
  "vulture": "vulture",
  "walrus": "walrus",
  "xraytetra": "x-ray tetra",
  "yak": "yak",
  "zebu": "zebu",
  "armadillo": "armadillo",
  "binturong": "binturong",
  "caiman": "caiman",
  "dhole": "dhole",
  "eland": "eland",
  "fossa": "fossa",
  "glowworm": "glowworm",
  "horseshoecrab": "horseshoe crab",
  "impala": "impala",
  "jaguarundi": "jaguarundi",
  "kangaroo": "kangaroo",
  "lemming": "lemming",
  "marmoset": "marmoset",
  "nematode": "nematode",
  "orangutan": "orangutan",
  "porcupine": "porcupine",
  "quokka": "quokka",
  "rattlesnake": "rattlesnake",
  "shrimp": "shrimp",
  "tapir": "tapir",
  "urchin": "urchin",
  "vole": "vole",
  "weasel": "weasel",
  "xrayfish": "x-ray fish",
  "yellowjacket": "yellowjacket",
  "zebu": "zebu",
  "avocet": "avocet",
  "bongo": "bongo",
  "chinchilla": "chinchilla",
  "dhole": "dhole",
  "earwig": "earwig",
  "firefly": "firefly",
  "goose": "goose",
  "hedgehog": "hedgehog",
  "impala": "impala",
  "jaguar": "jaguar",
  "kinkajou": "kinkajou",
  "lemur": "lemur",
  "macaque": "macaque",
  "nutria": "nutria",
  "ocelot": "ocelot",
  "pangolin": "pangolin",
  "quokka": "quokka",
  "redpanda": "red panda",
  "seadragon": "seadragon",
  "tarsier": "tarsier",
  "uakari": "uakari",
  "viperfish": "viperfish",
  "wolverine": "wolverine",
  "xrayfish": "x-ray fish",
  "yellowjacket": "yellowjacket",
  "zebu": "zebu",
  "ant": "ant",
  "bat": "bat",
  "crocodile": "crocodile",
  "dolphin": "dolphin",
  "elephant": "elephant",
  "falcon": "falcon",
  "gazelle": "gazelle",
  "hedgehog": "hedgehog",
  "iguana": "iguana",
  "jaguar": "jaguar",
  "koala": "koala",
  "lemur": "lemur",
  "mongoose": "mongoose",
  "newt": "newt",
  "octopus": "octopus",
  "penguin": "penguin",
  "rhinoceros": "rhinoceros",
  "giraffe": "giraffe",
  "tiger": "tiger",
  "chimpanzee": "chimpanzee",
  "komodo dragon": "komodo dragon",
  "tarantula": "tarantula",
  "whale": "whale",
  "zebra": "zebra",
        
#indo ke inggris

"kucing" : "cat",
"anjing" : "dog",
"gajah" : "elephant",
"kuda" : "horse",
"monyet" : "monkey",
"harimau" : "tiger",
"kupu-kupu" : "butterfly",
"ular" : "snake",
"burung" : "bird",
"ikan" : "fish",
"sapi" : "cow",
"kambing" : "goat",
"kelinci" : "rabbit",
"ayam" : "chicken",
"bebek" : "duck",
"kanguru" : "kangaroo",
"beruang" : "bear",
"serigala" : "wolf",
"singa" : "lion",
"kumbang" : "beetle",
"kupu-kupu malam" : "moth",
"kuda nil" : "hippopotamus",
"jerapah" : "giraffe",
"katak" : "frog",
"laba-laba" : "spider",
"lumba-lumba" : "dolphin",
"paus" : "whale",
"kelelawar" : "bat",
"tikus" : "mouse",
"kelomang" : "snail",
"cicak" : "lizard",
"koala" : "koala",
"capung" : "dragonfly",
"beo" : "parrot",
"merpati" : "pigeon",
"ruak-ruak" : "crocodile",
"kepiting" : "crab",
"babi" : "pig",
"ular python" : "python",
"kuda laut" : "seahorse",
"monyet ekor panjang" : "lemur",
"unta" : "camel",
"macan tutul" : "leopard",
"trenggiling" : "pangolin",
"landak" : "porcupine",
"gagak" : "crow",
"burung hantu" : "owl",
"kodok" : "toad",
"banteng" : "banteng",
"kura-kura" : "turtle",
"kakatua" : "cockatoo",
"penyu" : "turtle",
"simpanse" : "chimpanzee",
"komodo" : "komodo dragon",
"laba-laba hitam" : "black widow spider",
"hiu" : "shark",
"udang" : "shrimp",
"panda" : "panda",
"burung camar" : "seagull",
"ular cobra" : "cobra",
"gembala jantan" : "ram",
"burung gereja" : "sparrow",
"semut" : "ant",
"harimau bintang" : "star-nosed mole",
"lobster" : "lobster",
"penyu laut" : "sea turtle",
"macan" : "cheetah",
"kupu-kupu monark" : "monarch butterfly",
"elang" : "eagle",
"puma" : "puma",
"hiu paus" : "whale shark",
"bebek hutan" : "wood duck",
"kijang" : "deer",
"katak beracun" : "poison dart frog",
"laba-laba merah jambu" : "pink-toed tarantula",
"ayam jantan" : "rooster",
"kuda laut laut" : "sea horse",
"badak" : "rhinoceros",
"kelinci liar" : "wild rabbit",
"angsa" : "goose",
"cendrawasih" : "paradise bird",
"kupu-kupu raja" : "king butterfly",
"serigala kutub" : "arctic wolf",
"jerapah okapi" : "okapi",
"burung pemakan lebah" : "bee-eater bird",
"celeng" : "wild boar",
"ikan koi" : "koi fish",
"capung biru" : "blue dragonfly",
"ikan paus" : "swordfish",
"camar" : "lobster",
"laba-laba merah" : "red spider",
"kuda laut gergaji" : "sawfish",
"kancil" : "mouse deer",
"burung hantu elang" : "eagle owl",
"beruang kutub" : "polar bear",
"lalat" : "fly",
"bintang laut" : "starfish",
"babi hutan" : "wild pig",
"serigala hutan" : "woodland wolf",
"kuda laut putih" : "white seahorse",
"koala berjemur" : "sunbathing koala",
"burung beo" : "parakeet",
"bebek air" : "waterfowl",
"kalajengking" : "scorpion",
"rusa" : "stag",
"tikus air" : "water rat",
"kepiting pasir" : "sand crab",
"kuda laut hitam" : "black seahorse",
"kura-kura darat" : "box turtle",
"buaya air tawar" : "freshwater crocodile",
"merpati salju" : "snow dove",
"capung merah" : "red dragonfly",
"ikan hiu" : "hammerhead shark",
"domba" : "sheep",
"berang-berang" : "otter",
"burung kenari" : "canary",
"dinosaurus" : "dinosaur",
"kelinci cokelat" : "brown rabbit",
"serigala hitam" : "black wolf",
"burung camar laut" : "seagull",
"kepala angsa" : "swan",
"anjing laut" : "seal",
"kucing belang" : "tabby cat",
"kadal" : "lizard",
"gajah Afrika" : "African elephant",
"laba-laba emas" : "golden spider",
"paus putih" : "beluga whale",
"monyet langur" : "langur monkey",
"kanguru merah" : "red kangaroo",
"burung kasuari" : "cassowary",
"kelinci abu-abu" : "grey rabbit",
"capung kuning" : "yellow dragonfly",
"kucing siam" : "Siamese cat",
"kerbau" : "buffalo",
"katak hijau" : "green frog",
"ular cokelat" : "brown snake",
"kumbang hijau" : "green beetle",
"kecoa" : "cockroach",
"zebra" : "zebra",
"ular piton" : "python snake",
"lebah" : "bee",
"kupu-kupu oranye" : "orange butterfly",
"babi hutan hitam" : "black wild boar",
"laba-laba biru" : "blue spider",
"ikan gurame" : "gourami fish",
"serigala kelabu" : "grey wolf",
"laba-laba jaring emas" : "golden orb spider",
"angsa putih" : "white goose",
"burung hantu salju" : "snowy owl",
"kucing persia" : "Persian cat",
"laba-laba besar" : "tarantula",
"tikus putih" : "white mouse",
"ikan mas" : "goldfish",
"kelinci putih" : "white rabbit",
"ikan lele" : "catfish",
"beruang cokelat" : "brown bear",
"burung hantu besar" : "great horned owl",
"laba-laba hitam besar" : "giant black spider",
"kepiting air tawar" : "freshwater crab",
"elang laut" : "osprey",
"burung camar merah" : "red seagull",
"kupu-kupu kuning" : "yellow butterfly",
"babi hutan cokelat" : "brown wild pig",
"ikan pari" : "stingray",
"kuda zebra" : "zebra horse",
"burung hantu kecil" : "little owl",
"kupu-kupu ungu" : "purple butterfly",
"babi hutan putih" : "white wild boar",
"laba-laba merah besar" : "giant red spider",
"burung camar hijau" : "green seagull",
"kepiting air laut" : "sea crab",
"ikan tuna" : "tuna fish",
"laba-laba hijau" : "green spider",
"kucing hitam" : "black cat",
"ikan mas koki" : "koi carp",
"kelinci cokelat tua" : "dark brown rabbit",
"gajah India" : "Indian elephant",
"serigala hitam besar" : "giant black wolf",
"burung hantu cokelat" : "brown owl",
"laba-laba jaring emas besar" : "giant golden orb spider",
"angsa hitam" : "black swan",
"ular hijau" : "green snake",
"laba-laba merah jambu besar" : "giant pink-toed tarantula",
"ikan hiu besar" : "giant hammerhead shark",
"burung camar merah besar" : "giant red seagull",
"kupu-kupu biru besar" : "giant blue butterfly",
"babi hutan cokelat besar" : "giant brown wild pig",
"ikan lele besar" : "giant catfish",
"beruang cokelat besar" : "giant brown bear",
"burung camar hijau besar" : "giant green seagull",
"kuda zebra besar" : "giant zebra horse",
"kucing hitam besar" : "giant black cat",
"ikan mas koki besar" : "giant koi carp",
"gajah India besar" : "giant Indian elephant",
"kelinci cokelat tua besar" : "giant dark brown rabbit",
"serigala hitam besar" : "giant black wolf",
"laba-laba jaring emas besar" : "giant giant golden orb spider",
"angsa hitam besar" : "giant black swan",
"ular hijau besar" : "giant green snake",

#Jepang ke inggris

"neko": "cat",
"inu": "dog",
"zou": "elephant",
"uma": "horse",
"saru": "monkey",
"tora": "tiger",
"cho": "butterfly",
"hebi": "snake",
"tori": "bird",
"sakana": "fish",
"ushi": "cow",
"yagi": "goat",
"usagi": "rabbit",
"niwatori": "chicken",
"ahiru": "duck",
"kangaru": "kangaroo",
"kuma": "bear",
"okami": "wolf",
"raion": "lion",
"mushi": "beetle",
"ga": "moth",
"kaba": "hippopotamus",
"kirin": "giraffe",
"kaeru": "frog",
"kumo": "spider",
"iruka": "dolphin",
"kujira": "whale",
"koumori": "bat",
"nezumi": "mouse",
"katatsumuri": "snail",
"tokage": "lizard",
"koala": "koala",
"tonbo": "dragonfly",
"inko": "parrot",
"hato": "pigeon",
"wani": "crocodile",
"kani": "crab",
"buta": "pig",
"paiton": "python",
"umihoshi": "seahorse",
"remuru": "lemur",
"rakuda": "camel",
"hyou": "leopard",
"yamori": "pangolin",
"yamakuzuri": "porcupine",
"karasu": "crow",
"fukurou": "owl",
"hiki": "toad",
"banteng": "banteng",
"kame": "turtle",
"kakatou": "cockatoo",
"kame": "turtle",
"chimpanji": "chimpanzee",
"komodo doragon": "komodo dragon",
"burakku widou kumo": "black widow spider",
"same": "shark",
"ebi": "shrimp",
"panda": "panda",
"kamome": "seagull",
"koubura": "cobra",
"ramu": "ram",
"suzume": "sparrow",
"ari": "ant",
"sutaanouzu mooru": "star-nosed mole",
"robusutaa": "lobster",
"umigame": "sea turtle",
"chiita": "cheetah",
"mOnaaku chou": "monarch butterfly",
"washi": "eagle",
"puma": "puma",
"huriru shaku": "whale shark",
"mokusei": "wood duck",
"shika": "deer",
"dokuhirokaeru": "poison dart frog",
"pinku toodo taranchura": "pink-toed tarantula",
"niwatori": "rooster",
"umihoshi": "seahorse",
"saihinocerosu": "rhinoceros",
"yaseiusagi": "wild rabbit",
"gacha": "goose",
"paradaisu baado": "paradise bird",
"kingu chou": "king butterfly",
"akuteikku urufu": "arctic wolf",
"okapi": "okapi",
"bii itaa": "bee-eater bird",
"yasei buta": "wild boar",
"koi": "koi fish",
"buruu tonbo": "blue dragonfly",
"ken hirameki": "swordfish",
"robusutaa": "lobster",
"reddo supaida": "red spider",
"howaito umihoshi": "white seahorse",
"hiyake no koara": "sunbathing koala",
"o-mume-sama": "parakeet",
"suichu rui": "waterfowl",
"sasori": "scorpion",
"kanuka": "stag",
"mizu nezumi": "water rat",
"suna gani": "sand crab",
"burakku umihoshi": "black seahorse",
"hako kame": "box turtle",
"seisui wani": "freshwater crocodile",
"yuki hato": "snow dove",
"akai tonbo": "red dragonfly",
"hanmaa heddo shaku": "hammerhead shark",
"hitsuji": "sheep",
"kawauso": "otter",
"kanaria": "canary",
"kyoryu": "dinosaur",
"chairoi usagi": "brown rabbit",
"kuroi ookami": "black wolf",
"kamome": "seagull",
"hakucho": "swan",
"azarashi": "seal",
"tora neko": "tabby cat",
"tokage": "lizard",
"afurika zou": "African elephant",
"kogane no kumo": "golden spider",
"beruga kujira": "beluga whale",
"ranguru saru": "langur monkey",
"akai kangaru": "red kangaroo",
"kassowari": "cassowary",
"haiiroi usagi": "grey rabbit",
"kiro tonbo": "yellow dragonfly",
"chairoi hebi": "brown snake",
"midori mushi": "green beetle",
"gokiburi": "cockroach",
"zebra": "zebra",
"paiton hebi": "python snake",
"hachi": "bee",
"orenji no chou": "orange butterfly",
"kuroi yasei buta": "black wild boar",
"aoi kumo": "blue spider",
"gurame": "gourami fish",
"haiiro no ookami": "grey wolf",
"konjiki no kumo": "golden orb spider",
"shiroi gacha": "white goose",
"yuki fukurou": "snowy owl",
"perushan neko": "Persian cat",
"taranchura": "tarantula",
"shiroi nezumi": "white mouse",
"kingyo": "goldfish",
"shiroi usagi": "white rabbit",
"namazu": "catfish",
"chairoi kuma": "brown bear",
"gureito honnodo": "great horned owl",
"kyodai kuroi kumo": "giant black spider",
"seisui kani": "freshwater crab",
"osupurei": "osprey",
"akai kamome": "red seagull",
"kiiro no chou": "yellow butterfly",
"chairoi yasei buta": "brown wild pig",
"sutinrei": "stingray",
"zebura uma": "zebra horse",
"ritoru fukurou": "little owl",
"murasaki no chou": "purple butterfly",
"shiroi yasei buta": "white wild boar",
"kyodai akai kumo": "giant red spider",
"midori kamome": "giant green seagull",
"umi gani": "sea crab",
"maguro": "tuna fish",
"midori no kumo": "green spider",
"kuroi neko": "black cat",
"koi koi": "koi carp",
"kurokuroi usagi": "dark brown rabbit",
"indo zou": "Indian elephant",
"kyodai kuroi ookami": "giant black wolf",
"chairoi fukurou": "brown owl",
"kyodai konjiki no kumo": "giant golden orb spider",
"kuroi hakucho": "black swan",
"midori hebi": "green snake",
"kyodai pinku toodo taranchura": "giant pink-toed tarantula",
"kyodai hanmaa heddo shaku": "giant hammerhead shark",
"kyodai akai kamome": "giant red seagull",
"kyodai aoi chou": "giant blue butterfly",
"kyodai chairoi yasei buta": "giant brown wild pig",
"kyodai namazu": "giant catfish",
"kyodai chairoi kuma": "giant brown bear",
"kyodai midori kamome": "giant green seagull",
"kyodai zebura uma": "giant zebra horse",
"kyodai kuroi neko": "giant black cat",
"kyodai koi koi": "giant koi carp",
"kyodai indo zou": "giant Indian elephant",
"kyodai kurokuroi usagi": "giant dark brown rabbit",
"kyodai kuroi ookami": "giant black wolf",
"kyodai kyodai konjiki no kumo": "giant giant golden orb spider",
"kyodai kuroi hakucho": "giant black swan",
"kyodai midori hebi": "giant green snake",
}

    return kamusInggris.get(kata.lower(), "KATA TIDAK DITEMUKAN DI KAMUS BAHASA INGGRIS.")