def translateIndo(kata):
    KamusIndonesia = {
        
#indo ke indo

"kucing": "kucing",
"anjing": "anjing",
"sapi": "sapi",
"burung": "burung",
"kelinci": "kelinci",
"babi": "babi",
"ikan": "ikan",
"kura-kura": "kura-kura",
"ular": "ular",
"gajah": "gajah",
"harimau": "harimau",
"kuda": "kuda",
"kirin": "kirin",
"kepiting": "kepiting",
"rubah": "rubah",
"anjing Akita": "anjing Akita",
"tengu": "tengu",
"tanuki": "tanuki",
"monyet": "monyet",
"burung gereja": "burung gereja",
"kuda laut": "kuda laut",
"paus": "paus",
"ikan koi": "ikan koi",
"lebah": "lebah",
"keong api": "keong api",
"gurita": "gurita",
"merak": "merak",
"berang-berang": "berang-berang",
"beruang": "beruang",
"kelelawar": "kelelawar",
"kupu-kupu": "kupu-kupu",
"kambing liar": "kambing liar",
"kanaria": "kanaria",
"koala": "koala",
"kelinci laut": "kelinci laut",
"rusa": "rusa",
"burung camar": "burung camar",
"singa": "singa",
"hiu": "hiu",
"jaguar": "jaguar",
"kupu-kupu": "kupu-kupu",
"gurita": "gurita",
"tengu": "tengu",
"tanuki": "tanuki",
"burung": "burung",
"kadal": "kadal",
"capung": "capung",
"buaya": "buaya",
"boneka": "boneka",
"hamster": "hamster",
"ayam muda": "ayam muda",
"gajah laut": "gajah laut",
"burung phoenix": "burung phoenix",
"burung hantu": "burung hantu",
"penguin": "penguin",
"panda": "panda",
"kepiting": "kepiting",
"kelabang": "kelabang",
"tapir": "tapir",
"bajak laut": "bajak laut",
"serangga": "serangga",
"kambing": "kambing",
"gecko": "gecko",
"kuda nil": "kuda nil",
"singa": "singa",
"rubah": "rubah",
"rusa kutub": "rusa kutub",
"gembala": "gembala",
"hantu Jepang": "hantu Jepang",
"buaya": "buaya",
"elang": "elang",
"sapi": "sapi",
"burung robin": "burung robin",
"belut": "belut",
"ulat daun": "ulat daun",
"udang": "udang",


        
# jepang ke indo

"neko": "kucing",
"inu": "anjing",
"ushi": "sapi",
"tori": "burung",
"usagi": "kelinci",
"buta": "babi",
"sakana": "ikan",
"kame": "kura-kura",
"hebi": "ular",
"zou": "gajah",
"tora": "harimau",
"uma": "kuda",
"kirin": "kirin",
"sarugani": "kepiting",
"kitsune": "rubah",
"akita inu": "anjing Akita",
"tengu": "tengu",
"tanuki": "tanuki",
"saru": "monyet",
"suzume": "burung gereja",
"ushiwaka": "kuda laut",
"kujira": "paus",
"koi": "ikan koi",
"hachi": "lebah",
"hotaru": "keong api",
"ika": "gurita",
"kujaku": "merak",
"kawauso": "berang-berang",
"kuma": "beruang",
"komori": "kelelawar",
"konoha": "kupu-kupu",
"kamoshika": "kambing liar",
"kanaria": "kanaria",
"koala": "koala",
"korin": "kelinci laut",
"shika": "rusa",
"shachou": "burung camar",
"shishi": "singa",
"shark": "hiu",
"jaguar": "jaguar",
"joou": "kupu-kupu",
"tako": "gurita",
"tengu": "tengu",
"tanuki": "tanuki",
"tori": "burung",
"tokage": "kadal",
"tombo": "capung",
"nigai": "buaya",
"nuigurumi": "boneka",
"hamu": "hamster",
"hiyoko": "ayam muda",
"bou": "gajah laut",
"houou": "burung phoenix",
"fukurou": "burung hantu",
"pen": "penguin",
"panda": "panda",
"pipi": "kepiting",
"hirameki": "kelabang",
"baku": "tapir",
"mujaki": "bajak laut",
"mushi": "serangga",
"yagi": "kambing",
"yamori": "gecko",
"rakuda": "kuda nil",
"raion": "singa",
"regu": "rubah",
"reindeer": "rusa kutub",
"roba": "gembala",
"rokurokubi": "hantu Jepang",
"wani": "buaya",
"washi": "elang",
"ushi": "sapi",
"ukitsumomiji": "burung robin",
"unagi": "belut",
"enokimushi": "ulat daun",
"ebi": "udang",
"chītā": "cheetah",
"batarifurifisshu": "ikan kupu-kupu",
"gazeru": "gazelle",
"okutopasu": "octopus",
"pengin": "penguin",
"rainoserosu": "badak",
"jirafu": "jerapah",
"hejjihoggu": "kelinci duri",
"igwana": "iguana",
"jagwā": "jaguar",
"kīui": "kiwi",
"remā": "lemur",
"mongūsu": "mongoose",
"nyūto": "salamander",
"orangutan": "orangutan",
"panda": "panda",
"kwokka": "quokka",
"rakūn": "raccoon",
"surōsu": "sloth",
"tapiru": "tapir",
"anburera bādo": "burung payung",
"varuchā": "vulture",
"wombatto": "wombat",
"ekkusu-rei tetora": "x-raytetra",
"yakku": "yak",
"zēbu": "zebu",
"arubatorosu": "albatross",
"baison": "bison",
"kapibara": "capybara",
"dorufin": "dolphin",
"erufantoshīru": "elephantseal",
"farukon": "falcon",
"gorira": "gorilla",
"hanmingubādo": "hummingbird",
"inpara": "impala",
"jerīfisshu": "giraffe",
"koara": "koala",
"raionfisshu": "lionfish",
"mantisushirimp": "mantisshrimp",
"nāwaru": "narwhal",
"oposamu": "opossum",
"kueiru": "quail",
"rēndia": "reindeer",
"saramandā": "salamander",
"tāshā": "tarsier",
"anburera bādo": "umbrellabird",
"vaipāfisshu": "viperfish",
"uippetto": "whippet",
"ekkusu-rei tetora": "xraytetra",
"ieti": "yeti",
"zeburashāku": "zebrashark",
"arupaka": "alpaca",
"barakūda": "barracuda",
"kamereon": "chameleon",
"dyūgongu": "dugong",
"furamingo": "flamingo",
"natto": "gnat",
"hanpbakkuhōru": "humpbackwhale",
"jābanrainoserosu": "javanrhinoceros",
"kingufishā": "kingfisher",
"rinkusu": "lynx",
"makō": "macaw",
"nudoburanku": "nudibranch",
"okapī": "okapi",
"puratipasu": "platypus",
"kwokka": "quokka",
"rainoserosubītoru": "rhinocerosbeetle",
"shīhōsu": "seahorse",
"tūkan": "toucan",
"wakari": "uakari",
"varuchā": "vulture",
"wōrasu": "walrus",
"ekkusu-rei tetora": "xraytetra",
"yakku": "yak",
"zēbu": "zebu",
"āmadirō": "armadillo",
"binturongu": "binturong",
"kaiman": "caiman",
"dōru": "dhole",
"erando": "eland",
"fossa": "fossa",
"gurōwāmu": "glowworm",
"hōsushukurabu": "horseshoecrab",
"jaguarundi": "jaguarundi",
"kangarū": "kangaroo",
"rebingu": "lemming",
"māmosetto": "marmoset",
"nematōdo": "nematode",
"orangutan": "orangutan",
"pōkupain": "porcupine",
"kwokka": "quokka",
"ratorusunēku": "rattlesnake",
"shurimp": "shrimp",
"tapiru": "tapir",
"āchin": "urchin",
"vōru": "vole",
"wīzaru": "weasel",
"ekkusu-rei fissu": "xrayfish",
"yerōjyaketto": "yellowjacket",
"zēbu": "zebu",
"ari": "ant",
"kōmori": "bat",
"wani": "crocodile",
"iruka": "dolphin",
"zō": "elephant",
"hayabusa": "falcon",
"harikein": "gazelle",
"irawā": "hedgehog",
"jagwā": "jaguar",
"kuma": "koala",
"ari": "lemur",
"sāmandā": "mongoose",
"taranchura": "tarantula",
"wēru": "whale",
"zebu": "zebra",

#inggris ke indo

"cat": "kucing",
"dog": "anjing",
"elephant": "gajah",
"horse": "kuda",
"monkey": "monyet",
"tiger": "harimau",
"butterfly": "kupu-kupu",
"snake": "ular",
"bird": "burung",
"fish": "ikan",
"cow": "sapi",
"goat": "kambing",
"rabbit": "kelinci",
"chicken": "ayam",
"duck": "bebek",
"kangaroo": "kanguru",
"bear": "beruang",
"wolf": "serigala",
"lion": "singa",
"beetle": "kumbang",
"moth": "kupu-kupu malam",
"hippopotamus": "kuda nil",
"giraffe": "jerapah",
"frog": "katak",
"spider": "laba-laba",
"dolphin": "lumba-lumba",
"whale": "paus",
"bat": "kelelawar",
"mouse": "tikus",
"snail": "kelomang",
"lizard": "cicak",
"koala": "koala",
"dragonfly": "capung",
"parrot": "beo",
"pigeon": "merpati",
"crocodile": "ruak-ruak",
"crab": "kepiting",
"pig": "babi",
"python": "ular python",
"seahorse": "kuda laut",
"lemur": "monyet ekor panjang",
"camel": "unta",
"leopard": "macan tutul",
"pangolin": "trenggiling",
"porcupine": "landak",
"crow": "gagak",
"owl": "burung hantu",
"toad": "kodok",
"banteng": "banteng",
"turtle": "kura-kura",
"cockatoo": "kakatua",
"turtle": "penyu",
"chimpanzee": "simpanse",
"komodo dragon": "komodo",
"black widow spider": "laba-laba hitam",
"shark": "hiu",
"shrimp": "udang",
"panda": "panda",
"seagull": "burung camar",
"cobra": "ular cobra",
"ram": "gembala jantan",
"sparrow": "burung gereja",
"ant": "semut",
"star-nosed mole": "harimau bintang",
"lobster": "lobster",
"sea turtle": "penyu laut",
"cheetah": "macan",
"monarch butterfly": "kupu-kupu monark",
"eagle": "elang",
"puma": "puma",
"whale shark": "hiu paus",
"wood duck": "bebek hutan",
"deer": "kijang",
"poison dart frog": "katak beracun",
"pink-toed tarantula": "laba-laba merah jambu",
"rooster": "ayam jantan",
"sea horse": "kuda laut laut",
"rhinoceros": "badak",
"wild rabbit": "kelinci liar",
"goose": "angsa",
"paradise bird": "cendrawasih",
"king butterfly": "kupu-kupu raja",
"arctic wolf": "serigala kutub",
"okapi": "jerapah okapi",
"bee-eater bird": "burung pemakan lebah",
"wild boar": "celeng",
"koi fish": "ikan koi",
"blue dragonfly": "capung biru",
"swordfish": "ikan paus",
"lobster": "camar",
"red spider": "laba-laba merah",
"sawfish": "kuda laut gergaji",
"mouse deer": "kancil",
"eagle owl": "burung hantu elang",
"polar bear": "beruang kutub",
"fly": "lalat",
"starfish": "bintang laut",
"wild pig": "babi hutan",
"woodland wolf": "serigala hutan",
"white seahorse": "kuda laut putih",
"sunbathing koala": "koala berjemur",
"parakeet": "burung beo",
"waterfowl": "bebek air",
"scorpion": "kalajengking",
"stag": "rusa",
"water rat": "tikus air",
"sand crab": "kepiting pasir",
"black seahorse": "kuda laut hitam",
"box turtle": "kura-kura darat",
"freshwater crocodile": "buaya air tawar",
"snow dove": "merpati salju",
"red dragonfly": "capung merah",
"hammerhead shark": "ikan hiu",
"sheep": "domba",
"otter": "berang-berang",
"canary": "burung kenari",
"dinosaur": "dinosaurus",
"brown rabbit": "kelinci cokelat",
"black wolf": "serigala hitam",
"seagull": "burung camar laut",
"swan": "kepala angsa",
"seal": "anjing laut",
"tabby cat": "kucing belang",
"lizard": "kadal",
"African elephant": "gajah Afrika",
"golden spider": "laba-laba emas",
"beluga whale": "paus putih",
"langur monkey": "monyet langur",
"red kangaroo": "kanguru merah",
"cassowary": "burung kasuari",
"grey rabbit": "kelinci abu-abu",
"yellow dragonfly": "capung kuning",
"Siamese cat": "kucing siam",
"buffalo": "kerbau",
"green frog": "katak hijau",
"brown snake": "ular cokelat",
"green beetle": "kumbang hijau",
"cockroach": "kecoa",
"zebra": "zebra",
"python snake": "ular piton",
"bee": "lebah",
"orange butterfly": "kupu-kupu oranye",
"black wild boar": "babi hutan hitam",
"blue spider": "laba-laba biru",
"gourami fish": "ikan gurame",
"grey wolf": "serigala kelabu",
"golden orb spider": "laba-laba jaring emas",
"white goose": "angsa putih",
"snowy owl": "burung hantu salju",
"Persian cat": "kucing persia",
"tarantula": "laba-laba besar",
"white mouse": "tikus putih",
"goldfish": "ikan mas",
"white rabbit": "kelinci putih",
"catfish": "ikan lele",
"brown bear": "beruang cokelat",
"great horned owl": "burung hantu besar",
"giant black spider": "laba-laba hitam besar",
"freshwater crab": "kepiting air tawar",
"osprey": "elang laut",
"red seagull": "burung camar merah",
"yellow butterfly": "kupu-kupu kuning",
"brown wild pig": "babi hutan cokelat",
"stingray": "ikan pari",
"zebra horse": "kuda zebra",
"little owl": "burung hantu kecil",
"purple butterfly": "kupu-kupu ungu",
"white wild boar": "babi hutan putih",
"giant red spider": "laba-laba merah besar",
"giant green seagull": "burung camar hijau besar",
"sea crab": "kepiting air laut",
"tuna fish": "ikan tuna",
"green spider": "laba-laba hijau",
"black cat": "kucing hitam",
"koi carp": "ikan mas koki",
"dark brown rabbit": "kelinci cokelat tua",
"Indian elephant": "gajah India",
"giant black wolf": "serigala hitam besar",
"brown owl": "burung hantu cokelat",
"giant golden orb spider": "laba-laba jaring emas besar",
"black swan": "angsa hitam",
"giant green snake": "ular hijau besar",
"cheetah": "cheetah",
"butterflyfish": "ikan kupu-kupu",
"gazelle": "gazelle",
"octopus": "gurita",
"penguin": "penguin",
"rhinoceros": "badak",
"giraffe": "jerapah",
"hedgehog": "landak",
"iguana": "iguana",
"jaguar": "jaguar",
"kiwi": "kiwi",
"lemur": "lemur",
"mongoose": "mongoose",
"newt": "salamander",
"orangutan": "orangutan",
"panda": "panda",
"quokka": "quokka",
"raccoon": "raccoon",
"sloth": "sloth",
"tapir": "tapir",
"umbrellabird": "burung payung",
"vulture": "burung nasar",
"wombat": "wombat",
"x-raytetra": "ikan x-ray",
"yak": "yak",
"zebu": "zebu",
"albatross": "albatros",
"bison": "bison",
"capybara": "capybara",
"dolphin": "lumba-lumba",
"elephantseal": "gajah laut",
"falcon": "falcon",
"gorilla": "gorila",
"hummingbird": "burung kolibri",
"impala": "impala",
"jellyfish": "ubur-ubur",
"koala": "koala",
"lionfish": "ikan singa",
"mantisshrimp": "udang raksasa",
"narwhal": "narwhal",
"opossum": "opossum",
"quail": "burung puyuh",
"reindeer": "rusa kutub",
"salamander": "salamander",
"tarsier": "tarsier",
"umbrellabird": "burung payung",
"viperfish": "ikan ular",
"whippet": "anjing whippet",
"xraytetra": "ikan x-ray",
"yeti": "yeti",
"zebrashark": "hiu zebra",
"alpaca": "alpaka",
"barracuda": "barracuda",
"chameleon": "bengkarung",
"dugong": "dugong",
"flamingo": "flamingo",
"gnat": "nyamuk kecil",
"humpbackwhale": "humpback whale",
"javanrhinoceros": "badak Jawa",
"kingfisher": "burung rajawali",
"lynx": "lynx",
"macaw": "burung macaw",
"nudibranch": "nudibranch",
"okapi": "okapi",
"platypus": "platipus",
"quokka": "quokka",
"rhinocerosbeetle": "kumbang badak",
"seahorse": "kuda laut",
"toucan": "toucan",
"uakari": "uakari",
"vulture": "burung nasar",
"walrus": "walrus",
"xraytetra": "ikan x-ray",
"yak": "yak",
"zebu": "zebu",
"armadillo": "armadillo",
"binturong": "binturong",
"caiman": "caiman",
"dhole": "anjing liar",
"eland": "eland",
"fossa": "fossa",
"glowworm": "cacing bercahaya",
"horseshoecrab": "keong kuda",
"jaguarundi": "jaguarundi",
"kangaroo": "kanguru",
"lemming": "lemming",
"marmoset": "marmoset",
"nematode": "nematoda",
"orangutan": "orangutan",
"porcupine": "porcupine",
"quokka": "quokka",
"rattlesnake": "ular berbisa",
"shrimp": "udang",
"tapir": "tapir",
"urchin": "bulu babi",
"vole": "vole",
"weasel": "musang",
"xrayfish": "ikan x-ray",
"yellowjacket": "tawon",
"zebu": "zebu",
"avocet": "avocet",
"bongo": "bongo",
"chinchilla": "chinchilla",
"dhole": "anjing liar",
"earwig": "cengkerik",
"firefly": "kunang-kunang",
"goose": "angsa",
"hedgehog": "landak",
"impala": "impala",
"jaguar": "jaguar",
"kinkajou": "kinkajou",
"lemur": "lemur",
"macaque": "monyet ekor panjang",
"nutria": "nutria",
"ocelot": "ocelot",
"pangolin": "pangolin",
"quokka": "quokka",
"redpanda": "red panda",
"seadragon": "naga laut",
"tarsier": "tarsier",
"uakari": "uakari",
"viperfish": "ikan ular",
"wolverine": "wolverine",
"xrayfish": "ikan x-ray",
"yellowjacket": "tawon",
"zebu": "zebu",
"ant": "semut",
"bat": "kelelawar",
"crocodile": "buaya",
"dolphin": "lumba-lumba",
"elephant": "gajah",
"falcon": "falcon",
"gazelle": "gazelle",
"hedgehog": "landak",
"iguana": "iguana",
"jaguar": "jaguar",
"koala": "koala",
"lemur": "lemur",
"mongoose": "mongoose",
"newt": "salamander",
"octopus": "gurita",
"penguin": "penguin",
"rhinoceros": "badak",
"giraffe": "jerapah",
"tiger": "harimau",
"chimpanzee": "chimpanzee",
"komododragon": "komodo dragon",
"tarantula": "tarantula",
"whale": "paus",
"zebra": "zebra"


    }

    return KamusIndonesia.get(kata, "KATA TIDAK DITEMUKAN DALAM KAMUS INDONESIA")