def translateJepang(kata):
    kamusJepang = {
        
#jepang ke jepang
"neko": "neko",
"inu": "inu",
"zou": "zou",
"uma": "uma",
"saru": "saru",
"tora": "tora",
"cho": "cho",
"hebi": "hebi",
"tori": "tori",
"sakana": "sakana",
"ushi": "ushi",
"yagi": "yagi",
"usagi": "usagi",
"niwatori": "niwatori",
"ahiru": "ahiru",
"kangaru": "kangaru",
"kuma": "kuma",
"okami": "okami",
"raion": "raion",
"mushi": "mushi",
"ga": "ga",
"kaba": "kaba",
"kirin": "kirin",
"kaeru": "kaeru",
"kumo": "kumo",
"iruka": "iruka",
"kujira": "kujira",
"koumori": "koumori",
"nezumi": "nezumi",
"katatsumuri": "katatsumuri",
"tokage": "tokage",
"koala": "koala",
"tonbo": "tonbo",
"inko": "inko",
"hato": "hato",
"wani": "wani",
"kani": "kani",
"buta": "buta",
"paiton": "paiton",
"umihoshi": "umihoshi",
"remuru": "remuru",
"rakuda": "rakuda",
"hyou": "hyou",
"yamori": "yamori",
"yamakuzuri": "yamakuzuri",
"karasu": "karasu",
"fukurou": "fukurou",
"hiki": "hiki",
"banteng": "banteng",
"kame": "kame",
"kakatou": "kakatou",
"kame": "kame",
"chimpanji": "chimpanji",
"komodo doragon": "komodo doragon",
"burakku widou kumo": "burakku widou kumo",
"same": "same",
"ebi": "ebi",
"panda": "panda",
"kamome": "kamome",
"koubura": "koubura",
"ramu": "ramu",
"suzume": "suzume",
"ari": "ari",
"sutaanouzu mooru": "sutaanouzu mooru",
"robusutaa": "robusutaa",
"umigame": "umigame",
"chiita": "chiita",
"mOnaaku chou": "mOnaaku chou",
"washi": "washi",
"puma": "puma",
"huriru shaku": "huriru shaku",
"mokusei": "mokusei",
"shika": "shika",
"dokuhirokaeru": "dokuhirokaeru",
"pinku toodo taranchura": "pinku toodo taranchura",
"niwatori": "niwatori",
"umihoshi": "umihoshi",
"saihinocerosu": "saihinocerosu",
"yaseiusagi": "yaseiusagi",
"gacha": "gacha",
"paradaisu baado": "paradaisu baado",
"kingu chou": "kingu chou",
"akuteikku urufu": "akuteikku urufu",
"okapi": "okapi",
"bii itaa": "bii itaa",
"yasei buta": "yasei buta",
"koi": "koi",
"buruu tonbo": "buruu tonbo",
"ken hirameki": "ken hirameki",
"robusutaa": "robusutaa",
"reddo supaida": "reddo supaida",
"howaito umihoshi": "howaito umihoshi",
"hiyake no koara": "hiyake no koara",
"o-mume-sama": "o-mume-sama",
"suichu rui": "suichu rui",
"sasori": "sasori",
"kanuka": "kanuka",
"mizu nezumi": "mizu nezumi",
"suna gani": "suna gani",
"burakku umihoshi": "burakku umihoshi",
"hako kame": "hako kame",
"seisui wani": "seisui wani",
"yuki hato": "yuki hato",
"akai tonbo": "akai tonbo",
"hanmaa heddo shaku": "hanmaa heddo shaku",
"hitsuji": "hitsuji",
"kawauso": "kawauso",
"kanaria": "kanaria",
"kyoryu": "kyoryu",
"chairoi usagi": "chairoi usagi",
"kuroi ookami": "kuroi ookami",
"kamome": "kamome",
"hakucho": "hakucho",
"azarashi": "azarashi",
"tora neko": "tora neko",
"tokage": "tokage",
"afurika zou": "afurika zou",
"kogane no kumo": "kogane no kumo",
"beruga kujira": "beruga kujira",
"ranguru saru": "ranguru saru",
"akai kangaru": "akai kangaru",
"kassowari": "kassowari",
"haiiroi usagi": "haiiroi usagi",
"kiro tonbo": "kiro tonbo",
"chairoi hebi": "chairoi hebi",
"midori mushi": "midori mushi",
"gokiburi": "gokiburi",
"zebra": "zebra",
"paiton hebi": "paiton hebi",
"hachi": "hachi",
"orenji no chou": "orenji no chou",
"kuroi yasei buta": "kuroi yasei buta",
"aoi kumo": "aoi kumo",
"gurame": "gurame",
"haiiro no ookami": "haiiro no ookami",
"konjiki no kumo": "konjiki no kumo",
"shiroi gacha": "shiroi gacha",
"yuki fukurou": "yuki fukurou",
"perushan neko": "perushan neko",
"taranchura": "taranchura",
"shiroi nezumi": "shiroi nezumi",
"kingyo": "kingyo",
"shiroi usagi": "shiroi usagi",
"namazu": "namazu",
"chairoi kuma": "chairoi kuma",
"gureito honnodo": "gureito honnodo",
"kyodai kuroi kumo": "kyodai kuroi kumo",
"seisui kani": "seisui kani",
"osupurei": "osupurei",
"akai kamome": "akai kamome",
"kiiro no chou": "kiiro no chou",
"chairoi yasei buta": "chairoi yasei buta",
"sutinrei": "sutinrei",
"zebura uma": "zebura uma",
"ritoru fukurou": "ritoru fukurou",
"murasaki no chou": "murasaki no chou",
"shiroi yasei buta": "shiroi yasei buta",
"kyodai akai kumo": "kyodai akai kumo",
"midori kamome": "midori kamome",
"umi gani": "umi gani",
"maguro": "maguro",
"midori no kumo": "midori no kumo",
"kuroi neko": "kuroi neko",
"koi koi": "koi koi",
"kurokuroi usagi": "kurokuroi usagi",
"indo zou": "indo zou",
"kyodai kuroi ookami": "kyodai kuroi ookami",
"chairoi fukurou": "chairoi fukurou",
"kyodai konjiki no kumo": "kyodai konjiki no kumo",
"kuroi hakucho": "kuroi hakucho",
"midori hebi": "midori hebi",
"kyodai pinku toodo taranchura": "kyodai pinku toodo taranchura",
"kyodai hanmaa heddo shaku": "kyodai hanmaa heddo shaku",
"kyodai akai kamome": "kyodai akai kamome",
"kyodai aoi chou": "kyodai aoi chou",
"kyodai chairoi yasei buta": "kyodai chairoi yasei buta",
"kyodai namazu": "kyodai namazu",
"kyodai chairoi kuma": "kyodai chairoi kuma",
"kyodai midori kamome": "kyodai midori kamome",
"kyodai zebura uma": "kyodai zebura uma",
"kyodai kuroi neko": "kyodai kuroi neko",
"kyodai koi koi": "kyodai koi koi",
"kyodai indo zou": "kyodai indo zou",
"kyodai kurokuroi usagi": "kyodai kurokuroi usagi",
"kyodai kuroi ookami": "kyodai kuroi ookami",
"kyodai kyodai konjiki no kumo": "kyodai kyodai konjiki no kumo",
"kyodai kuroi hakucho": "kyodai kuroi hakucho",
"kyodai midori hebi": "kyodai midori hebi",
"chītā": "chītā",
"batarifurifisshu": "batarifurifisshu",
"gazeru": "gazeru",
"okutopasu": "okutopasu",
"pengin": "pengin",
"rainoserosu": "rainoserosu",
"jirafu": "jirafu",
"hejjihoggu": "hejjihoggu",
"igwana": "igwana",
"jagwā": "jagwā",
"kīui": "kīui",
"remā": "remā",
"mongūsu": "mongūsu",
"nyūto": "nyūto",
"orangutan": "orangutan",
"panda": "panda",
"kwokka": "kwokka",
"rakūn": "rakūn",
"surōsu": "surōsu",
"tapiru": "tapiru",
"anburera bādo": "anburera bādo",
"varuchā": "varuchā",
"wombatto": "wombatto",
"ekkusu-rei tetora": "ekkusu-rei tetora",
"yakku": "yakku",
"zēbu": "zēbu",
"arubatorosu": "arubatorosu",
"baison": "baison",
"kapibara": "kapibara",
"dorufin": "dorufin",
"erufantoshīru": "erufantoshīru",
"farukon": "farukon",
"gorira": "gorira",
"hanmingubādo": "hanmingubādo",
"inpara": "inpara",
"jerīfisshu": "jerīfisshu",
"koara": "koara",
"raionfisshu": "raionfisshu",
"mantisushirimp": "mantisushirimp",
"nāwaru": "nāwaru",
"oposamu": "oposamu",
"kueiru": "kueiru",
"rēndia": "rēndia",
"saramandā": "saramandā",
"tāshā": "tāshā",
"anburera bādo": "anburera bādo",
"vaipāfisshu": "vaipāfisshu",
"uippetto": "uippetto",
"ekkusu-rei tetora": "ekkusu-rei tetora",
"ieti": "ieti",
"zeburashāku": "zeburashāku",
"arupaka": "arupaka",
"barakūda": "barakūda",
"kamereon": "kamereon",
"dyūgongu": "dyūgongu",
"furamingo": "furamingo",
"natto": "natto",
"hanpbakkuhōru": "hanpbakkuhōru",
"jābanrainoserosu": "jābanrainoserosu",
"kingufishā": "kingufishā",
"rinkusu": "rinkusu",
"makō": "makō",
"nudoburanku": "nudoburanku",
"okapī": "okapī",
"puratipasu": "puratipasu",
"kwokka": "kwokka",
"rainoserosubītoru": "rainoserosubītoru",
"shīhōsu": "shīhōsu",
"tūkan": "tūkan",
"wakari": "wakari",
"varuchā": "varuchā",
"wōrasu": "wōrasu",
"ekkusu-rei tetora": "ekkusu-rei tetora",
"yakku": "yakku",
"zēbu": "zēbu",
"āmadirō": "āmadirō",
"binturongu": "binturongu",
"kaiman": "kaiman",
"dōru": "dōru",
"erando": "erando",
"fossa": "fossa",
"gurōwāmu": "gurōwāmu",
"hōsushukurabu": "hōsushukurabu",
"jaguarundi": "jaguarundi",
"kangarū": "kangarū",
"rebingu": "rebingu",
"māmosetto": "māmosetto",
"nematōdo": "nematōdo",
"orangutan": "orangutan",
"pōkupain": "pōkupain",
"kwokka": "kwokka",
"ratorusunēku": "ratorusunēku",
"shurimp": "shurimp",
"tapiru": "tapiru",
"āchin": "āchin",
"vōru": "vōru",
"wīzaru": "wīzaru",
"ekkusu-rei fissu": "ekkusu-rei fissu",
"yerōjyaketto": "yerōjyaketto",
"zēbu": "zēbu",
"avosetto": "avosetto",
"bongo": "bongo",
"chinchira": "chinchira",
"dōru": "dōru",
"īuwigu": "īuwigu",
"faiyafurai": "faiyafurai",
"gūsu": "gūsu",
"hejjihoggu": "hejjihoggu",
"inpara": "inpara",
"jagwā": "jagwā",
"kinkajū": "kinkajū",
"remā": "remā",
"makakku": "makakku",
"nutria": "nutria",
"osurotto": "osurotto",
"pangorin": "pangorin",
"kwokka": "kwokka",
"reddopanda": "reddopanda",
"shīdoragon": "shīdoragon",
"tāshā": "tāshā",
"wakari": "wakari",
"vaipāfisshu": "vaipāfisshu",
"wōvurīn": "wōvurīn",
"ekkusu-rei fissu": "ekkusu-rei fissu",
"yerōjyaketto": "yerōjyaketto",
"zēbu": "zēbu",
"ari": "ari",
"kōmori": "kōmori",
"wani": "wani",
"iruka": "iruka",
"zō": "zō",
"hayabusa": "hayabusa",
"harikein": "harikein",
"irawā": "irawā",
"jagwā": "jagwā",
"kuma": "kuma",
"ari": "ari",
"sāmandā": "sāmandā",
"taranchura": "taranchura",
"wēru": "wēru",
"zebu": "zebu",


        
# indo ke jepang

"kucing": "neko",
"anjing": "inu",
"sapi": "ushi",
"burung": "tori",
"kelinci": "usagi",
"babi": "buta",
"ikan": "sakana",
"kura-kura": "kame",
"ular": "hebi",
"gajah": "zou",
"harimau": "tora",
"kuda": "uma",
"kirin": "kirin",
"kepiting": "sarugani",
"rubah": "kitsune",
"anjing Akita": "akita inu",
"tengu": "tengu",
"tanuki": "tanuki",
"monyet": "saru",
"burung gereja": "suzume",
"kuda laut": "ushiwaka",
"paus": "kujira",
"ikan koi": "koi",
"lebah": "hachi",
"keong api": "hotaru",
"gurita": "ika",
"merak": "kujaku",
"berang-berang": "kawauso",
"beruang": "kuma",
"kelelawar": "komori",
"kupu-kupu": "konoha",
"kambing liar": "kamoshika",
"kanaria": "kanaria",
"koala": "koala",
"kelinci laut": "korin",
"rusa": "shika",
"burung camar": "shachou",
"singa": "shishi",
"hiu": "shark",
"jaguar": "jaguar",
"kupu-kupu": "joou",
"gurita": "tako",
"tengu": "tengu",
"tanuki": "tanuki",
"burung": "tori",
"kadal": "tokage",
"capung": "tombo",
"buaya": "nigai",
"boneka": "nuigurumi",
"hamster": "hamu",
"ayam muda": "hiyoko",
"gajah laut": "bou",
"burung phoenix": "houou",
"burung hantu": "fukurou",
"penguin": "pen",
"panda": "panda",
"kepiting": "pipi",
"kelabang": "hirameki",
"tapir": "baku",
"bajak laut": "mujaki",
"serangga": "mushi",
"kambing": "yagi",
"gecko": "yamori",
"kuda nil": "rakuda",
"singa": "raion",
"rubah": "regu",
"rusa kutub": "reindeer",
"gembala": "roba",
"hantu Jepang": "rokurokubi",
"buaya": "wani",
"elang": "washi",
"sapi": "ushi",
"burung robin": "ukitsumomiji",
"belut": "unagi",
"ulat daun": "enokimushi",
"udang": "ebi",

# inggris ke jepang

"cat" : "neko",
"dog": "inu",
"elephant": "zou",
"horse": "uma",
"monkey": "saru",
"tiger": "tora",
"butterfly": "cho",
"snake": "hebi",
"bird": "tori",
"fish": "sakana",
"cow": "ushi",
"goat": "yagi",
"rabbit": "usagi",
"chicken": "niwatori",
"duck": "ahiru",
"kangaroo": "kangaru",
"bear": "kuma",
"wolf": "okami",
"lion": "raion",
"beetle": "mushi",
"moth": "ga",
"hippopotamus": "kaba",
"giraffe": "kirin",
"frog": "kaeru",
"spider": "kumo",
"dolphin": "iruka",
"whale": "kujira",
"bat": "koumori",
"mouse": "nezumi",
"snail": "katatsumuri",
"lizard": "tokage",
"koala": "koala",
"dragonfly": "tonbo",
"parrot": "inko",
"pigeon": "hato",
"crocodile": "wani",
"crab": "kani",
"pig": "buta",
"python": "paiton",
"seahorse": "umihoshi",
"lemur": "remuru",
"camel": "rakuda",
"leopard": "hyou",
"pangolin": "yamori",
"porcupine": "yamakuzuri",
"crow": "karasu",
"owl": "fukurou",
"toad": "hiki",
"banteng": "banteng",
"turtle": "kame",
"cockatoo": "kakatou",
"turtle": "kame",
"chimpanzee": "chimpanji",
"komodo dragon": "komodo doragon",
"black widow spider": "burakku widou kumo",
"shark": "same",
"shrimp": "ebi",
"panda": "panda",
"seagull": "kamome",
"cobra": "koubura",
"ram": "ramu",
"sparrow": "suzume",
"ant": "ari",
"star-nosed mole": "sutaanouzu mooru",
"lobster": "robusutaa",
"sea turtle": "umigame",
"cheetah": "chiita",
"monarch butterfly": "mOnaaku chou",
"eagle": "washi",
"puma": "puma",
"whale shark": "huriru shaku",
"wood duck": "mokusei",
"deer": "shika",
"poison dart frog": "dokuhirokaeru",
"pink-toed tarantula": "pinku toodo taranchura",
"rooster": "niwatori",
"sea horse": "umihoshi",
"rhinoceros": "saihinocerosu",
"wild rabbit": "yaseiusagi",
"goose": "gacha",
"paradise bird": "paradaisu baado",
"king butterfly": "kingu chou",
"arctic wolf": "akuteikku urufu",
"okapi": "okapi",
"bee-eater bird": "bii itaa",
"wild boar": "yasei buta",
"koi fish": "koi",
"blue dragonfly": "buruu tonbo",
"swordfish": "ken hirameki",
"lobster": "robusutaa",
"red spider": "reddo supaida",
"white seahorse": "howaito umihoshi",
"sunbathing koala": "hiyake no koara",
"parakeet": "o-mume-sama",
"waterfowl": "suichu rui",
"scorpion": "sasori",
"stag": "kanuka",
"water rat": "mizu nezumi",
"sand crab": "suna gani",
"black seahorse": "burakku umihoshi",
"box turtle": "hako kame",
"freshwater crocodile": "seisui wani",
"snow dove": "yuki hato",
"red dragonfly": "akai tonbo",
"hammerhead shark": "hanmaa heddo shaku",
"sheep": "hitsuji",
"otter": "kawauso",
"canary": "kanaria",
"dinosaur": "kyoryu",
"brown rabbit": "chairoi usagi",
"black wolf": "kuroi ookami",
"seagull": "kamome",
"swan": "hakucho",
"seal": "azarashi",
"tabby cat": "tora neko",
"lizard": "tokage",
"African elephant": "afurika zou",
"golden spider": "kogane no kumo",
"beluga whale": "beruga kujira",
"langur monkey": "ranguru saru",
"red kangaroo": "akai kangaru",
"cassowary": "kassowari",
"grey rabbit": "haiiro no usagi",
"yellow dragonfly": "kiro tonbo",
"brown snake": "chairoi hebi",
"green beetle": "midori mushi",
"cockroach": "gokiburi",
"zebra": "zebra",
"python snake": "paiton hebi",
"bee": "hachi",
"orange butterfly": "orenji no chou",
"black wild boar": "kuroi yasei buta",
"blue spider": "aoi kumo",
"gourami fish": "gurame",
"grey wolf": "haiiro no ookami",
"golden orb spider": "konjiki no kumo",
"white goose": "shiroi gacha",
"snowy owl": "yuki fukurou",
"Persian cat": "perushan neko",
"tarantula": "taranchura",
"white mouse": "shiroi nezumi",
"goldfish": "kingyo",
"white rabbit": "shiroi usagi",
"catfish": "namazu",
"brown bear": "chairoi kuma",
"great horned owl": "gureito honnodo",
"giant black spider": "kyodai kuroi kumo",
"freshwater crab": "seisui kani",
"osprey": "osupurei",
"red seagull": "akai kamome",
"yellow butterfly": "kiiro no chou",
"brown wild pig": "chairoi yasei buta",
"stingray": "sutinrei",
"zebra horse": "zebura uma",
"little owl": "ritoru fukurou",
"purple butterfly": "murasaki no chou",
"white wild boar": "shiroi yasei buta",
"giant red spider": "kyodai akai kumo",
"green seagull": "midori kamome",
"sea crab": "umi gani",
"tuna fish": "maguro",
"green spider": "midori no kumo",
"black cat": "kuroi neko",
"koi carp": "koi koi",
"dark brown rabbit": "kurokuroi usagi",
"Indian elephant": "indo zou",
"giant black wolf": "kyodai kuroi ookami",
"brown owl": "chairoi fukurou",
"giant golden orb spider": "kyodai konjiki no kumo",
"black swan": "kuroi hakucho",
"green snake": "midori hebi",
"giant pink-toed tarantula": "kyodai pinku toodo taranchura",
"giant hammerhead shark": "kyodai hanmaa heddo shaku",
"giant red seagull": "kyodai akai kamome",
"giant blue butterfly": "kyodai aoi chou",
"giant brown wild pig": "kyodai chairoi yasei buta",
"giant catfish": "kyodai namazu",
"giant brown bear": "kyodai chairoi kuma",
"giant green seagull": "kyodai midori kamome",
"giant zebra horse": "kyodai zebura uma",
"giant black cat": "kyodai kuroi neko",
"giant koi carp": "kyodai koi koi",
"giant Indian elephant": "kyodai indo zou",
"giant dark brown rabbit": "kyodai kurokuroi usagi",
"giant black wolf": "kyodai kuroi ookami",
"giant giant golden orb spider": "kyodai kyodai konjiki no kumo",
"giant black swan": "kyodai kuroi hakucho",
"giant green snake": "kyodai midori hebi",
"cheetah": "chītā",
"butterflyfish": "batarifurifisshu",
"gazelle": "gazeru",
"octopus": "okutopasu",
"penguin": "pengin",
"rhinoceros": "rainoserosu",
"giraffe": "jirafu",
"hedgehog": "hejjihoggu",
"iguana": "igwana",
"jaguar": "jagwā",
"kiwi": "kīui",
"lemur": "remā",
"mongoose": "mongūsu",
"newt": "nyūto",
"orangutan": "orangutan",
"panda": "panda",
"quokka": "kwokka",
"raccoon": "rakūn",
"sloth": "surōsu",
"tapir": "tapiru",
"umbrellabird": "anburera bādo",
"vulture": "varuchā",
"wombat": "wombatto",
"x-raytetra": "ekkusu-rei tetora",
"yak": "yakku",
"zebu": "zēbu",
"albatross": "arubatorosu",
"bison": "baison",
"capybara": "kapibara",
"dolphin": "dorufin",
"elephantseal": "erufantoshīru",
"falcon": "farukon",
"gorilla": "gorira",
"hummingbird": "hanmingubādo",
"impala": "inpara",
"jellyfish": "jerīfisshu",
"koala": "koara",
"lionfish": "raionfisshu",
"mantisshrimp": "mantisushirimp",
"narwhal": "nāwaru",
"opossum": "oposamu",
"quail": "kueiru",
"reindeer": "rēndia",
"salamander": "saramandā",
"tarsier": "tāshā",
"umbrellabird": "anburera bādo",
"viperfish": "vaipāfisshu",
"whippet": "uippetto",
"xraytetra": "ekkusu-rei tetora",
"yeti": "ieti",
"zebrashark": "zeburashāku",
"alpaca": "arupaka",
"barracuda": "barakūda",
"chameleon": "kamereon",
"dugong": "dyūgongu",
"flamingo": "furamingo",
"gnat": "natto",
"humpbackwhale": "hanpbakkuhōru",
"javanrhinoceros": "jābanrainoserosu",
"kingfisher": "kingufishā",
"lynx": "rinkusu",
"macaw": "makō",
"nudibranch": "nudoburanku",
"okapi": "okapī",
"platypus": "puratipasu",
"quokka": "kwokka",
"rhinocerosbeetle": "rainoserosubītoru",
"seahorse": "shīhōsu",
"toucan": "tūkan",
"uakari": "wakari",
"vulture": "varuchā",
"walrus": "wōrasu",
"xraytetra": "ekkusu-rei tetora",
"yak": "yakku",
"zebu": "zēbu",
"armadillo": "āmadirō",
"binturong": "binturongu",
"caiman": "kaiman",
"dhole": "dōru",
"eland": "erando",
"fossa": "fossa",
"glowworm": "gurōwāmu",
"horseshoecrab": "hōsushukurabu",
"jaguarundi": "jaguarundi",
"kangaroo": "kangarū",
"lemming": "rebingu",
"marmoset": "māmosetto",
"nematode": "nematōdo",
"orangutan": "orangutan",
"porcupine": "pōkupain",
"quokka": "kwokka",
"rattlesnake": "ratorusunēku",
"shrimp": "shurimp",
"tapir": "tapiru",
"urchin": "āchin",
"vole": "vōru",
"weasel": "wīzaru",
"xrayfish": "ekkusu-rei fissu",
"yellowjacket": "yerōjyaketto",
"zebu": "zēbu",
"avocet": "avosetto",
"bongo": "bongo",
"chinchilla": "chinchira",
"dhole": "dōru",
"earwig": "īuwigu",
"firefly": "faiyafurai",
"goose": "gūsu",
"hedgehog": "hejjihoggu",
"impala": "inpara",
"jaguar": "jagwā",
"kinkajou": "kinkajū",
"lemur": "remā",
"macaque": "makakku",
"nutria": "nutria",
"ocelot": "osurotto",
"pangolin": "pangorin",
"quokka": "kwokka",
"redpanda": "reddopanda",
"seadragon": "shīdoragon",
"tarsier": "tāshā",
"uakari": "wakari",
"viperfish": "vaipāfisshu",
"wolverine": "wōvurīn",
"xrayfish": "ekkusu-rei fissu",
"yellowjacket": "yerōjyaketto",
"zebu": "zēbu",
"ant": "ari",
"bat": "kōmori",
"crocodile": "wani",
"dolphin": "iruka",
"elephant": "zō",
"falcon": "hayabusa",
"gazelle": "gazeru",
"hedgehog": "hejjihoggu",
"iguana": "iguana",
"jaguar": "jagwā",
"koala": "koara",
"lemur": "remā",
"mongoose": "mangūsu",
"newt": "imori",
"octopus": "tako",
"penguin": "pengin",
"rhinoceros": "sai",
"giraffe": "kirin",
"tiger": "tora",
"chimpanzee": "chimpanjī",
"komododragon": "komodo doragon",
"tarantula": "taranchura",
"whale": "kujira",
"zebra": "zeburā"


}

    return kamusJepang.get(kata.lower(), "KATA TIDAK DITEMUKAN DALAM KAMUS BAHASA JEPANG.")